### ISSUE TITLE
Suggestion for locale

### ISSUE THREAD

**Issue by stevieg83** [engram-design/FeedMe#1]
Would be awesome if you were able to map entries to a given locale

**Comment by engram-design** [comment]
Great idea, haven't actually had a chance to use locale's yet, but will add it to the list!

**Comment by timbertens** [comment]
Being from Belgium that is a kind of deal breaker using this otherwise brilliant plugin! Any idea when this will be available?

**Comment by engram-design** [comment]
@timbertens Yhis was actually added in the [0.4.7 release](https://github.com/engram-design/FeedMe/releases/tag/1.4.7). Let me know if you have any issues!
