### ISSUE TITLE
import not happening

### ISSUE THREAD

**Issue by stevieg83** [engram-design/FeedMe#10]
I've come across a problem with Craft where I have a Channel that I made last year called 'Speakers'. I used the entry title field to capture the speaker's last name.

At the time, setting the title format like so

http://d.pr/i/1iYj8

wasn't possible and so viewing entries in that channel just gives a list of last names which is problematic when you have multiple Smiths.

Anyway, I thought I could create a new field `speakerLastName` - plain text, create a json template to output my speakers and then set FeedMe to update the records but doesn't seem to be happening for me.

Here's the initial settings for the feed

http://d.pr/i/1jqBH

and then 

http://d.pr/i/1isVJ

I've also tried importing from an XML feed as well but same thing.

Where am I going wrong?

**Comment by engram-design** [comment]
@stevieg83 I noticed you've got 'check for duplicate' set to id, which you aren't importing. You'll need to change this to a field you're importing - likely the title field. Could you change that and see how that goes?

**Comment by stevieg83** [comment]
hmmm, the same thing :(

I wonder if it's because in this instance I have locale enabled.

On 4 June 2015 at 22:34, Josh Crawford <notifications@github.com> wrote:

> @stevieg83 <https://github.com/stevieg83> I noticed you've got 'check for
> duplicate' set to id, which you aren't importing. You'll need to change
> this to a field you're importing - likely the title field. Could you change
> that and see how that goes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/engram-design/FeedMe/issues/10#issuecomment-109061011>
> .
>



-- 
My Website <http://www.digitalevangelist.net> | Follow me on Twitter
<http://twitter.com/stevieg_83> | Dribbble <http://dribbble.com/stevieg_83>

**Comment by engram-design** [comment]
@stevieg83 I'll have to setup a test - granted I've never tested without a Title field before (generated title fields), so something must be going wrong there...

**Comment by engram-design** [comment]
@stevieg83 Sorry for my delayed response. I've just tested a setup identical to yours, and its all worked as expected. I have even tested with locale's just to be sure. Did you have any further luck? Does that `{title}` field exist by the way?

If you load up the latest version (1.2.8), and head to `/admin/utils/logs`, hopefully something there will shed some light on this issue...

**Comment by stevieg83** [comment]
Afraid not, strange one.

Which locale did it import to?

On 19 June 2015 at 15:54, Josh Crawford <notifications@github.com> wrote:

> @stevieg83 <https://github.com/stevieg83> Sorry for my delayed response.
> I've just tested a setup identical to yours, and its all worked as
> expected. I have even tested with locale's just to be sure. Did you have
> any further luck? Does that {title} field exist by the way?
>
> If you load up the latest version (1.2.8), and head to /admin/utils/logs,
> hopefully something there will shed some light on this issue...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/engram-design/FeedMe/issues/10#issuecomment-113537283>
> .
>



-- 
My Website <http://www.digitalevangelist.net> | Follow me on Twitter
<http://twitter.com/stevieg_83> | Dribbble <http://dribbble.com/stevieg_83>

**Comment by engram-design** [comment]
Just a few different ones (German, Norwegian, English just to test). You can't target a locale specifically to import data into, and instead it simply copies the same data across locale fields.

Maybe we can chat via Slack? I'd just need to check out the feed your using to test...

**Comment by engram-design** [comment]
Closing for now, please reopen if you're still having issues.
