### ISSUE TITLE
Importing JSON feed.

### ISSUE THREAD

**Issue by SeeklesBodil** [engram-design/FeedMe#101]
Hi guys,

When importing de JSON file the plugin does not add the content as entries. Or import anything. We get the following issue:  {"title":["Titel mag niet leeg zijn."]}

Can you help us out?

Thank you in advance!

**Comment by engram-design** [comment]
I can't translate that, but seems to be an issue with the Title not being set. I would need to see your feed, and feed setup. If you can submit a Help request through FeedMe, that'll give me some more information.

**Comment by SeeklesBodil** [comment]
Hi,

Thanks but when i send a support email from the plugin i get the error: Something went wrong. 

Verstuurd vanaf mijn iPhone

**Comment by engram-design** [comment]
Okay, well are you mapping anything to the Title field for your entries? Are you checking any field for duplication handling?

**Comment by SeeklesBodil** [comment]
Yes, we are. What is the correct way to import feed?

Verstuurd vanaf mijn iPhone

**Comment by engram-design** [comment]
If you're able to hold out until tomorrow, we'll be releasing the public beta of [Feed Me 2](https://github.com/engram-design/FeedMe/tree/2.0.0), so should be able to provide a bit more assistance.

**Comment by engram-design** [comment]
Closing for the moment due to inactivity. Re-open if you have more issues.
