### ISSUE TITLE
[Beta 2.0.0]  License error when installing

### ISSUE THREAD

**Issue by jacquesletesson** [engram-design/FeedMe#102]
Got a fatal error when installing Feed Me 2.0.0

`Fatal error: Class 'Craft\FeedMe_License' not found in /var/www/staging-hdk.basedigital.io/craft/plugins/feedme/services/FeedMe_LicenseService.php on line 40`

Commented line 104 of `FeedMePlugin.php` to proceed with the installation.

Let me know how I can help.

Cheers.

**Comment by jacquesletesson** [comment]
It seems to be related to the PHP version.

Installation doesn't work with PHP version 5.5.9 but it works with PHP 5.6.x

To be confirmed

**Comment by engram-design** [comment]
I wonder if the class in `feedme/FeedMe/License/FeedMe_License.php` is not being read in correctly? Maybe re-uploading that?

**Comment by engram-design** [comment]
Probably a bit late now that its installed, but I think this was due to a race condition that the Craft Service was registered (and run) before it had time to import the necessary class. I've updated this as of the latest master.

**Comment by jacquesletesson** [comment]
- Downgraded to the last stable version on the master branch. 
- Uninstall the plugin properly.
- Download the new version for beta 2.0.0.
- Install it and got the same error.

http://staging-hdk.basedigital.io/hdkadmin

**Comment by engram-design** [comment]
Fixed, due to a case-sensitivity issue with class imports. Thanks for the help debugging!
