### ISSUE TITLE
[Beta 2.0.0]  Import into Matrix missing link

### ISSUE THREAD

**Issue by jacquesletesson** [engram-design/FeedMe#104]
In the documentation the link '**Import into Matrix**' is missing.

Would love to see this example and understand how importing content into a Matrix.

http://sgroup.com.au/plugins/feedme/guides/importing-entries

**Comment by engram-design** [comment]
Fixed for now, but still writing up a few of the guides. Will let you know when done!

**Comment by engram-design** [comment]
Documentation added - http://sgroup.com.au/plugins/feedme/guides/importing-into-matrix, as always, feedback welcome.
