### ISSUE TITLE
[Beta 2.0.0] Updating locale 2, updates locale 1 and 2

### ISSUE THREAD

**Issue by jacquesletesson** [engram-design/FeedMe#105]
I have two feeds with data in EN and in DE, they represent the same content in different language.

Both feeds import strategy are set to [update](http://sgroup.com.au/plugins/feedme/feature-tour/creating-your-feed#import-strategy).

The unique identifier is an ID (int).

- When importing EN, CraftCMS fills both locale with EN.
- When importing DE, it updates both locale with DE.

However, for existing entries, only the specified locale's content should be updated, leaving other locale content alone.

**Comment by engram-design** [comment]
I've actually done some testing on this, and its to duplicate how Craft natively handles locale content. For instance - create a new entry (as you normally would) and enter content for one locale. Upon save, you'll see all other locales have the same content.

Feed Me does the same thing - if an entry doesn't exist, it creates the content for all locales. Then any subsequent local-targeted imports only update the locale its targeting. I've just tested this myself - the first feed creates the entry, putting content in all locales. The second feed, targeted to one locale, only updates content for that locale.

**Comment by jacquesletesson** [comment]
@engram-design The problem is that the second feed updates the content for both locales.

Demonstration : http://quick.as/ovJkIlwDj

**Comment by engram-design** [comment]
Yeah, you're right, thanks for the video, will investigate.

**Comment by jacquesletesson** [comment]
@engram-design Any chance you might have the time to look at this issue?

**Comment by engram-design** [comment]
Bump - marking as priority.

**Comment by engram-design** [comment]
This has been implemented as of [Feed Me 2.0 beta 1](https://github.com/engram-design/FeedMe/tree/2.0.0).
