### ISSUE TITLE
[Beta 2.0.0] Only showing first field for Image Asset in FeedMe mapping page

### ISSUE THREAD

**Issue by richhayler** [engram-design/FeedMe#107]
I am attempting to map a JSON feed to a section with an entry type that contains just the default "title" field and an asset field. The image asset field contains a number of other plain text fields (think of these as meta data fields for uploaded images) including "caption", "author" and "location". The issue is that only the "caption" field is displayed so there is no option to map to the other image asset fields.

**Comment by engram-design** [comment]
Seems strange, as they should be shown according to their field layout. Might need to get in touch via email/Slack? Might need to have some hands-on troubleshooting...

**Comment by richhayler** [comment]
No problem. Happy to continue this over email. Should I send through a support request via the FeedMe CP and attach logs etc?

**Comment by richhayler** [comment]
Fixed!
