### ISSUE TITLE
[Beta 2.0.0] Feature Request: Import to assets and asset metadata only without creating new entries

### ISSUE THREAD

**Issue by richhayler** [engram-design/FeedMe#108]
Would love the option to map a feed directly to an assets folder and update image assets fields without having to create new entries or setup a specific section within craft. An example use case would be importing Instagram or facebook photos. An alternative could be an option to auto delete the entries once they had been successfully added as a vehicle to import the images and upload these to an assets folder.

**Comment by engram-design** [comment]
I think the option here is to implement an AssetsFeedMeElementType class, which handles this. I might add this natively at some point (probably for 2.1), but if you need it urgently, you can create your own following the [docs](http://sgroup.com.au/plugins/feedme/developers/element-types) - which are tba. You're welcome to look at [current ElementType implementations](https://github.com/engram-design/FeedMe/tree/2.0.0/feedme/FeedMe/ElementTypes)

**Comment by engram-design** [comment]
Added a little earlier to Beta 1. Assets are now an ElementType you can import directly into with Feed Me 2 Pro.
