### ISSUE TITLE
[Beta 2.0.0] Template Error

### ISSUE THREAD

**Issue by oblongd** [engram-design/FeedMe#109]
When trying use a feed in a template, the following error is returned:

> Neither the property "feed" nor one of the methods "feed()", "getfeed()"/"isfeed()" or "__call()" exist and have public access in class "Craft\FeedMeVariable"

**Comment by engram-design** [comment]
Sorry about that, fixed as of the latest master!

**Comment by oblongd** [comment]
Thanks, Josh!
