### ISSUE TITLE
How do I access xml tag attribute values in templates? 

### ISSUE THREAD

**Issue by taylorehat** [engram-design/FeedMe#11]
I am having some trouble accessing the information in the an ATOM XML feed that has values stored in attributes of an xml tag within the feed. How can I access that withing the craft templates?

XML file:
`<link href="http://linkprovidedbyfeed.com/link">`

Craft templates:
`
{% for post in posts %}
    <li>
        <a href="{{ post.link }}">{{ post.title }}</a>
    </li>
{% endfor %}
`

**Comment by engram-design** [comment]
@taylorehat At the moment, accessing attribute values isn't possible, but will look at adding that very soon.

**Comment by taylorehat** [comment]
Ok good to know. Thank you.

**Comment by engram-design** [comment]
@taylorehat As of the latest version, you can access node attributes through the `attributes` keyword. For your example, you can now use `{{ post.attributes.href }}`
