### ISSUE TITLE
missing Scope "optgroup"

### ISSUE THREAD

**Issue by gudehus** [engram-design/FeedMe#110]
I tested the new feed me 2.0 for craft commerce and ebverytime i tried to import something as a commerce product i got this error.
Craft an Commerce are updated to the last versions.

internal error
Craft\Commerce_TaxCategoryModel missing Scope "optgroup".

**Comment by engram-design** [comment]
Seems odd, never seen that error before. Have you setup Tax Categories correctly?

**Comment by engram-design** [comment]
Fixed as of the latest master in [2.0.0 branch](https://github.com/engram-design/FeedMe/tree/2.0.0)
