### ISSUE TITLE
Dynamic Feed URLs [FR]

### ISSUE THREAD

**Issue by siebird** [engram-design/FeedMe#111]
I'm in the process of a creating a client portal. Currently, I access authenticated API feeds dynamically with [oAuth](https://github.com/dukt/craft-oauth) & [Placid](https://github.com/momentumhq/Placid) plugins in the site templates based off the currently logged in user. This is working great. But I had an idea for data preservation, I'd like to move this outside of the templates to log/cache those feeds.

So I could create a new feed in FeedMe for each client and each service (which I will do for now). However, this becomes cumbersome as I will need to change parameters in the feed url for each client and service.

Ideally, it would be nice to be able to have dynamic feed urls that you could loop through based off settings (ie. section entries which point to a custom field). This might be an edge case, but thought I'd throw it out there.

ie. `https://example.someapp.com/api/invoices?client={id}` => `https://example.someapp.com/api/invoices?client=123456`

**Comment by engram-design** [comment]
Its not quite at that dynamic level yet, but you could use the `url` parameter when calling the feed. For instance:

`wget "http://your.domain/actions/feedMe/feeds/runTask?direct=1&feedId=1&passkey=FwafY5kg3c&url=https://example.someapp.com/api/invoices?client=123456"`

Reference - http://sgroup.com.au/plugins/feedme/feature-tour/trigger-import-via-cron

**Comment by siebird** [comment]
Interesting. I'm wondering if there is a way to trigger multiple cron jobs at once through an array or something. I'll start to dig as this would be perfect. 

Any recommendations or limitations to running too many imports at once?

**Comment by engram-design** [comment]
You can certainly set up multiple cron jobs to fire, pretty sure they fire all at once, but just depends on your setup, and how you want to manage those dynamic properties.

No real limitations running imports - they'll just queue themselves up.

**Comment by siebird** [comment]
Great. Thanks for clarifying. I'll see what I can come up.

**Comment by siebird** [comment]
Following up here if someone else attempts this. Here's a [thread](http://unix.stackexchange.com/questions/140550/curl-for-loop-variable) on using a curl `for` loop with variables. 

> `for num in 100 200 300; do curl "http://foo.bar&skip=$num" ; done`
> Or, you can have the list of numbers in a file (one per line) and use a while loop:
> `while read num;  do curl "http://foo.bar&skip=$num" ; done < nums.txt`
> Or even generate them using seq:
>` seq 100 100 300 | while read num;  do curl "http://foo.bar&skip=$num" ; done `
