### ISSUE TITLE
Switched a feeds entry type setting. Getting error on import

### ISSUE THREAD

**Issue by siebird** [engram-design/FeedMe#112]
Hey, thanks again for all your help with my other requests–much appreciated. I have been doing a little bit of refactoring and moved data from being stored in matrix blocks to entry types. This will improve searching entries, etc., in the application.

Currently, FeedMe is failing on import. I believe it has to do with the exisiting entry's entry type  being already set to a different type that what now the feed is set to. Any ideas on how I can get FeedMe to update the entry type when the feed's strategy is set to 'Add & Update Existing'

**Comment by engram-design** [comment]
You currently can't set the entry type in your feed. This is because entries are essentially compartmentalised by section and entry type. It should only match against existing entries in the same section and entry type that you've specified for you feed. No logging information on the error as to why its failing?

**Comment by siebird** [comment]
That's correct. In the feed settings under 'Entry Type' the feed was originally set to a different type. I switched the 'Entry Type' over to a new type and it's failing. Does that make sense? Meaning:

1. Data imported in as 'Type 1' originally
2. On re-import, the data is set to 'Type 2' and the entry data and type of entry is not updated. FeedMe is failing. 

Btw, I deleted the entries and started over just to keep working on things.

**Comment by engram-design** [comment]
Do your two different entry types have different fields? Did you go through and re-map (and save) your fields after switching the entry type?

**Comment by siebird** [comment]
The entry types how their own set of fields. Re: re-mapping–I believe so but I can't confirm as it was a couple days ago. It may have been a user error (me). I'll run a test again to see if I can reproduce it in the next couple days.

**Comment by engram-design** [comment]
Closing for the moment due to inactivity. Re-open if you have more issues.
