### ISSUE TITLE
[Beta 2.0.0] SuperTable support in 2.0 beta

### ISSUE THREAD

**Issue by dustinwalker** [engram-design/FeedMe#113]
A question instead of an issue, but is expected that I am unable to map SuperTable rows in the beta? 
![supertable](https://cloud.githubusercontent.com/assets/360177/20441632/f4a5ac70-ad8a-11e6-8a16-f5b89b7896c1.png)
 
If this is better to file in the SuperTable repo let me know, and I'll post there instead. 

Thanks!

I am really liking the FeedMe updates.

**Comment by engram-design** [comment]
Yep, gotta put together implementation for Super Table! Should be within the next week.

https://github.com/engram-design/SuperTable/issues/93

**Comment by engram-design** [comment]
Implemented in the [latest master](https://github.com/engram-design/SuperTable/archive/master.zip). Will roll into the next release after some peer testing, so go ahead when you can!
