### ISSUE TITLE
[Beta 2.0.0] Upgrading to 2.6.2952 causes error on CRAFT_BUILD constant

### ISSUE THREAD

**Issue by jpobojewski** [engram-design/FeedMe#115]
After updated to 2.6.2952 via the CP, twas greeted with the error below:

`Use of undefined constant CRAFT_BUILD - assumed 'CRAFT_BUILD'`
`/home/vagrant/3st/craft/plugins/feedme/FeedMe/License/FeedMe_License.php(42)`

I'm using the 2.0 beta.

**Comment by engram-design** [comment]
Fixed as of the latest [master](https://github.com/engram-design/FeedMe/tree/2.0.0).
