### ISSUE TITLE
[Beta 2.0] Modifying User Elements requires Group selection

### ISSUE THREAD

**Issue by miralize** [engram-design/FeedMe#116]
I'm looking at migrating a few fields in our user fields to a matrix but I want to modify the content for all users. When I try to import the fee, it gives me this error: 

`Couldn’t save feed: User Group Type is required`

I like the granularity you have in place, but there are definitely user cases where it needs to apply to all groups. I assume this is due to the way that entries are divided into sections, but user groups don't have a per group set of fields.

![image](https://cloud.githubusercontent.com/assets/1761115/20562822/97ca46ea-b17d-11e6-930f-f517f3d8e0aa.png)

**Comment by engram-design** [comment]
This has been improved in the latest [Feed Me 2.0 beta 1](https://github.com/engram-design/FeedMe/tree/2.0.0) master. User Groups are now no longer required, which makes perfect sense.
