### ISSUE TITLE
[Beta 2.0.0] Upload remote assets to S3 asset source do not behave correctly

### ISSUE THREAD

**Issue by idolab** [engram-design/FeedMe#122]
`keep original`, `keep both`, `replace existing` are all functioning as `keep both`.
haven't tested with other asset sources.

**Comment by idolab** [comment]
Now it was unstable. Assets Uploading stops at some points. Those luckily uploaded assets' but their assetSource are set to `null`.
I can only complete a import when no assets are uploaded.

**Comment by engram-design** [comment]
Firstly, I've changed how [2.0 beta 1](https://github.com/engram-design/FeedMe/tree/2.0.0) handles issues during the feed. It'll now try and process the rest of the feed even if an error is encountered.

Out of interest, how many items do you have in your feed, and how many assets are you trying to upload?

**Comment by engram-design** [comment]
Closed due to inactivity.
