### ISSUE TITLE
[Beta 2.0.0] - Cannot handle asset file names with commas in

### ISSUE THREAD

**Issue by johnwbaxter** [engram-design/FeedMe#123]
If you have asset filename data in your feed, FeedMe halts processing without throwing any errors at all. It just sits there at the point it got to saying it's processing.

Example file name that would fail: "feedme 2 is awesome, so is craft.pdf"

**Comment by engram-design** [comment]
This should be fixed in the latest [2.0 beta](https://github.com/engram-design/FeedMe/tree/2.0.0).
