### ISSUE TITLE
Issue when importing or when i run task 

### ISSUE THREAD

**Issue by Ho0m3s** [engram-design/FeedMe#124]
It seems as if the feedme plugin only creates an entry for the first item on the rss/xml feed. I do see all the feed items on the craft_entryversions table but not the backend in craft or the front end using twig.

The logs shows all the items but they all seem to have the entry_id 
12/30/2016 12:11 PM
The Fresh Pita: Entry successfully added: 966
12/30/2016 12:11 PM
The Fresh Pita: Entry successfully added: 966
12/30/2016 12:11 PM
The Fresh Pita: Entry successfully added: 966
12/30/2016 12:11 PM
The Fresh Pita: Entry successfully added: 966
12/30/2016 12:11 PM
The Fresh Pita: Entry successfully added: 966
12/30/2016 12:11 PM
The Fresh Pita: Entry successfully added: 966
12/30/2016 12:11 PM
The Fresh Pita: Entry successfully added: 966
12/30/2016 12:11 PM
The Fresh Pita: Entry successfully added: 966
12/30/2016 12:11 PM
The Fresh Pita: Entry successfully added: 966
12/30/2016 12:11 PM
The Fresh Pita: Entry successfully added: 966

This happens when i try to run the task or when i go through the process of setting up the feed and then importing.

**Comment by engram-design** [comment]
Can you submit a Help request? Its likely the Primary Element is mis-configured, or the unique identifier.

**Comment by engram-design** [comment]
Closed due to inactivity.
