### ISSUE TITLE
deprecation errors using getBuild

### ISSUE THREAD

**Issue by jpobojewski** [engram-design/FeedMe#125]
Getting errors in Craft:

> craft()->getBuild() has been deprecated. As of Craft 2.6.2951, craft()->getVersion() returns the complete version number (X.Y.Z).

Stack trace reveals that it is in FeedMe_License.php, Line 59:

`$this->_userAgent = 'Craft/' . craft()->getVersion() . '.' . craft()->getBuild();`

Using FeedMe 2.0.0 beta 1

**Comment by engram-design** [comment]
Should be fixed as of the latest master [2.0 beta 1.0.71](https://github.com/engram-design/FeedMe/tree/2.0.0)
