### ISSUE TITLE
[Beta 2.0.0] Do category imports now support hierarchy? 

### ISSUE THREAD

**Issue by Ticolyle** [engram-design/FeedMe#128]
I know that in the 1.0 version parent/child relationships were not supported with imports. 

Has this been added to the beta version? It is unclear on the documentation page: https://sgroup.com.au/plugins/feedme/importing-content/categories

I know this is possible with some of the other import plugins floating around, but I much prefer your interface. 

If this is not yet supported I would like to add this as a Feature Request / Enhancement.

Thanks very much!

**Comment by engram-design** [comment]
Yep, its been on the todo list for a while! Its not incorporated into the [Feed Me 2.0 beta 1](https://github.com/engram-design/FeedMe/tree/2.0.0).
