### ISSUE TITLE
[Beta 2.0.0] Version is too long for the `craft_plugins` table

### ISSUE THREAD

**Issue by green-plastic** [engram-design/FeedMe#129]
The Craft plugins table only allows for varchar 15. The current 2.0.0 beta version is listed as '2.0.0 beta 1 (1.0.71)'.  This gets truncated on some systems but others it causes a MySQL errror. 

Not sure what you'd do other than make sure the version isn't crazy long.

**Comment by engram-design** [comment]
Didn't even think of that, but thanks for bringing that up. I've now reverted it as of the latest master.

**Comment by green-plastic** [comment]
No problem. Just wanted to bring it to your attention.
