### ISSUE TITLE
Duplicates delete only imports one row. 

### ISSUE THREAD

**Issue by Floriswijgergangs** [engram-design/FeedMe#13]
Hi, 

Just updated Craft to 2.4 and Feedme to the latest version. Got some problems with the delete duplicates function, its only updating one row, if I use the update or add method everything works well and its importing more then one row. 
I got nothing strange in logs. So i've no idea what happend. 

Looking forward to your answer.

**Comment by engram-design** [comment]
@Floriswijgergangs Can't seem to duplicate this issue through my testing. Would you be able to provide your feed and mapping setup? Happy to chat through Slack if you'd rather not post here.

And I assume there is at least one entry in the Log saying that the first entry got imported properly?
