### ISSUE TITLE
Inner element fields not mapping.

### ISSUE THREAD

**Issue by shornuk** [engram-design/FeedMe#130]
Using the 2.0 beta. I have an assets field, with a custom field (a plain text field). The option to map to this is shown in my feed set-up, however the field never gets populated when I run the task. No errors, just nothing mapping. 
Tested with uploaded assets and ones just linked via filename. No errors I can see in the logs either.

**Comment by green-plastic** [comment]
@shornuk Do the files get imported as well? I'm having troubles getting my files to import in the beta.

**Comment by engram-design** [comment]
There's been a bit of an overhaul on field-mapping, including inner-element fields. Would you be able to give the latest [2.0 master](https://github.com/engram-design/FeedMe/tree/2.0.0) a go?

**Comment by shornuk** [comment]
Awesome, I'll have a try with this a little later this evening. Will report back once I've tested.

**Comment by shornuk** [comment]
OK, just having a little test. Seems to be mapping the assets fields now. Only issue is that it's wiping my Simplemap data. Did you remove/change that in the latest commit?

**Comment by engram-design** [comment]
Ah - I'll likely need to update the PR for Simplemap due to changes described...

**Comment by shornuk** [comment]
Ah! Only tested on a couple of entries and then suddenly realised it was happening!

**Comment by engram-design** [comment]
Refer to latest PR - https://github.com/ethercreative/simplemap/pull/23

**Comment by shornuk** [comment]
Brill. First tests show everything working OK. That's with an XML feed.
