### ISSUE TITLE
Add Entry ID as a Unique Identifier Option

### ISSUE THREAD

**Issue by patrickhefner** [engram-design/FeedMe#131]
It would be great to have an option to use the Entry ID as the unique identifier. This would be really useful for all export -> transformation -> re-import type use cases. Here is an example:

Content is first created in English and assigned a translation batch number. When the batch is ready for translation an API endpoint is consumed by the translation company to pull down the English content. A JSON file in the same structure is returned for each locale and a Feed Me task is triggered to update the entries with the translated content.

It would also be great to have an "Update Only" option, so that entries can only be updated when the unique identifier is matched.

**Comment by engram-design** [comment]
Element ID mapping has been added to the latest [Feed Me 2.0 beta 1](https://github.com/engram-design/FeedMe/tree/2.0.0), and "Update Only" will be coming in beta 2

**Comment by patrickhefner** [comment]
Thank you for the updates, this is exactly what I was I hoping for. I have tested it and everything is working as brilliantly now.
