### ISSUE TITLE
[Beta 2.0.0] Amazon S3 assets do not import when it has query string 

### ISSUE THREAD

**Issue by lexbi** [engram-design/FeedMe#137]
S3 assets often have query strings, this appeared in my log, sure enough, the asset did not import.

`Asset error: http://s3-eu-west-1.amazonaws.com/client/files/news/news-item.png?mtime=20160414161822 - This file type is not allowed`

I just tested this with a hardcoded link without the query string & it imported ok.

**Comment by engram-design** [comment]
Have you looked at https://sgroup.com.au/plugins/feedme/getting-started/configuration, specifically `cleanAssetUrls`?

**Comment by lexbi** [comment]
I have not, didn't know that was a thing, I shall test it! 

Is it possible to make that default if it isn't working out the box?

**Comment by lexbi** [comment]
That's solved it for me, thanks.

**Comment by engram-design** [comment]
Its certainly a possibility to switch this on by default, but it'll be opt-in for the moment. Glad you got it sorted.
