### ISSUE TITLE
[Beta 2.0.0] Match on elements regardless of status

### ISSUE THREAD

**Issue by joshua-martin** [engram-design/FeedMe#140]
FeedMe doesn't seem to be relating entries that are expired or disabled.

To overcome this, I have added `$criteria->status = null;` to Line 59 in **/feedme/FeedMe/FieldTypes/EntriesFeedMeFieldType.php**

I feel like this line should be added by default as if you have specified in your feed that you need to relate to this page, its status should be irrelevant.

**Comment by engram-design** [comment]
Well picked up, added to the latest Beta 2.
