### ISSUE TITLE
Mapping to entry field with maintain hierarchy breaks unchanged content feature

### ISSUE THREAD

**Issue by ccchapman** [engram-design/FeedMe#1418]
### Description

A feed mapping to an entry field which has the maintain hierarchy option enabled breaks the unchanged content feature. In other words, Feed Me will consider the element changed because the "new" content data only contains the leaf.

<details>

<summary>
Expected output
</summary>

<pre>
Node `#1` skipped. No content has changed.

Array
(
    [productName] => Vinegar-Champagne Reims
    [productBrand] => Array
        (
            [0] => 30205
        )

    [productCategory] => Array
        (
            [0] => 72444
            [1] => 72487
        )

    [productSku] => X-VIN176C
    [productSize] => 500 ML
)

Processing 1 elements finished in 0.19s
</pre>

</details>

<details>

<summary>
Actual debugging output
</summary>

<pre>
productCategory - diff

Array
(
    [0] => Array
        (
            [0] => 72444
            [1] => 72487
        )

    [1] => Array
        (
            [0] => 72487
        )

)

productCategory - existing

Array
(
    [0] => 72444
    [1] => 72487
)

productCategory - new

Array
(
    [0] => 72487
)

Array
(
    [productName] => Vinegar-Champagne Reims
    [productBrand] => Array
        (
            [0] => 30205
        )

    [productCategory] => Array
        (
            [0] => 72487
        )

    [productSku] => X-VIN176C
    [productSize] => 500 ML
)

Processing 1 elements finished in 0.29s
</pre>

</details>

For the time being, I have written a "hack" to workaround the issue.

<details>

<summary>
Expand "hack"
</summary>

```php
Event::on(
    Process::class,
    Process::EVENT_STEP_BEFORE_ELEMENT_SAVE,
    function (FeedProcessEvent $event) {
        $canonicalElement = $event->element
            ->find()
            ->id($event->element->id)
            ->siteId($event->element->siteId)
            ->one();
        $canonicalCategories = $canonicalElement->productCategory->ids();

        if (
            array_slice($canonicalCategories, -1) !==
            $event->contentData["productCategory"]
        ) {
            return;
        }

        $event->contentData["productCategory"] = $canonicalCategories;
    },
);
```
</details>

### Steps to reproduce

1. Create two sections: `Products` and `Product Categories` (the latter should be a structure)
3. Create an entry field: `Product Category` with maintain hierarchy option enabled
4. Create two entries in `Product Categories` section, the second one nested under the first
5. Create Feed Me feed called `Products` and setup mapping to `Product Category` field
6. Process the feed

### Additional info

- Craft version: 4.7
- PHP version: 8.3
- Database driver & version: PostgreSQL 14.9
- Plugins & versions: Feed Me 5.4.0

**Comment by ccchapman** [comment]
Perhaps the `contentData` needs to be passed through something that will "[fill gaps in element](https://github.com/search?q=repo%3Acraftcms%2Fcms%20fillGapsInElements&type=code)" if `maintainHierarchy`.

**Comment by i-just** [comment]
Hi, thanks for reporting and clear description! I raised a PR to adjust this.

**Comment by angrybrad** [comment]
Merged and this will be included in the next release.
