### ISSUE TITLE
foreach() argument must be of type array|object, null given

### ISSUE THREAD

**Issue by plcdnl** [engram-design/FeedMe#1423]
<img width="1429" alt="image" src="https://github.com/craftcms/feed-me/assets/32842043/f3281433-983c-475d-b5f8-87415d639bbf">

<img width="1451" alt="image (4)" src="https://github.com/craftcms/feed-me/assets/32842043/eefad0ad-cdf1-4bfb-bf77-f58fea6e3cbb">

<img width="1458" alt="image (3)" src="https://github.com/craftcms/feed-me/assets/32842043/ae4f046e-11e6-4820-934d-bc22b70f2e49">

<img width="1457" alt="image (2)" src="https://github.com/craftcms/feed-me/assets/32842043/e2aad636-edd2-4598-addc-ae3da81fe9c2">

<img width="1451" alt="image (1)" src="https://github.com/craftcms/feed-me/assets/32842043/eae363fd-b9c4-44f5-ad0b-168c3bb31e52">

**Comment by ax2000** [comment]
Hi there,

I'm also having this issue when trying to import into a matrix field, getting error `foreach() argument must be of type array|object, null given - Matrix.php: 312`

I'm on:
- Craft Pro 5.0.4
- Feed Me 6.0.0

**Comment by chadcrowell** [comment]
Same exact as @ax2000 above

foreach() argument must be of type array|object, null given - Matrix.php: 312

**Comment by curtishenson** [comment]
Incase this helps anyone I got this error when my dataset had two entry types where one entry type was missing fields I was trying to import.

**Comment by JMKelley** [comment]
Getting the same. Is there an estimated release date for this fix @olivierbon?

**Comment by i-just** [comment]
Feed Me 6.0.1 is out now with a fix.

**Comment by aeg-deployment** [comment]
Hi @i-just Did this get fixed in the craft 4 version of the plugin too? 
I'm seeing the following similar error with SuperTable content on a commerce product

`foreach() argument must be of type array|object, null given - SuperTable.php: 190`

Feed-me: 5.9.0
Craft: 4.13.3
