### ISSUE TITLE
Assets import error: Argument #1 ($asset) must be of type craft\elements\Asset, craft\awss3\Fs given

### ISSUE THREAD

**Issue by ax2000** [engram-design/FeedMe#1427]
### Description
When trying to import and create an asset via URL I'm getting the following:

`
Sculptures: sculptureImages - Asset error: https://sculptorsvictoria.asn.au/images/uploads/sculptures/6720/wiskas_n_cream_01.jpg - craft\helpers\Assets::generateUrl(): Argument #1 ($asset) must be of type craft\elements\Asset, craft\awss3\Fs given, called in /var/www/html/vendor/craftcms/feed-me/src/helpers/AssetHelper.php on line 123
`

My assets filesystem is set to s3 but I've tried using a local folder in case that was the issue and I still get the following:

`Sculptures: sculptureImages - Asset error: https://sculptorsvictoria.asn.au/images/uploads/sculptures/6772/beast_with_horns_01.jpg - craft\helpers\Assets::generateUrl(): Argument #1 ($asset) must be of type craft\elements\Asset, craft\fs\Local given, called in /var/www/html/vendor/craftcms/feed-me/src/helpers/AssetHelper.php on line 120`

### Additional info

- Craft version: `Craft Pro 5.0.4`
- PHP version: `8.2.10`
- Database driver & version: `MariaDB 10.2.44`
- Plugins & versions: `Feed Me 6.0.0`

**Comment by i-just** [comment]
Thanks for reporting! Feed Me 6.0.1 is out now with a fix.
