### ISSUE TITLE
Error when setting the stock property in a product import

### ISSUE THREAD

**Issue by ax2000** [engram-design/FeedMe#1428]
### Description
When trying to import products, I'm getting the following error:
`
Setting read-only property: craft\commerce\elements\Variant::stock - Component.php: 206
`

![Screenshot 2024-04-12 at 11 11 26](https://github.com/craftcms/feed-me/assets/2585959/c9bfa46b-3ed8-414c-9504-1d54fd9f1053)

![Screenshot 2024-04-12 at 11 16 24](https://github.com/craftcms/feed-me/assets/2585959/bb002f90-4bf5-4ff8-b682-533be71d393c)

### Additional info

- Craft version: Craft Pro 5.0.4
- PHP version: 8.2.10
- Database driver & version: MariaDB 10.2.44
- Plugins & versions: Feed Me 6.0.0

**Comment by sunnylawn** [comment]
Yeah, also hitting this issue... We're not using the default value but a specific value in the feed element, but same error.

Commerce 5.0.2 / Feed Me 6.0.1

**Comment by mach1media** [comment]
I'm also encountering this issue.

Commerce 5.0.5 / Feed Me 6.0.1

**Comment by lukeholder** [comment]
We have a Commerce 5 compatibility PR #1448, to test it out change your `craftcms/feed-me` requirement in composer.json to:

```json
"require": {
  "craftcms/feed-me": "dev-feature/commerce-5-support as 6.0.1"
  "...": "..."
}
```

Then run `composer update`.

**Comment by angrybrad** [comment]
Feed Me 6.1.0 is out with this change.
