### ISSUE TITLE
[Beta 2.0.0] Not matching on comma separated data

### ISSUE THREAD

**Issue by joshua-martin** [engram-design/FeedMe#143]
For `Main Image`, `Show Categories`, etc. that are comma separated, FeedMe is no longer looping through each item and assigning the asset/category/related entry per value - it is now treating the whole value as the entry for matching.

I've tested this by ticking 'Create categories if they do not exist' and it does indeed add a category for `Dance, Season Highlights` instead of individually assigning `Dance` and `Season Highlights`.

```
{
"RECORDS":[
  {
"GUID":"25046",
"Slug":"tangomotion",
"Title":"Tangomotion",
"Duration":"",
"Credit":"",
"Alternative venue":"Corn Exchange Auditorium",
"Age guide":"",
"Blackbaud Code":"",
"Full price ticket":"19",
"Full price ticket - additional information":"",
"Concession price ticket":"17",
"Concession price ticket - additional information":"",
"Summary":"[..]",
"Standfirst":"[..]",
"Description":"[..]",
"Additional information":"",
"Timestamp":"1475807402",
"Related page(s) custom title":"",
"Additional date information":"",
"Spektrix Event ID":"55202",
"Main Image":"Tangomotion_(3)_EE.jpg,Tangomotion_EE.jpg",
"Downloads":"",
"Additional images":"",
"Hear from our staff":"",
"Show categories":"Dance, Season Highlights",
"Project categories":"",
"Tickets":[],
"Video":"tangomotion-trailer",
"Related shows/projects":"",
"Post show discussion":"",
"Workshop":"",
"Related events":"",
"Related page(s)":"anyday, meet-fred, rosalind",
"SEO Title":"",
"SEO Description":"",
"Spotlight show flag":"0",
"Regular venues":"0",
"Hide date":"0",
"Collapsed date panel":"0",
"Author":"Alex Amey",
"Enabled":"1",
"Post Date":"2017-01-27 00:00:00",
"Expiry Date":"2017-01-27 23:59:59"
}]}
```

Thanks

**Comment by engram-design** [comment]
This is actually a breaking-change as of Beta 2, and was probably a bad idea in the first place. The reason being that an asset, entry or most things have a comma in them - how can we tell if there should be a comma in the filename/title, or if its denoting a new element to match against?

Its a pain to refactor I know, but changing this (if possible) to `"Related page(s)": ["anyday", "meet-fred", "rosalind"],` is the way forward.

**Comment by joshua-martin** [comment]
Stunning, working fine now with the refactored array notation.
