### ISSUE TITLE
foreach() argument must be of type array|object, null given - Matrix.php: 312

### ISSUE THREAD

**Issue by JMKelley** [engram-design/FeedMe#1434]
### Description

Bug when trying to import into a matrix. `foreach() argument must be of type array|object, null given - Matrix.php: 312` 

### Steps to reproduce

1. Try import into a Matrix.
2. Encounter Bug.

### Additional info

- Craft version: 5.0.5
- PHP version: 8.1
- Database driver & version: MariaDB
- Plugins & versions: Feedme 6.0.0

**Comment by i-just** [comment]
Hi, thanks for reporting! This was already raised here: https://github.com/craftcms/feed-me/issues/1423, and a fixed in 6.0.1
