### ISSUE TITLE
[Multisite] "Delete missing elements" deletes entries on all sites

### ISSUE THREAD

**Issue by mnlmaier** [engram-design/FeedMe#1435]
### Description
Honestly, I don't know if this is a bug at all, or if it is intended behavior. A project I am working on has the following requirements:
- Import Jobs in two languages (DE, EN)
- Two feeds, one per language
- Job Translations should be referenced as entry translations
- Jobs which are missing from the feed(s) should be deleted **for the respective language only**

Now when configuring the Feed to delete missing entries, turns out Feed Me deletes also the DE entry if an entry is missing from the EN feed only while being present in the DE feed, which is a problem for us, since jobs will not always be available in both feeds.

Sure, I could work around this myself (disabling the entries and cleaning them out using events) but still, this almost seems like a bug to me.

Is this working as intended, and if yes, is deleting-per-site a functionality which will be implemented in the near future?

### Steps to reproduce

1. Create two feeds referencing the same sections, one per language
2. Import language A, afterwards import language B which is missing one entry

### Additional info

- Craft version: Craft Pro 4.8.7
- PHP version: 8.1.28
- Database driver & version: MariaDB 10.4.32
- Plugins & versions: Feed Me 5.4.0

**Comment by i-just** [comment]
Hi, thanks for reaching out! Could you please let me know what are the propagation settings for the section you’re importing to?

**Comment by mnlmaier** [comment]
Hi @i-just, thanks for the quick reply! :) 

Currently, the section's propagation is set to `Save entries to all sites enabled for this section`. I guess it would _kind of_  work when switching to `Only save entries to the site they were created in`, but as I tested this, I lost the relation between the translations / entries with same vacancyId in multiple sites, which would be nice to have :/

**Comment by i-just** [comment]
Thanks for the info!

Given your propagation method, this is working as expected and deleting per site wouldn’t work with this propagation method.

But it seems like `Let each entry choose which sites it should be saved to` could do what you’re after.

**Comment by mnlmaier** [comment]
@i-just Thanks a lot for the heads-up and quick reply, seems like I missed this one :) it's now working as expected!

**Comment by i-just** [comment]
Not a problem! Glad it’s all working like you want it to!
