### ISSUE TITLE
Entry Field data import issue: "Setting unknown property: craft\\elements\\db\\EntryQuery::elements.id - Component.php: 209"

### ISSUE THREAD

**Issue by joelod** [engram-design/FeedMe#1438]
### Description

When running a JSON feed import, I'm getting the following error:

> {"date":"2024-05-06 12:01:54","type":"info","message":"Test: Preparing for feed processing."}
{"date":"2024-05-06 12:01:54","type":"info","message":"Test: Preparing for database backup.","key":"mistufthflvsmmgtibsw"}
{"date":"2024-05-06 12:01:54","type":"info","message":"Test: Starting database backup.","key":"mistufthflvsmmgtibsw"}
{"date":"2024-05-06 12:01:54","type":"info","message":"Test: Limit: `100` Path: `\/var\/www\/html\/storage\/backups\/feedme-240506_190154_lmxbbempvh.sql`.","key":"mistufthflvsmmgtibsw"}
{"date":"2024-05-06 12:01:54","type":"info","message":"Test: Finished database backup successfully.","key":"mistufthflvsmmgtibsw"}
{"date":"2024-05-06 12:01:54","type":"info","message":"Test: Finished preparing for feed processing."}
{"date":"2024-05-06 12:01:54","type":"info","message":"Test: Starting processing of node `#1`.","key":"yxbvswuemlwegsccmfxt"}
{"date":"2024-05-06 12:01:54","type":"info","message":"Test: Match existing element with data `{\"title\":\"A&A Pump Company\"}`.","key":"yxbvswuemlwegsccmfxt"}
{"date":"2024-05-06 12:01:54","type":"error","message":"Test: `Setting unknown property: craft\\elements\\db\\EntryQuery::elements.id - Component.php: 209`.","key":"yxbvswuemlwegsccmfxt"}
{"date":"2024-05-06 12:01:54","type":"info","message":"Test: Starting processing of node `#2`.","key":"nvkvjnbzuckgzqhsvtzi"}
{"date":"2024-05-06 12:01:54","type":"info","message":"Test: Match existing element with data `{\"title\":\"Advanced Filtration Technologies, Inc.\"}`.","key":"nvkvjnbzuckgzqhsvtzi"}
{"date":"2024-05-06 12:01:54","type":"error","message":"Test: `Setting unknown property: craft\\elements\\db\\EntryQuery::elements.id - Component.php: 209`.","key":"nvkvjnbzuckgzqhsvtzi"}

This seems to be caused by a specific part of my JSON:
`"distributorLocation": ["1733"]`

The `distributorLocation` handle and the ID of 1733 are both valid.
Tested with a few different methods, but getting the same error.
`"distributorLocation": "1733"`
`"distributorLocation": 1733`
`distributorLocation": ["United States & Canada"]`
~~`distributorLocation": "United States & Canada"`~~

### Steps to reproduce

1. Create a new feed to import a JSON of entries
2. Setup all Entry Fields and Content Fields (including the entry field mentioned above)
![imagem](https://github.com/craftcms/feed-me/assets/40759310/9ac1fa14-bd01-4afb-b3de-a555c43e5a4f)
3. Process the newly created Feed Me feed

### Additional info

- Craft version: 5.1.1
- PHP version: 8.2
- Database driver & version: MariaDB 10.4
- Plugins & versions: 6.0.1

### EDIT:
`distributorLocation": "United States & Canada"` worked, so the issue seems to be related with IDs only.

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1440 and will be included in the next release.
