### ISSUE TITLE
[Beta 2.0.0] Broken unique identifier for existing elements

### ISSUE THREAD

**Issue by joshua-martin** [engram-design/FeedMe#144]
Sorry, me again...

It seems that 69d14c074c2a1f34b345f547afc591ed3c0ad267 commit has broken unique identifier for existing elements.

Reverting back to the code you commited (07cdad5f91fb97ba08e16bd65b829ea0e06f90e0) based on [an earlier query of mine](https://github.com/engram-design/FeedMe/issues/126#issuecomment-276416666) has fixed the issue.

Thanks

**Comment by fcaron** [comment]
I have the same issue since updating to the beta 2. It create new entries every time a task is runned even if the entries with the unique identifier already exist.

Thanks

**Comment by engram-design** [comment]
Latest [2.0 master](https://github.com/engram-design/FeedMe/tree/2.0.0) should fix that.

**Comment by joshua-martin** [comment]
Thanking you, can confirm that works correctly now. @fcaron can you confirm too, please?
