### ISSUE TITLE
Undefined array key "fields" - Matrix.php: 122

### ISSUE THREAD

**Issue by AthinaSolvr** [engram-design/FeedMe#1451]
### Description

Undefined array key "fields" - Matrix.php: 122

### Steps to reproduce

1. Feed me -> Run Feed

### Additional info

- Craft version:  "5.1.5"
- PHP version: "8.2"
- Database driver & version:
- Plugins & versions:

Fix: https://github.com/craftcms/feed-me/pull/1450

**Comment by i-just** [comment]
Hi, thanks for reporting! I was able to replicate this error and raised a PR based on your PR with some additional tweaks.

**Comment by angrybrad** [comment]
Merged and will be included in the next release!
