### ISSUE TITLE
Broken Link in Documentation - Field Types 

### ISSUE THREAD

**Issue by kragit** [engram-design/FeedMe#1454]
### Description

On the Content Mapping > [Field Types](https://docs.craftcms.com/feed-me/v4/content-mapping/field-types.html) page:
> Feed Me supports all native [Craft Fields](https://craftcms.com/docs/fields)[ (opens new window)](https://craftcms.com/docs/fields), and even some third-party ones.

The "Craft Fields" link is a 404.

**Comment by AugustMiller** [comment]
Thanks for reporting—included this fix in a recent batch of changes to the documentation!
