### ISSUE TITLE
Unable to import a Categories array

### ISSUE THREAD

**Issue by daniellelecomte** [engram-design/FeedMe#1455]
### Description

Trying to import categories on entries within a CSV file. I have tried the following formats:

```
Cat 1, Cat 2
[Cat 1,Cat 2]
['Cat 1','Cat 2']
```

The first one will work but only imports the first category and ignores any additional ones. I've also tried using the category IDs instead of the titles with the same result.

### Additional info

- Craft version: 5.1.7
- PHP version: 8.2
- Feed-Me 6.1.0

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 

When using CSV file to import your data, commas are used (by default) to separate the columns in the CSV. To separate the data inside a column, you need to use a different separator. By default, Feed Me uses `-|-`, and you can change it via `dataDelimiter`. If you use the default delimiter, then `Cat 1-|-Cat 2` should work as you expect it to.

You can find more about the configuration options [here](https://docs.craftcms.com/feed-me/v4/get-started/configuration.html#configuration-options).

I hope this helps!
