### ISSUE TITLE
Stock doesn't get set when importing Products/variants

### ISSUE THREAD

**Issue by bartrylant** [engram-design/FeedMe#1457]
### Description
I'm importing products with variants. However, the stock is not being imported correctly.

<img width="979" alt="Scherm­afbeelding 133" src="https://github.com/craftcms/feed-me/assets/1434451/20ad54ef-27da-4f9a-a9a3-29b47e318c37">

Here's a screenshot from a product with variants that do have stock in the XML source file (2, 5, 1, ...)

<img width="903" alt="Scherm­afbeelding 135" src="https://github.com/craftcms/feed-me/assets/1434451/7eddf1a7-2203-4a03-ac1e-b58233bef3cc">

<img width="499" alt="Scherm­afbeelding 136" src="https://github.com/craftcms/feed-me/assets/1434451/dbb303e5-0a4b-4d59-8cab-ad49094b75c2">

Could it be that stock for variants is not updated when the variants are already in the inventory? (I'm checking for duplicate products based on the product sku field.)

### Additional info

- Craft version: Craft Pro 5.2.0-beta.1
- PHP version: 8.3.3
- Database driver & version: MySQL 8.3.0
- Plugins & versions: Feed Me 6.1.0

**Comment by bartrylant** [comment]
Any updates on this?

**Comment by i-just** [comment]
Hi, thanks for reporting! We've raised a PR for this. It should be included in the next release. 

If you'd like to test it, change your `craftcms/feed-me` requirement in `composer.json` to:

`"craftcms/feed-me": "dev-bugfix/stock as 6.3.0",`

and then run `composer update`.

**Comment by angrybrad** [comment]
Merged in https://github.com/craftcms/feed-me/pull/1490 and will be included in the next release.
