### ISSUE TITLE
Getting unknown property: craft\fields\PlainText

### ISSUE THREAD

**Issue by bartrylant** [engram-design/FeedMe#1458]
### Description
When importing products & variants into Commerce, I get a 
`Getting unknown property: craft\fields\PlainText` error

### Steps to reproduce

1. Import a valid xml file into a Commerce 5 site
2. As Unique Identifier, I chose Product SKU, which is a custom plain text field I added to the products
3. Run the feed

### Additional info

- Craft version: 5.2.0-beta1
- PHP version: 8.3.3
- Database driver & version: mysql 8.3.0
- Plugins & versions: Feed Me 6.1.0 & Craft Commerce 5.0.8

<img width="1094" alt="Scherm­afbeelding 138" src="https://github.com/craftcms/feed-me/assets/1434451/bbf5ebaa-c7e6-4a50-95ce-e97d6cb9af17">
<img width="163" alt="Scherm­afbeelding 139" src="https://github.com/craftcms/feed-me/assets/1434451/68c0277b-5c29-462e-b2ac-24ba7e9c4348">

**Comment by i-just** [comment]
Hi, thanks for reporting! It’s related to this issue: https://github.com/craftcms/cms/issues/15147, which was fixed in `5.2.0-beta.3`. 
If you update to 5.2.0-beta.3 or later and try again it should work as expected.
