### ISSUE TITLE
Google map field

### ISSUE THREAD

**Issue by wmdhosting** [engram-design/FeedMe#1466]
Latest versions

Google map field
https://plugins.craftcms.com/google-maps?craft5

Import works Ok  when importing directly in field.

When Google map field in matrix, import does not work , nor even when selecting default values..

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this. This issue also affects other nested complex fields (e.g. Table field). Once the PR is merged and released, you'll have to re-map your matrix field for the fix to take effect.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1475 and will be included in the next release.
