### ISSUE TITLE
craft\feedme\base\Element::parseTitle(): Return value must be of type string, null returned - Element.php: 300

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [engram-design/FeedMe#1467]
### Description

No matter what feed field mapping is setup, I continue to get this error:

```
craft\feedme\base\Element::parseTitle(): Return value must be of type string, null returned - Element.php: 300
```

I have tried simplifying the feed but still get this error.

### Steps to reproduce

1. Setup a feed
2. Use https://aaci.getfido.app/api/pages.json for the data
3. Map just the title field to `data/title`
4. run the feed

### Additional info

- Craft version: 5.2.2
- PHP version: 8.3
- Database driver & version: mysql 8
- Plugins & versions: FeedMe 6.1.0

Thanks as always for the help!

**Comment by tommysvr** [comment]
Resolved in support; the fix was to use a different Primary Element

**Comment by chadclark** [comment]
I'm running into this same issue. In my situation, I'm trying to map to the `title` field in the root element. It previews correctly in the feed setup, but fails each time when run.

In debug mode, I receive this TypeError:

```
Unsupported operand types: string + int

1. in /var/www/html/vendor/craftcms/feed-me/src/services/Process.php
at line 205

205: Plugin::info('Starting processing of node `#{i}`.', ['i' => ($step + 1)]);
```
