### ISSUE TITLE
Same image added to multiple Matrix blocks when using 'Use this filename for assets created from URL'

### ISSUE THREAD

**Issue by tommysvr** [engram-design/FeedMe#1471]
### Description
When opting to rename files during the import, only the first image in each array is imported, and that is duplicated across multiple Matrix Blocks.

### Steps to reproduce

1. Create a Matrix field/block type with an image field
2. Using the example feed below, set up Feed Me to import into the image field inside Matrix
3. Ensure 'Use this filename for assets created from URL' is using the filename
5. Imported entry will show the same image twice:
![screenshot_2024_06_28 _10 25](https://github.com/craftcms/feed-me/assets/867566/d8cc0e46-be88-41b4-8d6e-742f47e61c54)

This feature was added here: https://github.com/craftcms/feed-me/pull/1336

### Additional info

- Craft version: 4.10.2
- PHP version: 8.2
- Database driver & version: MySQL 8.0
- Plugins & versions: Feed Me 5.5.0

**Example Feed:**
```
{
  "items": [
    {
      "title": "Entry 1",
      "images": [
        {
          "url": "https://via.placeholder.com/150",
          "filename": "image1"
        },
        {
          "url": "https://via.placeholder.com/200",
          "filename": "image2"
        }
      ]
    },
    {
      "title": "Entry 2",
      "images": [
        {
          "url": "https://via.placeholder.com/250",
          "filename": "image3"
        },
        {
          "url": "https://via.placeholder.com/300",
          "filename": "image4"
        }
      ]
    }
  ]
}
```

**Comment by i-just** [comment]
Thanks for a clear description, Tommy! PR raised.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1472 and will be included in the next 5 and 6 releases.
