### ISSUE TITLE
Missing "Show Details" link when viewing Error logs

### ISSUE THREAD

**Issue by Visiluna** [engram-design/FeedMe#1478]
### Description

When viewing FeedMe logs on the "Logs" tab with "Errors" selected from the "Show logs for:" dropdown, the "Show Details" link is missing. The link is present when viewing by "All" or "Info".

### Steps to reproduce

1. Run an import that produces errors.
2. From the "Logs" tab, select "Errors" from the "Show logs for:" dropdown.

### Additional info

- Craft version: 5.2.5
- PHP version: 8.2.20
- Database driver & version: MySQL 8.0.36
- Plugins & versions: FeedMe 6.2.0, CKEditor 4.1.0

- Browser: Safari Version 17.5 (19618.2.12.11.6)

**Comment by i-just** [comment]
Hi, thanks for getting in touch! This is working as expected. The filtering is set to only show rows of a given level (info or error). If there’s a row that has sub-rows of the same type, the “Show Details” link will be shown.

The error-type rows usually don’t have any sub-rows that would also be of type error. This means that there are no details to show, so the “Show Details” link isn’t rendered. If there was an error that had a sub-row that was also of type error, the link would show.
