### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by rensverschuren** [engram-design/FeedMe#148]
When I run the import, I get a `Trying to get property of non-object` error:

`craft/plugins/feedme/variables/FeedMeVariable.php:135`

Craft version: 2.6.2960
FeedMe version: latest commit on the `2.0.0` branch

The import runs from a JSON feed, also auto-uploading assets.

Edit: asset source is Amazon S3

**Comment by engram-design** [comment]
Now fixed in the latest master for [2.0](https://github.com/engram-design/FeedMe/tree/2.0.0). This can happen if its unable to find the source ID for the asset field.
