### ISSUE TITLE
FeedMe doesn't select entries from custom sources when importing

### ISSUE THREAD

**Issue by DenyEs** [engram-design/FeedMe#1488]
### Description
I have an entries field where you can only select entries from a custom source. The custom source is only meant to show entry with certain entry type. My XML file has a node which looks like the following

```
<entry>
    <locations>One-|-Two-|-Three</locations>
</entry>
```

### Steps to reproduce

1. Create a channel
2. Create an entry type
3. Create some entries with newly created entry type
4. Create custom source in entries which only shows entries with entry type created in the first step
5. Create a field that can only select entries from custom source
6. Assign the field to a channel created in step 1
7. Map feedme import into the field created in step 5

Desired outcome would to be see entries from custom source assigned to the field, but that's not happening.

Now if I create a custom channel where I create a bunch of entries and change the field to pull entries from this channel, it asigns them without any issues.

Am I right in thinking that feedme can't find a source for entries I am trying to import to it leaves it blank?

My feed-me.php file looks like and I know that dataDelimiter works as it imports into other sections just fine.

```
<?php

return [
    '*' => [
        'dataDelimiter' => '-|-',
    ]
];
```

### Additional info

- Craft version: 5.2.9
- PHP version: 8.3.6
- Database driver & version: MySQL 8
- Plugins & versions: FeedMe 6.2.1

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1504 and will be included in the next v5 and v6 releases.
