### ISSUE TITLE
Filename Title

### ISSUE THREAD

**Issue by wmdhosting** [engram-design/FeedMe#1497]
### Description

![2024-08-21_11-41-38](https://github.com/user-attachments/assets/9ecd3510-17ef-46a7-9b7e-d1fccf4867b1)

- Craft version: Craft Pro 5.2.9
- PHP version: 8.3.9
- Database driver & version: MySQL 8.0.36
- Plugins & versions: 6.2.1

**Comment by i-just** [comment]
Hi, thanks for getting in touch. 

The “Use this filename for assets created from URL” value will be used as the imported file’s filename. As per Craft’s native behaviour, when you upload a file, the filename is parsed into a title of the asset and you can change it later on by editing the asset. 

When importing to a relation field, like assets, you don’t have control over the element’s (asset’s) title. If you need to control both the file’s filename and the asset’s title, you might want to consider importing your assets first and then using them to populate the relation field you showed in your screenshot.

I hope this helps!
