### ISSUE TITLE
Selectable Element fields not matching the Entry type's field layout

### ISSUE THREAD

**Issue by tibbis** [engram-design/FeedMe#1499]
### Description
The Element fields available to map within a given Entries field don't match the fields from that Entry type's field layout.

**This has been reported previously several times but has been closes on previous updates. However it seems the bug has come back again.** 

### Steps to reproduce
Example: [Issue 825](https://github.com/craftcms/feed-me/issues/825)

FeedMe plugin version: 6.3.0

### Additional info

- Craft version: Pro 5.3.5
- PHP version: 8.2.22
- Database driver & version: MySQL 8.0.36
- Plugins & versions:

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

To clarify, how the inner fields mapping works in terms of entries:
- if you have an entries field set to only have a single source e.g. section `blog` and that section only has one entry type, e.g. `article` - the outcome should be that some (more on that later) custom fields from the `article` entry type's field layout will show as available for inner mapping;
- if you have an entries field set to only have a single section and that section has multiple entry types, the first entry type will be used;
- if you have an entries field set to have multiple sources selected, then the first section and its first entry type will be used;

- note that I mentioned that only some custom fields will be available for inner mapping; for example, you can’t map relation (assets, categories etc), table, or matrix fields this way;

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/pull/1503 and will be included in the next v5 and v6 releases.
