### ISSUE TITLE
Importing product data into Craft Commerce doesn't create variants

### ISSUE THREAD

**Issue by vincecorradetti** [engram-design/FeedMe#1514]
### Description
I'm following the documentation on importing product data via Feed Me into Craft Commerce: https://docs.craftcms.com/feed-me/v6/guides/importing-commerce-products.html.

I have a completely fresh install of CraftCMS, Craft Commerce, and Feed Me. All on their latest versions.

I've set up the feed according to the documentation and it successfully imports the products, but no variants are created:
![image](https://github.com/user-attachments/assets/b2c71c81-549c-4e9d-92bc-33033a636b8d)

Debugging it also shows that the variants are being mapped, but not created:
![image](https://github.com/user-attachments/assets/7dc7aa70-5062-4d7a-bff3-5dc9daa39866)

### Steps to reproduce

1. Completely fresh install of CraftCMS, Craft Commerce, Feed Me
2. Add example `products.json` from the documentation into the `@root`.
3. Set up the feed as specified in documentation
4. Run feed, everything checks out except the variant creations

### Additional info

- Craft version: 5.4.4
- PHP version: 8.2
- Database driver & version: MySQL (8.0)
- Plugins & versions: Feed Me (6.3.0), Craft Commerce (5.1.2)

**Comment by v11ncent** [comment]
I also see that the documentation for this has a screenshot of the product being updated at 8/13/2024:
![feedme-guide-commerce-product-success-single 6GlowugR](https://github.com/user-attachments/assets/2233ba27-de2e-411d-a561-8d9a3f7d5098)

So I've reverted Craft, Craft Commerce, and Feed Me to versions before 8/13 hoping I can get it working and it still doesn't work for me.

**Comment by vincecorradetti** [comment]
I was able to successfully import variants if I ran the import twice.

**Comment by i-just** [comment]
Hi, thanks for reporting! It looks like this was also reported here: https://github.com/craftcms/feed-me/issues/1525. I raised a PR for it.

**Comment by i-just** [comment]
Feed Me 6.4.1 is out with the Commerce Variant import fix.

**Comment by vincecorradetti** [comment]
Thank you!
