### ISSUE TITLE
"Unable to match an existing element." when updating against a slug

### ISSUE THREAD

**Issue by jimmerk** [engram-design/FeedMe#1515]
### Description

Using Craft 5.4.4 and FeedMe 6.3.0, MySQL 8

I have about 80 existing articles that I'm trying to update with title tags and meta descriptions from an xml file. I tried this with a cvs file first and got the "unable to match" error. So I "summoned" an xml schema and exported the data as xml. Still getting the same error. I'm sure the slugs exist and should match. I've tried selected the root from three different levels in the hierarchy (including one that lists the record count). I also tried to match on the Title. Same issue.

The xml schema and a sample record...
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="posts">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="post" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="BlogName" type="xs:string"/>
              <xs:element name="PostTitle" type="xs:string"/>
              <xs:element name="PostSEOTitle" type="xs:string"/>
              <xs:element name="PostLanguage" type="xs:string"/>
              <xs:element name="Slug" type="xs:string"/>
              <xs:element name="Author" type="xs:string"/>
              <xs:element name="Tags" type="xs:string"/>
              <xs:element name="MetaDescription" type="xs:string"/>
              <xs:element name="PublishDate" type="xs:date"/>
              <xs:element name="LastModifiedDate" type="xs:date"/>
              <xs:element name="PostBody" type="xs:string"/>
              <xs:element name="FeaturedImageURL" type="xs:string"/>
              <xs:element name="HeadHTML" type="xs:string"/>
              <xs:element name="Status" type="xs:string"/>
              <xs:element name="Archived" type="xs:boolean"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<posts>
	<post>
		<BlogName>stuff</BlogName>
		<PostTitle>stuff</PostTitle>
		<PostSEOTitle>stuff</PostSEOTitle>
		<PostLanguage>stuff</PostLanguage>
		<Slug>stuff</Slug>
		<Author>stuff</Author>
		<Tags>stuff</Tags>
		<MetaDescription>stuff</MetaDescription>
		<PublishDate>stuff</PublishDate>
		<LastModifiedDate>stuff</LastModifiedDate>
		<PostBody>stuff</FeaturedImageURL>
		<HeadHTML/>
		<Status>stuff</Status>
		<Archived>stuff</Archived>
	</post>
</posts>
</xml>
```

### Steps to reproduce

1. Run the update feed while trying to match on a slug

Results in errors like this...
*Unable to match an existing element. Have you set a unique identifier for ["slug"]? Make sure you are also mapping this in your feed and it has a value. - Element.php: 178.*

Any help would be greatly appreciated! Thanks.

**Comment by jimmerk** [comment]
Still having trouble with this after the recent update.

**Comment by i-just** [comment]
Hi, thanks for getting in touch! Could you please share a screenshot of the entire mapping screen and also let me know what you have selected as the Primary Element?

**Comment by jimmerk** [comment]
![Image](https://github.com/user-attachments/assets/ff393b88-b2f9-436e-bcb4-bee322cae328)

I'm only updating two fields in the meta section. I've tried using all three levels in the hierarchy for the Primary Element, including /root, /posts, and /posts/post.

**Comment by i-just** [comment]
Thanks for the info! 

Your Primary Element should be /posts/post. There’s a bit more info on this subject [here](https://docs.craftcms.com/feed-me/v6/feature-tour/primary-element.html#primary-element).

As for the error you’re getting, the field you want to use as the unique identifier must also be mapped. Without that mapping, the import has no data to match the elements in the system against. [Here’s](https://docs.craftcms.com/feed-me/v6/feature-tour/primary-element.html#primary-element) a bit more info about unique identifiers.

I hope this helps!

I will close this now, but feel free to reach out again if you run into any further problems.

**Comment by jimmerk** [comment]
I really didn't want to wake up today as the guy who didn't read the docs! Thank you. It worked.

**Comment by i-just** [comment]
Glad to hear it's all working as expected now 🙂
