### ISSUE TITLE
Status of "0" being ignored on import

### ISSUE THREAD

**Issue by johndwells** [engram-design/FeedMe#152]
I have been trying to set an imported entry's Status based on a `1` or `0` value coming from a JSON feed, but found that the resulting status was always `true`.  Digging in, I believe it is because of line 116 of EntryFeedMeElementType.php:

    if (isset($value['data']) && $value['data'] == '') {
        continue;
    }

Since `$value['data']` is set to `0`, the `==` is evaluating to _`false`_ and thus never making it further.

**Comment by engram-design** [comment]
Firstly, I believe this was address before the v2 beta 2. In fact, the example code allows for a value of `0` (`$value['data']` is set and not equal to a blank string).

I've just tested this locally, so maybe you're on a previous version? See https://github.com/engram-design/FeedMe/commits/2.0.0 for the latest.

And lastly, can you check the element attributes by using the Debug action (there's a icon link to it in the Feed Me index)

**Comment by johndwells** [comment]
This is based off of the most recent code available to the 2.0.0 branch, just downloaded this morning when working to debug this.

But actually PHP's `==` is going to evaluate `0` as being "equal" to an empty string, it's a "truthy" condition ; when I change that comparison operator to `===`, then the condition evaluates correctly.

In the debug, the `[enabled]` attribute is equal to an array with only `data` attribute, set to `0`.

**Comment by engram-design** [comment]
Well talk about amateur hour - you're 100% correct regarding `===`, I didn't even check that. Notably, my testing with `{"enabled": "0"}` and not `{"enabled": 0}` is what threw things off (the former working).

Thanks for this, much appreciated.
