### ISSUE TITLE
Product variant data doesn't get updated - Feed Me 5.8.0

### ISSUE THREAD

**Issue by ax2000** [engram-design/FeedMe#1521]
### Description
This issue _might_ be related with [this ticket](https://github.com/craftcms/feed-me/issues/1457) but can't be sure. I'm using Feed Me for Craft 4.x and that issue seemed to be for Craft 5.x

When importing product data for a brand new product, all data gets imported as intended.

The issue seems to happen when updating data for an existing product. All the updates for the normal product fields come through correctly but none of the variant fields get updated somehow.

![Screenshot 2024-10-02 at 15 20 30](https://github.com/user-attachments/assets/e8f4c349-ceed-49d1-92ea-cf143836af21)

![Screenshot 2024-10-02 at 15 21 18](https://github.com/user-attachments/assets/6938f99e-d95f-4d58-8200-26fcd78ae4e4)

![Screenshot 2024-10-02 at 15 22 21](https://github.com/user-attachments/assets/0b625d47-7785-4867-9d9e-463b80d39378)

![Screenshot 2024-10-02 at 15 23 20](https://github.com/user-attachments/assets/d1405417-4a62-4424-8d75-5bf4fb74a629)

### Steps to reproduce

1. Import a brand new product via feed me
2. Update all product data from feed including variant fields and run import again. The common product data gets updated properly whilst variant data doesn't.

### Additional info

- Craft version: 4.12.4.1
- PHP version: 8.2.23
- Database driver & version: MariaDB 10.2.44
- Plugins & versions: Feed Me 5.8.0, Commerce 4.6.12

**Comment by i-just** [comment]
Hi, thanks for getting in touch! Could you clarify a few things, please?

- is your product set to have one variant?
- when you say, “Update all product data from feed including variant fields and run import again.”, does it mean you updated the `pku` value in your feed, too?

**Comment by ax2000** [comment]
Thanks for your reply @i-just 

To answer your questions:

- The product is set to have only one variant
- The pku didn't get updated in the feed (it always remains the same for each existing products). The feed is set to match entries by the external's API `warehouse_product_id`

Please find below screenshots of the full feed config in case they help.

![Image](https://github.com/user-attachments/assets/b1bdb777-7298-4915-98a8-8d45e7815ac8)

![Image](https://github.com/user-attachments/assets/c6a0d232-ffaf-4701-b94c-a5d49988500c)

![Image](https://github.com/user-attachments/assets/4a626d41-7112-4a39-ac36-d142a19242d6)
![Image](https://github.com/user-attachments/assets/1dbcdd9f-6b32-4aec-afe6-0e0bf8232cd6)
![Image](https://github.com/user-attachments/assets/5d7cceef-f4f6-413d-82e8-ff460873fba6)

![Image](https://github.com/user-attachments/assets/fc2f2b65-5e3c-4159-9f36-18684ced1807)

Let me know if that helps or if you'd need me to provide anything else.

**Comment by i-just** [comment]
Thanks, @ax2000, that’s all very useful! Unfortunately, I still can’t replicate this issue, nor do I see anything obvious in the screenshots you provided. 
Are you using any other plugins or modules? If so, could you disable them (modules too), leaving only Commerce and Feed Me and see if that changes anything? If that doesn’t change anything, would you mind sharing a snippet of your feed?

**Comment by Asociateone** [comment]
We had the same issue, we downgraded FeedMe to `5.7.0` to resolve this issue. 

we use the slug as UID. 
Craft version: `4.12.5`

**Comment by ax2000** [comment]
Thanks @i-just @Asociateone  I've got a few plugins installed and also a custom module in place. Please bear with me whilst I test disabling them and performing more tests and I'll get back to you asap.

**Comment by ax2000** [comment]
Apologies for the delay getting back to this.

After reviewing it turns out that the `pku` was getting updated as well and craft wasn't updating the variant fields (price, weight, width, etc) due to the `pku` not matching.

When `pku` field remains unchanged, the variant data updates as expected.
