### ISSUE TITLE
Hierarchy not maintained when importing categories with different levels (5.8.0)

### ISSUE THREAD

**Issue by jmauzyk** [engram-design/FeedMe#1522]
### Description

After upgrading to 5.8.0, categories imported by title to a category field do not maintain hierarchy and include ancestors if there are more than one category with different levels.

After import with 5.7.0:
<img width="204" alt="Screenshot 2024-10-02 at 9 52 46 AM" src="https://github.com/user-attachments/assets/bb97630c-a874-4cf4-a5d7-a0c49fcb47ee">

After import with 5.8.0:
<img width="206" alt="Screenshot 2024-10-02 at 9 50 15 AM" src="https://github.com/user-attachments/assets/89dd3b1c-9dbf-4221-a571-84c9ac87913b">

### Steps to reproduce

1. Set up an element data import and configure a node to import categories by title to a category field.
2. Import element data with a node that contains more than one category that have different levels in the category structure.

### Additional info

- Craft version: Pro 4.12.5
- PHP version: 8.2.4
- Database driver & version: PostgreSQL 14.7

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I’m unable to replicate this on a clean install. Are you importing into an Entry? Could you share a snippet of your feed and a screenshot of the mapping screen?

**Comment by jmauzyk** [comment]
Sorry for the delayed response here. I'm importing into a Product element. Here's a snippet of the category data in the XML feed:
```xml
    <Categories>
        <Category><![CDATA[Frame & Fork]]></Category>
        <Category><![CDATA[Parts]]></Category>
    </Categories>
```

Here is a screenshot of the associated mapping:
![Image](https://github.com/user-attachments/assets/bfb0b520-b3a4-48b0-8d9d-5bdb31bed068)

I dug into this a bit more to try and figure out the source of the issue, and while examining the relations table I noticed that there was a category saved in the relations table that wasn't displaying. The category was one by the same name (Frame & Fork), but in a different category group. It seems that something changed in 5.8.0 so that when searching for category matches by title, it no longer scopes to the category groups defined by the field. As a result, both categories with matching titles are saved to the relation field, which in turn prevents the parent category from being saved.

**Comment by i-just** [comment]
Thanks for the additional info! It sounds like you might be running into this one: https://github.com/craftcms/feed-me/issues/1530. PR's already raised, but hasn't been released yet.

**Comment by angrybrad** [comment]
Feed Me 5.9.0 and 6.6.0 are out with this fix!

https://github.com/craftcms/feed-me/releases/tag/5.9.0
https://github.com/craftcms/feed-me/releases/tag/6.6.0
