### ISSUE TITLE
Duplicating a feed does not change the passkey on the new feed created

### ISSUE THREAD

**Issue by jamesmacwhite** [engram-design/FeedMe#1526]
### Description

When duplicating a feed the passkey is copied from the existing feed. Depending on how you view the use/purpose of the passkey, it is technically there to provide an extra layer of security in addition to just being able to pass a feed ID from a web request to a trigger a feed import. Having it not changed from an existing feed could be seen as potentially a security issue if you have a passkey for another feed and just increment the ID to try and guess or enumerate.

Not a bug technically but perhaps something that can be reviewed?

### Steps to reproduce

1. Duplicate an existing Feed Me feed
2. The passkey value provided will be the same from the original feed

### Additional info

- Craft version: 5.4.6
- PHP version: 8.3.8
- Database driver & version: MySQL
- Plugins & versions: Feed Me 6.4.0

**Comment by jamesmacwhite** [comment]
As the field helper references it as a unique string, the duplication action contradicts that.
![Image](https://github.com/user-attachments/assets/2fef72fa-83c7-476d-813a-5c7ed9f9a1c6)

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by i-just** [comment]
Feed Me 5.8.2 and 6.5.0 are out with this change.

**Comment by jamesmacwhite** [comment]
@i-just Thank you!
