### ISSUE TITLE
parseTwig doesn't work to generate SKU when importing Commerce Product

### ISSUE THREAD

**Issue by hassanmah** [engram-design/FeedMe#1527]
### Description
I have `parseTwig` set to true in `feed-me.php`. When I set SKU to use "Default Value" and set the value to `{slug}`, the variants SKU is set to the string {slug} and not the slug of the product.

I've seen these two issues in the past for other versions of the plugin. #1035 and #1326 

![Image](https://github.com/user-attachments/assets/8f51d20e-f1fd-4fac-9959-5a1a8b4a738a)
![Image](https://github.com/user-attachments/assets/3d027c5a-a8f7-44a4-a6fd-63460ec1b126)

### Steps to reproduce

1. Set `parseTwig` set to true in feed-me.php
2. Set up a feed
3. For SKU, use "Default Value" and set the value to `{slug}`

### Additional info

- Craft version: 5.4.6
- PHP version: PHP 8.3
- Database driver & version: MySQL 8
- Plugins & versions:
Feedme: 6.4.0
Commerce: 5.1.3

**Comment by angrybrad** [comment]
This should be resolved in Feed Me 5.8.1 and 6.4.1.
