### ISSUE TITLE
[Beta 2.0.0] Table Field Import Causes Error - 'mb_convert_case() expects parameter 1 to be string, array given'

### ISSUE THREAD

**Issue by john-henry** [engram-design/FeedMe#153]
I have a fairly simple JSON/XML file. I tried both to be sure.

I am mapping each item (Data) to my table columns.

Below is a sample of the XML

```
<?xml version="1.0" encoding="UTF-8" ?>
<rss>
    <channel>
        <Data>
	    <carat>0.30 carat</carat>
            <index>1488</index>
	    <weeklyPriceChange>-0.0006</weeklyPriceChange>
	    <monthlyPriceChange>0.0031</monthlyPriceChange>
	    <yearlyPriceChange>-0.0006</yearlyPriceChange>
    </Data>
</channel>
</rss>
```

Import fails and when I debug I get

> mb_convert_case() expects parameter 1 to be string, array given

In the trace I can see the following

> ../craft/app/helpers/StringHelper.php(571): mb_convert_case(array("col1" => "0.30 carat", "col2" => "1488", "col3" => "-0.0006", "col4" => "0.0031", ...), 1, "UTF-8")
../craft/app/helpers/DbHelper.php(464): Craft\StringHelper::toLowerCase(array("col1" => "0.30 carat", "col2" => "1488", "col3" => "-0.0006", "col4" => "0.0031", ...))
../craft/app/fieldtypes/BaseFieldType.php(226): Craft\DbHelper::parseParam("content.field_myTableName", array(1 => array("col1" => "0.30 carat", "col2" => "1488", "col3" => "-0.0006", "col4" => "0.0031", ...)), array(":locale" => "en_gb"))
../craft/app/services/ElementsService.php(870): Craft\BaseFieldType->modifyElementsQuery(Craft\DbCommand, array(1 => array("col1" => "0.30 carat", "col2" => "1488", "col3" => "-0.0006", "col4" => "0.0031", ...)))

Seems to have trouble with the table array. This is as far as my troubleshooting got unfortunately.

**Comment by engram-design** [comment]
Just tested this locally with the following mapping setup:

![screen shot 2017-02-09 at 1 51 26 pm](https://cloud.githubusercontent.com/assets/1221575/22767397/1856ae1e-eecf-11e6-8ab7-12077a3c9de0.png)

Results in:

![screen shot 2017-02-09 at 1 53 14 pm](https://cloud.githubusercontent.com/assets/1221575/22767406/2441be8a-eecf-11e6-9018-80956bb3b68e.png)

Are you on the latest beta 2?

**Comment by john-henry** [comment]
Yes I'm on Feed Me 2.0.0 beta 2 (Pro).

I just uninstalled and replaced files and reinstalled to be sure.

Craft CMS 2.6.2961

I deleted field and recreated it as you have there

It finally worked after I switch off dev mode and turned on again

Must have been some form of cache even though I cleared it a number of times
