### ISSUE TITLE
Matches a category with the same name from the wrong category group.

### ISSUE THREAD

**Issue by StanSteen** [engram-design/FeedMe#1530]
### Description
When using the Feed Me plugin to import data from Mercury, the configuration is set to match category fields from the Mercury data and import them into specific Craft entries. In our case, there were two category groups with categories that shared the same name.

For example:
Category Group A: "Vacancy Branch" includes a category named "Medical Devices."
Category Group B: "News Type" also has a category named "Medical Devices."
When the import was executed, instead of assigning the "Medical Devices" category from Vacancy Branch, it incorrectly assigned the one from News Type due to the identical category name.

### Steps to reproduce

1. Create two category groups in Craft CMS:
    -Category Group A (e.g., Vacancy Branch)
     -Category Group B (e.g., News Type)
2. Add a category with the same name to both category groups (e.g., Medical Devices).
3. Configure Feed Me to import categories from Mercury and match based on the category name.
4. Set Feed Me to import into an entry, and specify that it should use categories from Vacancy Branch.
5. Run the import.
6. Observe that the category imported is from the wrong category group (i.e., it assigns "Medical Devices" from News Type instead of from Vacancy Branch).

### Additional info
- Craft version: Craft Pro 4.12.5
- PHP version: 8.2.23
- Database driver & version: MariaDB 10.6.19
- Plugins & versions: Feed Me | 5.8.0

**Comment by JaneConvergine** [comment]
Hello,

We're encountering the same critical bug and would appreciate a prompt resolution. 

When uploading data via Feedme, the plugin doesn't seem to respect the specified category group. Instead, it searches across all category groups and pulls in any entries with the same title.

Example:
The "Canada" tag appears in multiple groups:

- Tags
- Countries
- Country of Exploration

However, Feedme pulls all instances of "Canada" across these groups instead of isolating them to the designated group.

Craft version: Craft Pro 5.4.9
PHP version: 8.2.22
Database driver & version: MySQL 8.0.36
Plugins & versions: Feed Me | 6.5.0

**Comment by i-just** [comment]
Hi, thanks for reaching out. 

@Patchyy, can you please let me know if I got this right:
- You are importing an entry, and that entry has a Categories field, which has a Source set to “Vacancy Branch” (in Control Panel > Settings > Fields > <Categories field>).
- On the Feed Me mapping page for this feed, you are mapping the Categories field to the category title, and “Data provided for this category is:” is set to “Title”.
- When you run the import, the entry you just imported has the “Medical Devices” category in the Categories field, but it’s the “Medical Devices” from “News Type”, and it should be “Medical Devices” from “Vacancy Branch”?

**Comment by StanSteen** [comment]
Hi @i-just 

Thank you for your reply.
Yes this is all correct. We try to match "subsector titles" from mercury with "vacancyJobBranches" with the import and "data provided for this category is" set to "title". But for some reason this always matches with news type so in the entry the data is not set correctly

**Comment by bymayo** [comment]
I'm also experiencing this issue, where it also pulls in categories in to a field, that don't even belong in that category group

E.g.

I have 2 category groups 

Categories - Work
Categories - Industry

When i import in to a field called "Industry" it's pulling in categories from "Categories - Work", even though that field has got "Categories - Industry" set as the category group. But also it seems to be pulling in categories that don't even match/exist in my XML imports

**Comment by i-just** [comment]
Thanks for confirming! I raised a PR for this.

**Comment by angrybrad** [comment]
Feed Me 5.9.0 and 6.6.0 are out with this fix!

https://github.com/craftcms/feed-me/releases/tag/5.9.0
https://github.com/craftcms/feed-me/releases/tag/6.6.0
