### ISSUE TITLE
Add switch to section channel entries to exclude from feedme update

### ISSUE THREAD

**Issue by justcookin** [engram-design/FeedMe#154]
Is there a way to add a field to a section entry type like a lightswitch that would tell Feedme whether or not to update that entry? 

The use case is needing to make certain fields keep edits made to the entry in Craft and not overwrite these changes on subsequent Feedme imports.

**Comment by engram-design** [comment]
Not currently, but thats a great case for a feature request. This will likely come in the form of a config setting defining your field handle (that you yourself create as a lightswitch field).

Are you looking for this urgently?

**Comment by justcookin** [comment]
It would be a great feature to have right now, and save time from doing in a less elegant way. Would it be a big lift?

**Comment by engram-design** [comment]
I've added this to the [latest master](https://sgroup.com.au/plugins/feedme/download).

Create a Lightswitch field, similar to the below to opt-out of element updates. Assign it to the Entry or other element you're importing into.

![screen shot 2017-02-11 at 6 42 39 pm](https://cloud.githubusercontent.com/assets/1221575/22852127/e4fb0760-f089-11e6-9aed-5de3b9190a3b.png)

Take note of the field handle you create your field with. Then, add a configuration option (follow the guide [here](https://sgroup.com.au/plugins/feedme/getting-started/configuration), so be the following:

```
return array(
    '*' => array(
        'skipUpdateFieldHandle' => 'myLightswitchFieldHandle',
    ),
);

```

**Comment by justcookin** [comment]
Awesome! I will test this out and let you know how it goes. Thanks!

**Comment by engram-design** [comment]
Closed for the time being, as all working after tests.
