### ISSUE TITLE
Behaviour of Category Fields Beginning with "Not "

### ISSUE THREAD

**Issue by leighgibbo** [engram-design/FeedMe#1542]
### Description
I have discovered an issue with Category-matching, for certain values in nodes:

Passing an import node that contains a string with the word `Not ` at the start, causes incorrect category assignment to entries - even so far as assigning categories from completely different/unrelated groups.  This feels like the string is being parsed as a category query!?!

### Steps to reproduce

1. Create a new feed that will generate a standard Entry element type, which has a related Category field assigned to a Category Group
2. Ensure the feed has an incoming field which is mapped as the 'Title' of the related category (the category itself doesn't need to already exist).
4. In the feed itself (i.e. the JSON file being parsed), set the node that is used for the category title to a value like `Not Released` or `Not Applicable` etc.
5. Review the created/imported entries - on the current version of Feed-Me (`6.5.0`) and CraftCMS (`5.4.10.1`) the entries are incorrectly assigned the first category in the applicable category group, but while testing on older packages (Feed-Me `6.4.0` and CraftCMS `5.4.6`) I was seeing the entry being assigned categories from completely unrelated groups! 

### Additional info

- Craft version: 5.4.10.1
- PHP version: 8.2.8
- Database driver & version: MySQL 8.0.33
- Plugins & versions: Feed-Me 6.5.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

> even so far as assigning categories from completely different/unrelated groups

There’s a [separate issue](https://github.com/craftcms/feed-me/issues/1530) open for it, and a PR has been raised too.

**Comment by angrybrad** [comment]
Feed Me 6.6.0 is out with this fix! https://github.com/craftcms/feed-me/releases/tag/6.6.0
