### ISSUE TITLE
Updating a disabled entry in another locale automatically sets the status to enabled

### ISSUE THREAD

**Issue by patrickhefner** [engram-design/FeedMe#155]
When running an import to update an entry in a locale other than the default, all disabled entries are set to enabled even when "Don't Import" is selected for status.

**Comment by engram-design** [comment]
Are you on the [latest beta](https://sgroup.com.au/plugins/feedme/download)? Just tested quickly and seems to be working correctly, but happy to investigate further if you're already on the latest.

**Comment by patrickhefner** [comment]
I pulled the latest this morning and noticed the issue, just pulled again and retested, issue is resolved!

**Comment by engram-design** [comment]
Great, just let me know if you have any further issues!

**Comment by patrickhefner** [comment]
Will do, awesome work, this is truly a brilliant plugin!
