### ISSUE TITLE
When updating an entry that contains a matrix field that has an asset field, the entire matrix field is deleted

### ISSUE THREAD

**Issue by patrickhefner** [engram-design/FeedMe#158]
I am running an import on a section of entries for a locale other than the default. The import is set to update only and matching on existing element ID. I have also tried matching on the slug and see the same result.

All of the entries have a Matrix Field that contains an Asset Field. I have the Matrix Field set to "Do Not Import". When running the import, the Matrix Field is deleted from each entry. I ran a test where I removed the asset field from the Matrix Field before running the import. I then re-ran the same import and the Matrix Field was not deleted.

In addition, I am now seeing the issue again where all entries that have been updated are enabled for the locale, even if they were not enabled for that locale before running the import. I have the status set to "Do Not Import".

**Comment by engram-design** [comment]
I'll investigate the Matrix issue, as it acts differently to most other elements - compounded by Locales.

For the Locales, do you have Default Entry Status for the section set to disabled?

**Comment by patrickhefner** [comment]
Thank you for looking into the issue. I have default entry set to enabled for en_us and disabled for the other 5 locales. When running the import on any of the locales they are enabled regardless of their previous state. It's possible they are inheriting the en_us status.

The deletion of the Matrix Field only seems to happen when it contains an asset field.

**Comment by smcyr** [comment]
Hi, I had the same issue with Feedme 2 beta 2. It deleted matrix fields with asset field even if it was set to "Don't import". My entries are by default enabled in the 3 languages.

Thanks

**Comment by engram-design** [comment]
The Matrix/Asset issue should now be fixed in the [latest master](https://sgroup.com.au/plugins/feedme/download). The issue was element options (Assets, Entries, etc) were still being passed to Matrix, despite no data being present. This cause the Matrix field to think there was content to import.

The locale enabling issue has also been resolved. It previously forced a locale to be enabled, and will now simply leave as-is.

**Comment by patrickhefner** [comment]
I have confirmed this is Update is working perfectly after several rounds of imports, thank you for the update!
