### ISSUE TITLE
Mapping XML node attributes to field

### ISSUE THREAD

**Issue by oncode** [engram-design/FeedMe#16]
When I read a XML feed in a template, I can access a node attribute by:
`{{ xml.field.attributes.my_attribute }}`

Is it also possible to map a node attribute and not just a node to a destination field when I add a feed in the backend?

**Comment by engram-design** [comment]
Its not possible at the moment through the feed setup, but I'll add it to the roadmap. For the moment, you'll need to restructure your feed to put the values you wish to map inside node tags.

**Comment by oncode** [comment]
Unfortunately it's not my feed, but I think I'll just read it in the template. Thanks anyway for your awesome plugin!

**Comment by engram-design** [comment]
Ah, yeah if thats the case, you'll unfortunately have to build something in the middle that modifies the original feed. I've done this before for an ExpressionEngine site with Datagrab, as that doesn't support attribute mapping either. Will let you know when this has been added!

**Comment by BobD** [comment]
Hi there,

I love this plugin. I'm trying to achieve the same thing reading in some RSS feeds. What would be the easiest way to go about this besides altering the feed beforehand? Is there perhaps some even hook available firing after an entry is created so you can add the attribute feed afterwards? Or would you have to create entry from scratch?

**Comment by engram-design** [comment]
This has finally been added to Feed Me 2.
