### ISSUE TITLE
FR: Numbered select options for field mapping

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#162]
When running through field mapping for data where there's dozens of fields to choose from, it would be handy to have either numbered select items to make it easier to jump to (or near) a certain field with the keyboard. (Typing the first few letters using the native OS functionality currently isn't practical when everything starts with a <, and in my case, a section prefix, but there is a tradeoff there.)

Even better would be fuzzy search for each select, but I'm not sure what the performance implications would be of having potentially dozens of those fields on the mapping screen. :)

**Comment by engram-design** [comment]
Implemented in the [latest master](https://sgroup.com.au/plugins/feedme/download).
