### ISSUE TITLE
FR: Set entry assets' creation date on import

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#165]
When importing an entry which contains an asset field, I'd like to be able to set that asset's creation date to be the entry's publish date. Currently I'm just importing that date as a separate field for the asset, but it would be a bit cleaner to be able to set the asset creation date from import.

**Comment by engram-design** [comment]
I don't believe we're able to alter the `dateCreated` attribute on _any_ element, as thats strictly handled by Craft. For Assets, this would be the time of upload of that Asset, not the Entry associated with it.

I'll look into this, but I'm fairly certain its not going to be possible. A separate date field would be the way to go.

**Comment by engram-design** [comment]
Closing, this simply isn't possible with Craft (Craft overrides element creation/update times).
