### ISSUE TITLE
FR: Better copy around "Upload files from urls"

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#166]
This is a hard one, but I went through the source at one point trying to understand the difference between "Keep original", "Replace existing", and "Keep both" and still didn't quite get it. IIRC this is using Craft's native image handling, but (to me at least) it was a bit ambiguous if it was talking about files only, or existing assets, or what. 

I assume the meaning is more like...
In cases where filename already exists:
- Use destination file (imported file will be discarded).
- Use imported file (existing file will be replaced).
- Use renamed imported file (existing file will be left alone).

Is that correct? Hard to put into pithy UI copy though!

**Comment by engram-design** [comment]
Its actually the same text as the prompt you'd get from Craft if you tried to upload a file with the same name. On that basis, thought it would be clear enough.

If this filename matches an existing Asset:

- Use the existing Asset and ignore whats in this feed.
- Replace the existing Asset (overwrite) with the file in this feed.
- Upload the file in this feed, but rename (usually adds '-1' to the file). 

Does that make sense?

**Comment by ldstevens** [comment]
Yeah if it's a Craft convention then maybe clarifying in the docs is enough. But for me at least there was also a bit of ambiguity about files vs assets, probably because I'd be doing test runs over the same import/destination dirs, so whether a file (with or without an asset) existed was a factor in testing. 

In any case, yeah your language is much clearer. So maybe instead of:

[ ] Upload files from urls: [Keep original/Replace Existing/Keep both]

Something like...
[ ] Create asset from URL. If asset filename exists: [Use existing (skip import)/Replace existing (use import)/Create new (rename import)]

Would be enough? Hmm. 🤔

**Comment by ldstevens** [comment]
...err "If asset **with** filename exists:" would be better I think, to make it clear we're taking about assets-that-exist, not a misunderstanding of filename-of-asset-you-want-to-upload (i.e. file on disk vs asset in DB).

**Comment by engram-design** [comment]
Implemented in the [latest master](https://sgroup.com.au/plugins/feedme/download).
