### ISSUE TITLE
Feed mapping page times out when Craft DB has 10,000s of elements

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#168]
Ran into a weird bug (?) today, with the latest Feed Me master.

I've got my imports working, and have successfully imported ~20k entries with ~7k other elements. 

However, there was an issue with the field mapping of one feed, so I tried editing that feed. First screen loads fine, but hitting "Save and continue" to go to the field editing screen just hangs indefinitely, no matter how long I leave it (I think it would timeout if my PHP timeout limit wasn't so high :) ). I can also create a new feed, but again as soon as I hit "Save and continue" to go to field mapping, it hangs indefinitely. It's doing _something_ - the http process starts pegging the CPU pretty hard, and I have to restart Apache to end it, but it never resolves. 

If I delete all the entry elements (20k of them) straight out of craft_elements, Feed Me lets me get to the field mapping screen again straight away. Weird. :)

**Comment by ldstevens** [comment]
Just wanted to add that I can still run the import, regardless of how many entries are in the DB. My workaround is to have one DB with no entries to edit feeds, and one with entries to import them :)

**Comment by iparr** [comment]
I also have this problem.

PHP logs say iIt fails at:

`[23-Feb-2017 13:31:56 UTC] PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /home/vagrant/sites/5m-craft/app/craft/app/models/BaseModel.php on line 266`

This screen was achievable on the 1.4.12 version. I'm rolling back!

**Comment by engram-design** [comment]
This should be fixed in the [latest master](https://sgroup.com.au/plugins/feedme/download). The issue was when providing default parents for entries and categories, it tried to pull in all entries/categories with no limit. This was a bit of an unforeseen issue at the time, but its pretty crystal clear now in hindsight! 

For now, parent entry/categories are limited to 100. I'll look at re-implementing that in the future.

Let me know how that goes.

**Comment by iparr** [comment]
I'm afraid I still get that error.

**Comment by engram-design** [comment]
@iparr Have you cleared your caches via Settings > Clear Caches? Is the Section you're importing into a Channel or a Structure?

**Comment by iparr** [comment]
Well, that's embarrassing - I'm not really a plugin dev so did not consider that would have an impact. I was importing into a channel. 

Cache cleared and now everything seems to be working.

I've tried to purchase a [discounted license](https://sgroup.com.au/plugins/feedme/getting-started/pricing) but it's not clear how that works! Can you point me in the right direction as I am keen to show my support to this project - which has been very useful to my work.

**Comment by engram-design** [comment]
@iparr To be fair, I didn't think it would be an issue either! Glad thats working now. Even if you're importing into a channel, it shouldn't have memory issues anymore.

And the Pro version is free during the beta, and purchasing a license isn't available yet, but will be very soon once the plugin is out of beta. Thanks for your support!
