### ISSUE TITLE
Support for multiple categories

### ISSUE THREAD

**Issue by amityweb** [engram-design/FeedMe#17]
Does FeedMe support multiple categories? From looking at the code I can't see that it does. 
Thanks

**Comment by engram-design** [comment]
It certainly does, and your feed should provide them in the below format (for XML):

```
<Categories>
    <Category>First Category</Category>
    <Category>Second Category</Category>
</Categories>
```

**Comment by amityweb** [comment]
Yay! Brill, will try now.

**Comment by amityweb** [comment]
It works! Thanks.
