### ISSUE TITLE
Atom feed import chokes on emoji 💢

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#170]
I've got Feed Me successfully importing entries from an RSS feed, except for entries which contain emoji (in any field).

The error in the Feed Me logs is:
```
CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x99\x84' for column 'title' at row 1
```

However, trying to create an entry in Craft with emoji in the title throws the same error:

```
CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x99\x84' for column 'title' at row 1
```

So I guess it's a Craft thing. I'll lodge a bug there. I'm tempted to suggest imported fields could be sanitised to remove characters such as emoji, but OTOH once Craft supports it, it doesn't make sense to exclude them necessarily. Hm 🤔

Example atom feed attached. 
[phtech_20170224.xml.zip](https://github.com/engram-design/FeedMe/files/798554/phtech_20170224.xml.zip)

**Comment by ldstevens** [comment]
Looks like it's been reported (https://craftcms.uservoice.com/forums/285221-feature-requests/suggestions/16364995-title-should-accept-emojis) and Brad suggested it's a mysql config issue: https://mathiasbynens.be/notes/mysql-utf8mb4

I'll look into that instead 😅

**Comment by engram-design** [comment]
Actually came across this issue on a non-Feed Me related issue, so thats handy to know!

I think pre/post sanitization is something for the roadmap - I'd just rather not touch user feed data and force any sort of behaviour.

**Comment by ldstevens** [comment]
Yeah that's fair enough. Brad commented further here fwiw: http://craftcms.stackexchange.com/questions/17277/mysql-collation-utf8mb4-unicode-ci-emojis/17278 .

**Comment by nathanielperales** [comment]
Is there anyway you guys could implement this so it doesn't break feedme importing?

```
    if (Craft::$app->getDb()->getIsMysql()) {
        // Encode any 4-byte UTF-8 characters.
        $value = StringHelper::encodeMb4($value);
    }
```

https://github.com/selvinortiz/craft-plugin-doxter/issues/5

**Comment by engram-design** [comment]
@nathanielperales What field type are you importing into? I've tested with XML, Rich Text and Plain text, and is not throwing any errors?
