### ISSUE TITLE
Drop down field value not found breaks import

### ISSUE THREAD

**Issue by timeverts** [engram-design/FeedMe#171]
Hi,

I am running an import routine which has a drop down field in it.
My import data has 'WA' as the text value but the value of the drop down field in the CMS is actually 'wa'. Because of this, when I run the import, it breaks without explanation/logs and the task fails to get beyond the first step. So something in the ```DropdownFeedMeFieldType::prepFieldData()``` method is not quite right (perhaps that ```$preppedData``` is initialised as an array?)

How I got around the problem was to change the source code for the drop down field to match on the label if it can't find a value.

So the code becomes:
```
        // find matching option label
        foreach ($options as $option) {
            if ($data == $option['value']) {
                $preppedData = $option['value'];
                break;
            }
            else if ($data == $option['label']) {
                $preppedData = $option['value'];
                break;
            }
        }
```
This might be a worthwhile change you could implement. However, it solves the problem in my case because I have a 'WA' label that matches my textual import value of 'WA', so the bug no longer gets triggered. But this might not actually be the _real_ fix for the bug.

**Comment by engram-design** [comment]
To be fair, value matching should be case sensitive. What if you had several options (values) in your dropdown field for `WA`, `Wa`, `wA`, `wa`, you wouldn't want Feed Me to match against the incorrect one. I would suggest either changing the Dropdown value, or the value in your feed (if either is possible.

I'm hesitant to adding that code to match against the label, purely from a simplicity standpoint. In the unlikely case you have WA as the label for one option, and WA as the value for another, Feed Me doesn't know which one is the 'correct' option.

If anything, I think the solution would be to choose what your data is coming in as, something like the below:

![screen shot 2017-03-01 at 12 25 32 am](https://cloud.githubusercontent.com/assets/1221575/23406972/aeafd43a-fe15-11e6-9937-74350a8a2ca9.png)

**Comment by timeverts** [comment]
I see your point and agree that your proposed solution is much better.
Hope it gets into the next build.

**Comment by ugin** [comment]
I'm having a similar issue, had the following Dropdown (label | value):

```
Signed by the Author | signedByTheAuthor
Signed & Lined | signedLined
```

When the imported field had the value `unsigned` which was missing from the dropdown, the following error would be logged in `craft.log`, and the takes would get stale.

Stacktrace of the error:

```
...
2017/03/11 00:11:21 [info] [application] [Forced] Starting step 5 of 10 total steps.
2017/03/11 00:11:21 [info] [application] [Forced] Starting step 6 of 10 total steps.
2017/03/11 00:11:21 [info] [application] [Forced] Starting step 7 of 10 total steps.
2017/03/11 00:11:21 [info] [application] [Forced] Starting step 8 of 10 total steps.
2017/03/11 00:11:21 [error] [php] Array to string conversion (/PROJECT/craft/app/fieldtypes/OptionData.php:58)
Stack trace:
#0 /PROJECT/craft/app/fieldtypes/BaseFieldType.php(182): arrayToString()
#1 /PROJECT/craft/app/services/ContentService.php(403): Craft\DropdownFieldType->getSearchKeywords()
#2 /PROJECT/craft/app/services/ContentService.php(154): Craft\ContentService->_updateSearchIndexes()
#3 /PROJECT/craft/app/services/ElementsService.php(1416): Craft\ContentService->saveContent()
#4 /PROJECT/craft/plugins/commerce/services/Commerce_ProductsService.php(171): Craft\ElementsService->saveElement()
#5 /PROJECT/craft/plugins/feedme/FeedMe/ElementTypes/Commerce_ProductFeedMeElementType.php(164): Craft\Commerce_ProductsService->saveProduct()
#6 /PROJECT/craft/plugins/feedme/services/FeedMe_ProcessService.php(166): Craft\Commerce_ProductFeedMeElementType->save()
#7 /PROJECT/craft/plugins/feedme/tasks/FeedMeTask.php(68): Craft\FeedMe_ProcessService->processFeed()
#8 /PROJECT/craft/app/services/TasksService.php(239): Craft\FeedMeTask->runStep()
#9 /PROJECT/craft/app/services/TasksService.php(200): Craft\TasksService->runTask()
#10 /PROJECT/craft/app/controllers/TasksController.php(63): Craft\TasksService->runPendingTasks()
#11 /PROJECT/craft/app/framework/web/actions/CInlineAction.php(49): Craft\TasksController->actionRunPendingTasks()
#12 /PROJECT/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams()
#13 /PROJECT/craft/app/framework/web/CController.php(286): Craft\TasksController->runAction()
#14 /PROJECT/craft/app/framework/web/CController.php(265): Craft\TasksController->runActionWithFilters()
#15 /PROJECT/craft/app/framework/web/CWebApplication.php(282): Craft\TasksController->run()
#16 /PROJECT/craft/app/etc/web/WebApp.php(817): Craft\WebApp->runController()
#17 /PROJECT/craft/app/etc/web/WebApp.php(287): Craft\WebApp->_processActionRequest()
#18 /PROJECT/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#19 /PROJECT/craft/app/index.php(62): Craft\WebApp->run()
#20 /PROJECT/craft/index.php(8): require_once()
REQUEST_URI=/index.php?p=manager/actions/tasks/runPendingTasks
2017/03/11 00:11:21 [error] [application] Encountered an error running task 156 (FeedMe), step 8 of 10: Array to string conversion on line 58 of /PROJECT/craft/app/fieldtypes/OptionData.php
```

**Comment by engram-design** [comment]
@ugin This should be fixed in the [latest master](https://sgroup.com.au/plugins/feedme/download).
