### ISSUE TITLE
Template error in ClientEdition

### ISSUE THREAD

**Issue by ryansnowden** [engram-design/FeedMe#177]
In the file feedme/templates/_includes/elements/entry/map.html you check the client edition line 11:

> {% if CraftEdition >= CraftClient %}
>    {% for user in craft.users.can('createEntries:' ~ sectionId) %}
>        {% set users = users | merge([{ label: user, value: user.id }]) %}
>    {% endfor %}
> {% endif %}

However it throws an error 

> Impossible to invoke a method ("can") on a null variable

What are you trying to do there exactly? Just make sure the admin is the owner?

**Comment by engram-design** [comment]
It creates a variable of users that are allowed to create entries in the selected section and entry type. This variable is then used for the default Author dropdown field. I've fixed this issue in the [latest version](https://sgroup.com.au/plugins/feedme/download).

**Comment by ryansnowden** [comment]
Superb 👍 The most amazing plugin on Craft by far :-)
