### ISSUE TITLE
Add support for Craft Commerce Digital Products

### ISSUE THREAD

**Issue by robbsnell** [engram-design/FeedMe#181]
This plugin already supports Craft Commerce Products which are far more complex than their Digital Products extension.

**Comment by engram-design** [comment]
I'll consider how to handle this. Technically, its a third-party plugin, which at the moment should implement required functionality themselves.

**Comment by robbsnell** [comment]
This is an extension provided the P&T guys. It's not packaged with Craft Commerce because it's a very specific use case, but I don't think it's really a third-party plugin.

**Comment by robbsnell** [comment]
Hi Josh
I'd be happy to write this extension myself.
I can see your pattern there, though it would handy if you confirmed a bullet list of the files you'd expect to see to add digital products.
Also, when handling an asset field as part of an entry import. If I already have all my files uploaded in the appropriate S3 bucket (configured as the asset source) then I should be able to simply provide the asset file name for the import and all the necessary associations are created, is that correct?
Thanks
Robb

**Comment by engram-design** [comment]
You're most welcome to have a go at writing the integration yourself. I'd recommend creating a 'helper', which will be how to support third-party fields and element-types. These are in a separate repository - https://github.com/engram-design/FeedMe-Helpers. Have a look at the Solspace Calendar helper which will give you an idea on what you need to support.

I stand by my conviction that its a third-party plugin, despite it being developed by the Craft developers. Lets put it in a helper for the moment, and if things start to get to 'integrated', it can be easily moved into the core Feed Me plugin.

**Comment by robbsnell** [comment]
Great, thanks, a helper sounds like a good solution. I'll take a look.

Any probs on my question about asset imports? 
I've got 12500 digital products that are about 1.5MB each so wanted to make sure I could upload the files to S3 separate to the product import.

**Comment by engram-design** [comment]
Sorry, realised I didn't answer your question. Thats correct - simply supply the filename for the asset, and it should link things up. Thats probably going to be quicker than uploading files at the same time as the import (by selecting upload).

**Comment by engram-design** [comment]
Closing, thanks for your help @robbsnell https://github.com/engram-design/FeedMe-Helpers/pull/1
