### ISSUE TITLE
A few things that stop an import

### ISSUE THREAD

**Issue by ugin** [engram-design/FeedMe#184]
`numberOfEditions` is a Number field, when the value was `-1` the code logged:

```
2017/03/12 23:19:56 [error] [plugin] [Forced] Books lists: {"numberOfEditions":["Number of editions is too small (minimum is 0)."]}
```

`bookImages` was an Asset field, when the import value was an array containing 2 identical URLs the task would get stale.

```
"bookImages": [
  "https://domain.com/path/to/image_1.jpg",
  "https://domain.com/path/to/image_1.jpg"
] 
```

**Comment by engram-design** [comment]
What version of Feed Me are you on? No validation errors come up for the Number field with a minimum value set. Can you confirm if you were uploading these URLs into your Asset field?

**Comment by ugin** [comment]
version 2.0.1 (Pro)

On the Number field, was a minimum value set to "0".
For the Asset field I use: "Upload files from urls (replace existing)"

**Comment by engram-design** [comment]
And when you mention `stop an import`, how are you running the feed - using Run Feed, or using the direct link? Errors like these are supposed to show at the end of feed processing, and shouldn't stop an import from running mid-import. I'll try to replicate again.

**Comment by ugin** [comment]
I run imports using "Run Feed".

I've just ran a 200 product import and the task gets stale:

```
[20-Mar-2017 12:41:47 UTC] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 1462272 bytes) in /../craft/app/vendor/lsolesen/pel/src/PelJpeg.php on line 584
```

I've allocated more memory and I get the same error, current memory `memory_limit => 1024M => 1024M`.

Below is an example product item. I'm under NDA can't share the exact image / URL, it's a 1.5mb image.

```
{
  "status": "publish",
  "id": "42715",
  "title": "Dodger",
  "bookAuthor": "Terry Pratchett",
  "bookCategories": [
    "Childrens & YA"
  ],
  "bookDescription": "...",
  "bookEditionType": [],
  "bookNumberOfEditions": 0,
  "bookFeatures": [],
  "bookFormat": "hardcover",
  "bookImages": [
    "https://UNDERNDA/wp-content/uploads/2017/02/IMG_6967.jpg"
  ],
  "isBookRecommended": false,
  "bookIsbn": "9780385619271",
  "bookPrintingType": "ukFirstEditionFirstPrinting",
  "bookPublicationDate": "Thu, 13 Sep 2012 03:00:00 +0300",
  "bookPublisher": "Doubleday",
  "bookSignatureType": "unsigned",
  "bookTags": [
    "Fantasy"
  ],
  "bookOfTheMonthDate": "",
  "bookOfTheMonthDescription": "",
  "isBookOfTheMonth": false,
  "bookRareDescription": "",
  "permalink": "https://UNDERNDA/product/dodger-2/",
  "price": "25",
  "regularPrice": "25",
  "stock": 1,
  "gallery": "",
  "createdAt": "1424100303",
  "productImageGallery": "",
  "featured": "no",
  "slug": "dodger-2",
  "availabilityDatetime": "",
  "whenToCharge": "",
  "postDate": "Mon, 16 Feb 2015 17:25:03 +0200",
  "sku": "WS7XMMHA",
  "isEnabled": true,
  "bookAuthors": [
    "Terry Pratchett"
  ]
}
```

**Comment by engram-design** [comment]
Have you looked at the [Performance FAQ](https://sgroup.com.au/plugins/feedme/support/troubleshooting#performance)?

Having said that, I've never seen the reference to `/../craft/app/vendor/lsolesen/pel/src/PelJpeg.php`, so thats new. Have you tried this import with your image field un-mapped?

**Comment by ugin** [comment]
😆 sorry, I removed sensitive data from the path -> `/../craft/app/vendor/lsolesen/pel/src/PelJpeg.php`.

If I remove the image URL from `bookImages`, it imports the product.

**Comment by engram-design** [comment]
I just meant if you select "Don't Import" for the Asset field you're importing `bookImages` into - and it sounds like thats the issue. Images are actually downloaded without loading them into memory first, so it shouldn't raise errors.

I bit tricky to debug without seeing your environment and data, but understand thats under a NDA. I'll see if I can come up with anything after some more testing.

**Comment by ugin** [comment]
I think is a memory related issue.

When I try to import a 200 product list, the import task gets stale at item number 126. I ran the same task 4 times and it gets stuck importing item 126. If I remove the first 125 products, the tasks finishes without problems.

So is not a FeedMe issue, what I don't know is how the image import works, maybe it loads all the images in memory and doesn't free it, somehow. The images I have imported are ~2mb.

**Comment by engram-design** [comment]
Its Feed Me that does the image importing from a remote url, so I believe it still might be a Feed Me issue. I can do some further testing to identify memory leaks, but for the time-being, if you can limit your items to 100-125 that might work in the interim.
