### ISSUE TITLE
Importing assets into a specific directory.

### ISSUE THREAD

**Issue by subrato** [engram-design/FeedMe#185]
Hi,
I have parent folder and many sub-folders and I need to preserve the folder structure while importing. I was testing it with a sample json file I created and from the looks of it I can only upload it in the parent folder. Is it possible to take the path that I provide, locate the directory and then put the file there?

**Comment by howells** [comment]
Chiming in here: could you not specify a default location of the file within the asset field itself? That's what I do and it seems to work well

![screen shot 2017-03-27 at 13 05 10](https://cloud.githubusercontent.com/assets/145849/24355499/0c897e8e-12ee-11e7-9943-616df58918e5.png)

**Comment by engram-design** [comment]
@subrato I'll provide a dropdown on the first screen to select a specific folder to upload into. Where this gets tricky is if you want to dynamically generate the folder, based on the element you're importing (say a folder named the slug of the entry). In this instance, you'd follow @howells and his advise to use the `Default Upload Location` field setting.

**Comment by subratom** [comment]
@howells The issue I have is I have one main folder under which I have subfolders followed by another level of folders. In total I am looking at creating 200+ folders & then asset fields. I didn't want to do that. So I added the top level folder and let CraftCMS index it.

@engram-design I am not creating new folders on the fly. I already have all the folders I need, I just need to add new files that are still in our existing CMS to CraftCMS. Because the size of the top folder is now at 18 GB, indexing through CraftCMS takes about 3-4 days.

**Comment by engram-design** [comment]
To just to clarify on your original issue @subrato `Is it possible to take the path that I provide, locate the directory and then put the file there?`

How will it locate the directory? Say you have the following URL that you're mapping to an Assets field - `http://mywebsite.com/path/to/asset/image.jpg`. Are you expecting Feed Me to look at this image, and download it into `/path/to/asset/` on your Craft install?

**Comment by subrato** [comment]
@engram-design No I can provide the complete path to where it belongs inside the sub-directory so on first screen I select the top-level folder and then for each asset there will be a complete path and then another field as filename. Does that make sense?

**Comment by engram-design** [comment]
@subrato Can you share you feed, or at least the structure or what data you've got to make work? Do you mean something like:
```
<Asset>
  <Path>/path/to/asset/</Path>
  <Filename>image.jpg</Filename>
</Asset>
```

**Comment by outline4** [comment]
Would love to see that possible! Any progress on this?

**Comment by engram-design** [comment]
@outline4 The plan is to still have the folder as a selection on the first screen when setting up your feed. Is this what you're after? This is strictly when importing Assets - not when importing Entries with Asset fields. If you are doing this, you can use the dynamic directory setting for the Asset field.

**Comment by marksimons** [comment]
@engram-design Hi Josh, did this folder selection get implemented? I have an asset field and its only giving me the map to field option and not to a folder drop down.

![screen shot 2019-01-29 at 14 24 29](https://user-images.githubusercontent.com/519951/51914839-a1ba7800-23d1-11e9-85f1-d5462ccd000c.png)

Thanks

**Comment by marksimons** [comment]
Actually, I see this is for Element Type > Asset. My case is slightly different. I am importing entries  from oldsite-a.com and would like to put them in the volume /images/oldsitea/general

**Comment by engram-design** [comment]
There's no option to specify the folder you want when its an asset field. The recommended way to handle this would be to set this in your Asset field settings. Either restrict assets to be a particular folder, or use the dynamic folder name options to get a similar result.
