### ISSUE TITLE
License error: missing_required_data

### ISSUE THREAD

**Issue by efedorenko** [engram-design/FeedMe#186]
Hi there,

I just installed the latest version of the plugin and tried to import an XML feed but it failed with a "License error: missing_required_data" error in logs.

Craft's own logs have only one error related to the accident: "Encountered an error running task 132 (FeedMe), step 1 of 1: strtotime() expects parameter 1 to be string, array given on line 654 of /var/www/craft/app/helpers/DateTimeHelper.php"

I tried it both on a development machine and a live server, got the same error.

Any idea what that can be and how can it be fixed?

**Comment by engram-design** [comment]
Have you entered a license key, or just running the free version? Are you importing entries or another element type? If you're just importing entries, you can ignore the error.

**Comment by efedorenko** [comment]
I'm running the free version. I created a new entry type and trying to import entries from GoodReads' API into it.

**Comment by engram-design** [comment]
Are you also on the latest 2.0.1 release? https://sgroup.com.au/plugins/feedme/download

**Comment by efedorenko** [comment]
Yep!

On Field Mapping step I see correct examples from my feed, so I guess it can be reached and parsed just fine. But when I finish setting it up and trying to import it fails.

**Comment by efedorenko** [comment]
I cleared everything, restored from backup, and now it actually works ¯\_(ツ)_/¯

Thanks for taking time to look into it!

**Comment by engram-design** [comment]
Hmmm, a little odd, as there's no real license-checking as part of the feed processing (unless you trying to import anything other than entries). But, glad its working! Just let me know if it plays up again and can look into it further.

**Comment by nicolasbottari** [comment]
I have this issue as well. Using FeedMe 2.0.1 (free) on a local Craft install (Craft CMS 2.6.2961). Clearing EE cache and making sure all tasks (including failed FeedMe tasks) are cleared before I try the import again, but I still get the `License error: missing_required_data` error. The license information is of course empty.

**Comment by nicolasbottari** [comment]
Was also using a path to an XML file on my (local) server for the import. Also now discovered that the **Direct Feed Link** URL worked and I was able to complete the import (update in this case). This wasn't working with importing from the CP however.

**Comment by efedorenko** [comment]
@nicolasbottari, I feel like not an obvious thing that helped me resolve was specifying a correct Primary Element ¯\_(ツ)_/¯

**Comment by engram-design** [comment]
@nicolasbottari This should be resolved as of the [latest version](https://sgroup.com.au/plugins/feedme/download). 

However, I don't believe this will stop and feed processing you're doing - it'll simply log that an error occurred with your feed, which is incorrect, as its a licensing issue. It should also be pretty infrequent, as its whenever the server is pinged for the license status.

In any case, please try the latest version to see how that goes.
