### ISSUE TITLE
"Unable to parse feed URL" error with Wordpress ATOM feed

### ISSUE THREAD

**Issue by tyssen** [engram-design/FeedMe#19]
I'm trying to import a Wordpress ATOM feed and getting the above error when I do. 

Validating the feed says it's valid but there are a few recommendations about not allowing scripts or iframes in content and about the subtitle not being blank.

Would those prevent the plugin from importing the content?

**Comment by engram-design** [comment]
That error usually points to an issue either accessing the feed URL, or the feed itself. Is the feed something thats public? If not, get in touch with me via Slack, or use the Help widget in Feed Me and I can assist!

**Comment by engram-design** [comment]
Closing for now. Please let me know if you need this reopened.
