### ISSUE TITLE
Email address in image URL querystring causes filetype not allowed

### ISSUE THREAD

**Issue by ryansnowden** [engram-design/FeedMe#191]
If I have a URL:

http://carsales.li.csnstatic.com/nwm/car/dealer/194945985.jpg?width=1280&cid=5049&un=support%40mydomain.com&expires=20170404003321&key=123123

my **extension** is recognised as  com&expires=20170404003321&key=123123

**Comment by ryansnowden** [comment]
Actually this is mis-titled, it has to do with Curl and saving and filenames. We need to strip the QueryString from the URL but keep the original with the QueryString for CURL to get it because un my case I need to authenticate it.

So I

$originalUrl = $url;

then further down

$curlUrl = str_replace(' ', '%20', $originalUrl);

and then

CURLOPT_URL => $originalUrl,

Then it works for me. 

Might need to adjust for that!

**Comment by engram-design** [comment]
Ah yes, that makes sense. There's actually a `cleanAssetUrls` config option, but thats not quite right for this case, as it strips out query string content _before_ the request is made.

In fact, I'ev altered this behaviour to be on by default, but in addition, only cleanup the URL after the remote image has been fetched. Give the [latest version](https://sgroup.com.au/plugins/feedme/download) a go with this implemented.

**Comment by ryansnowden** [comment]
In my case as well, the script on the other end has a missing image, so it has been marked differently:

http://carsales.li.csnstatic.com/nwm?width=1280&cid=5049&un=support%40gdomain.com&expires=20170405003335&key=1234

Where it's actually returning a missing image/jpg in the browser. The asset import will fail if this is the case.

**Comment by engram-design** [comment]
I've made further improvements to this in the [latest version](https://sgroup.com.au/plugins/feedme/download). Now, it'll check if the URL you've provided has a filename or extension, and if not, will generate one for you. Otherwise, you'll have lots of images all called `nwm`, which isn't ideal.

**Comment by engram-design** [comment]
Closing for now, I believe we fixed this (correct me If I'm wrong!)
