### ISSUE TITLE
Undefined index error when selecting unique identifier

### ISSUE THREAD

**Issue by jesouhaite08** [engram-design/FeedMe#193]
I get an _Undefined index: appAndroidPackage error_ when selecting a unique identified for existing elements (aside from title).

The appAndroidPackage handle is a valid field that I am using.

<img width="1094" alt="screen shot 2017-04-01 at 1 12 39 pm" src="https://cloud.githubusercontent.com/assets/7729839/24583625/bc9241ec-171e-11e7-8efe-4f9128a8bd64.png">

**Comment by engram-design** [comment]
Hi @jesouhaite08 Just wanted to follow this up (tried through Slack). If you can send through a Help request through Feed Me, that'd help. Failing that, maybe an export of your `craft_feedme_feeds` table.

If you're able to share your feed (even privately if its sensitive data), that'd help too.

**Comment by siebird** [comment]
I just had a similar issue and it was due to myself. I was trying to update entries using `Title` as the unique identifier w/o setting the `title` field on import. I just banged my head around for 2 hours trying to figure out why the import kept failing.

**Comment by engram-design** [comment]
This should be greatly improved in the [latest master](https://sgroup.com.au/plugins/feedme/download), a log error will appear if you're trying to use a unique identifier with no data present. Processing will also skip over the element you're trying to add/update, as its unable to check if an existing element is present. This is important to ensure the incorrect element isn't updated, or duplicates aren't created.

As such, the unique identifier is a required field, as it always has been.
