### ISSUE TITLE
Fatal error: Class 'Craft\FeedMe_FeedModel' not found in app/craft/app/helpers/ModelHelper.php

### ISSUE THREAD

**Issue by kblizeck** [engram-design/FeedMe#194]
I am manually updating my Craft install from 2.6.2916 to 2.6.2968. I uploaded the new `app` folder from the Craft download and I am receiving the following error : 
`Fatal error: Class 'Craft\FeedMe_FeedModel' not found in app/craft/app/helpers/ModelHelper.php`

I do not have FeedMe installed, and never have had that plugin installed.

What could be causing this error?

**Comment by kblizeck** [comment]
Solved: Stalled tasks in the database from 2015... Cleared those out and the dashboard loaded without the error.

**Comment by kblizeck** [comment]
Nevermind! Deleting the stalled tasks didn't fix this. Refreshed the Dashboard and the error appears still, and there are no FeedMe tasks in `craft_tasks` table

**Comment by engram-design** [comment]
Thats quite bizarre, you must have installed Feed Me at some point? Can you check if there is a `craft_feedme_feeds` table in your database? 

Can you check your `craft_plugins` table and see if there is a row for Feed Me? If there is, you can delete it - essentially uninstalling the plugin. This can happen if you installed it on a previous version of your Craft site, deleted the actual plugin files, but the plugin is still listed as installed in the database.

**Comment by engram-design** [comment]
Any further news on this one? More than happy to assist via Slack if that helps?

**Comment by kblizeck** [comment]
Looks like FeedMe was installed at some point! Had to delete the `craft/storage` folder, clear the `craft_tasks` table and then refresh the site. 

When I first cleared the `craft_tasks` table, the `craft/storage` folder just repopulated it, so had to make sure that was deleted first.

Thanks for checking back in!!

**Comment by engram-design** [comment]
No problem, glad you got it sorted in the end!
