### ISSUE TITLE
Check if asset exists

### ISSUE THREAD

**Issue by ryansnowden** [engram-design/FeedMe#195]
Is there a way I can check if an asset exists (db or file?) and if it does, have the option to skip it? I have 2 gigs of files which otherwise get downloaded which I'm trying to void if the file already exists.

**Comment by engram-design** [comment]
Currently, if you select `Upload files from urls`, there's no checking for existing assets, which indeed does cause some issues.

Fortunately, the [latest master](https://sgroup.com.au/plugins/feedme/download) greatly improves this, and checks for the same asset (with the same filename in the folder its destined for) before trying to upload it. Just ensure you pick `Keep original`, and you should be good to go.
