### ISSUE TITLE
Backups location & logging

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#197]
Whereabouts are backups generated by Feed Me stored? I have a sneaking suspicion my test setup isn't creating them :)

If it would be possible to have database creation/failure logged in feedme.log that'd be great!

**Comment by engram-design** [comment]
They _should_ be stored in the same location as Craft's main backups - https://craftcms.com/support/logs-and-backups#database-backups

**Comment by ldstevens** [comment]
Ah, I'm guessing Craft doesn't create `craft/storage/backups/` until it needs to. I was running a clean install, hadn't upgraded, and the dir wasn't there, so no backups at all (not a big deal as just a dev site).

**Comment by engram-design** [comment]
No, I believe it should create the directory - underneath, Feed Me uses Craft's 'regular' backup API, so should act pretty normal. Regardless, I'll test it out, and likely add those events logged just for kicks.

**Comment by engram-design** [comment]
Added to the [latest master](https://sgroup.com.au/plugins/feedme/download).
