### ISSUE TITLE
Better asset error logging

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#198]
Speaking of logs, with the new hash check, Feed Me generates errors like:

> 2017/04/13 01:41:29 [error] [plugin] [Forced] Asset error: http://www.domain.com/path/toimages/ - The file “d20a3d5f6eaa679f8e49511edee6db82.jpg” does not appear to be an image.

It'd be great if there was some indication of the original URL in the log too, so the user can track down the bad source image. ✌️

**Comment by engram-design** [comment]
In that example - `http://www.domain.com/path/toimages/` should be the original URL?

**Comment by ldstevens** [comment]
Yeah I'm only getting the path - no filename.

**Comment by engram-design** [comment]
Weird, as its certainly doing that for me with two different type of uploading - with a filename, and without one.
```
2017/04/13 07:50:24 [error] [plugin] [Forced] Asset error: http://feedme.craft.dev/fake-img.jpg - The file “fake-img.jpg” does not appear to be an image.
...and...
2017/04/13 07:50:25 [error] [plugin] [Forced] Asset error: http://feedme.craft.dev/index.php/actions/businessLogic/getFakeImage - The file “b7884e5080bcc6faf270a7d689d3e95c.jpg” does not appear to be an image.
```

**Comment by engram-design** [comment]
Just chasing this up now that the 'major issue' with assets not matching correctly is fixed - can you shed any more light on this?

**Comment by ldstevens** [comment]
Not seeing the hashed filename in the logs any more, so let's close this one.
