### ISSUE TITLE
CSRF Protection

### ISSUE THREAD

**Issue by billythekid** [engram-design/FeedMe#2]
If a site has CSRF Protection enabled the form submissions always fail validation. Adding...
`{{ getCsrfInput() }}`
within the form tags in the form template files (_edit and _map in my testing - but any other forms I've not come across yet will need this too) is the fix.

eg. (in _edit.html - line 20 on)
```twig
{% block content %}
	<form method="post" accept-charset="UTF-8" data-saveshortcut="1">
		<input type="hidden" name="action" value="">
		{{ getCsrfInput() }}

		{% if feed.id %}<input type="hidden" name="feedId" value="{{ feed.id }}">{% endif %}
...
```

**Comment by engram-design** [comment]
Thanks for reporting this - fixed in the latest commit.
