### ISSUE TITLE
Matrix field not adding assets

### ISSUE THREAD

**Issue by Floriskoch** [engram-design/FeedMe#200]
I'm trying to import data to a Matrix field with the following structure but no data is added to the matrix field. In the feed map screen it actually shows the photo field as `<obj/img/.../photo[]>`, so the system seems to recognize the fields but each time the import fails without any reason. Other times there's no error but still no data is added to the matrix field.

`{
    "listing": [
    {
      "title": "title",
      "firstName": "first name",
      "lastName": "last name",
      "coverImage": "http://www.url.com/image.jpg",
      "objects": {
        "img": [
          {
            "photo": [
              "http://www.url.com/image.jpg"
            ]
          },
          {
            "photo": [
              "http://www.url.com/image.jpg"
            ]
          },
          {
            "photo": [
              "http://www.url.com/image.jpg"
            ]
          }
        ]
      }
    }
  ]
}`

I've tried everything but nothing seems to be working. Is this a bug or am I doing something wrong?

**Comment by engram-design** [comment]
Are you setting the Asset field to upload a remote image? There were some issues with Matrix/Asset and this combination, but is fixed in the [latest master](https://sgroup.com.au/plugins/feedme/download). If you wouldn't mind, would you be able to give that a go?

**Comment by Floriskoch** [comment]
It's working now, thanks for fixing it!
