### ISSUE TITLE
Asset filename & asset fields

### ISSUE THREAD

**Issue by ryansnowden** [engram-design/FeedMe#201]
When importing an asset element type, what should the filename be? I'm trying to import from a URL and it's an image so download and keep existing. If I do it via entry, it'll just grab it from the JSON array and extract the filename.

Also, it seems when importing to an Entry into an asset field with it's own additional field, as in I added a textfield to an asset, match it up in the mapping, it is blank on import. The same field exists in the element, but I'm trying to keep some redundancy in my assets by having a unique identifier common with the entry being imported.

**Comment by engram-design** [comment]
The filename needs to be your asset you want to import into Craft. Entry's (and other elements) are different in that they're a collection of content fields, whereas an Asset is an image, with a collection of content fields.

I imagine you'd have a feed such as:
```
[
  {
    "image": "http://url.to/my-image.jpg"
  }
]
```
Or better yet, send through your feed (or just the structure).

**Comment by ryansnowden** [comment]
My feed is huge but the relevant part looks like this. There are multiple assets to import, ideally into a folder /{stocknumber}.

```
[
  {
    "StockNumber": "141844",
    "Photos": [
      "http://carsales.li.csnstatic.com/nwm/car/dealer/97681979.jpg?width=1280&cid=5049&un=support%40glideagency.com&expires=20170422073321&key=0WgvJE6qm8W09rBLzmPioCqvUdfWcQ5KzKiIQFTXlnA_",
      "http://carsales.li.csnstatic.com/nwm/car/dealer/97681982.jpg?width=1280&cid=5049&un=support%40glideagency.com&expires=20170422073321&key=qyjT493szLSBZFJjKNZb5dCUB78Sk4RrS8yP7L-4jVk_",
      "http://carsales.li.csnstatic.com/nwm/car/dealer/97681981.jpg?width=1280&cid=5049&un=support%40glideagency.com&expires=20170422073321&key=2Rsj4JD8sJOIjIjkwMGzaeIbLeTqIxzJciTSc8ji7F0_",
    ]
},
... repeat 2000 times
]
```

**Comment by engram-design** [comment]
Thats a bit of a tricky one, as your feed needs to ideally be structured like:
```
[
  {
    "StockNumber": "141844",
    "Photo": "http://carsales.li.csnstatic.com/nwm/car/dealer/97681979.jpg?width=1280&cid=5049&un=support%40glideagency.com&expires=20170422073321&key=0WgvJE6qm8W09rBLzmPioCqvUdfWcQ5KzKiIQFTXlnA_"
  }, {
    "StockNumber": "141844",
    "Photo": "http://carsales.li.csnstatic.com/nwm/car/dealer/97681982.jpg?width=1280&cid=5049&un=support%40glideagency.com&expires=20170422073321&key=qyjT493szLSBZFJjKNZb5dCUB78Sk4RrS8yP7L-4jVk_"
  }, {
    "StockNumber": "141844",
    "Photo": "http://carsales.li.csnstatic.com/nwm/car/dealer/97681981.jpg?width=1280&cid=5049&un=support%40glideagency.com&expires=20170422073321&key=2Rsj4JD8sJOIjIjkwMGzaeIbLeTqIxzJciTSc8ji7F0_"
  }
]
```

This is because Feed Me expects a single asset per node, as multi-upload isn't really supported (at this stage). Is there any chance you can change the feed structure to match?

**Comment by ryansnowden** [comment]
Hmm, yah. I'd have to write a script to format it I guess. 

The reason I'm trying to import to an asset directly is by adding it through an Entry, the task fails getting the images (sometimes the URL stalls because the API is creating a transform) or runs out of memory just due to the volume. The task ends up stalling, blocking everything else.... so looking for a simpler method. Over all there are ~2000 steps, each with about 2-20 images each.

Anyway, cheers. I'll keep trying.

**Comment by engram-design** [comment]
Are you on the latest version by the way? I made a commit a few days back regarding changing how assets are handled when uploading from a URL (will be rolled into a 2.0.3 release soon). Previously, there was no check for an existing asset when uploading via a URL. If you have 'Keep Existing' selected, it'll check for an asset with that same filename, before trying to download the image.

So theoretically, if you get through 100 images on the first round, it'll skip over those next round.

Anyway, apologies that's all not more helpful!

**Comment by ryansnowden** [comment]
I just checked, I did update to the latest from 2 days ago but previously I raised the issue of checking if the asset filename exists :-) It fails on that too. Still trying to pinpoint whats going on, very frustrating.

**Comment by engram-design** [comment]
I'm guessing we're talking about https://github.com/engram-design/FeedMe/issues/191 - is that still not working correctly? I'll try and get to the bottom of it...

**Comment by ryansnowden** [comment]
Oh - no it is working. It runs through faster than the first pass and matches the files. The problem is that it still fails - sometimes on the very last step. I'm still trying to debug it. I can give you the json file but via email.

**Comment by engram-design** [comment]
Sure thing - nothing In the logs I imagine? Feel free to send to web at sgroup.com.au if you can!

**Comment by ryansnowden** [comment]
Ok sent. The errors I get vary from out of memory (but I have it set to unlimited), assets not being downloaded but the URL exists (but that shouldn't fail the task), some user permission errors but not sure if it's related. I got a few imports going on a clean data set so trying to get something a bit more specific. I did notice HTMLPurifier was being run on richtext fields causing the memory to be used up, so I changed to plain text and got further in. The data import (non asset) works 99% of the time, it's the asset import that fails 80% of the time.

**Comment by engram-design** [comment]
Hmm, haven't received the email yet - feel free to get in touch via Slack maybe? Thats interesting you point out HTMLPurifier and Rich Text fields, I'd not noticed that before.

**Comment by ryansnowden** [comment]
It would seem that something is switching my PHP max_execution_time to 30 seconds even though it starts out at 0, it suddenly switches to 30. Then it times out after a period because it is not long enough.

In ProcessFeed() I have

```
error_log('max_execution_time is: '. ini_get('max_execution_time'));
$iniPath = php_ini_loaded_file();
error_log('iniPath: ' . $iniPath);
```

and it gives me:

```
[15-Apr-2017 15:27:48 UTC] max_execution_time is: 30
[15-Apr-2017 15:27:48 UTC] iniPath: /opt/cpanel/ea-php70/root/etc/php.ini
```

So frustrating....

**Comment by engram-design** [comment]
I feel like someone pin-pointed that `max_execution_time`, but I need to dig through things to find what that was about. It sounds familiar though. I wouldn't have though transforms would kick in until a template route has been triggered? Feed Me isn't doing anything special other than what a regular upload image function would do.

Anyway, I'll test out your setup soon to see how far we get. I'll also try the `max_execution_time` stuff, as thats not a test I'd done yet (I would expect it to stay when set!).

**Comment by ryansnowden** [comment]
I think when saving it just gets it's dimensions width, height in craft_assetfiles and using GD will slow it down, Imagick less so. @set_time_limit will always override (maybe) the default max_execution_time unless maybe it's not set in disable_functions.

Each step was averaging about 1-22 seconds, so when it goes in and gets image meta and maybe the CURL takes a while, and being overwritten top be 30 seconds, it's likely to fail. Bit of a bug in Craft when dealing with image assets I think... maybe?

**Comment by ryansnowden** [comment]
I submitted it to P&T and Brad has patched it in the latest update.

"Fixed a bug where Craft would set a hard-coded PHP time limit of 30 seconds when uploading some types of images."

Looks like "HTML Purifier Config" is in there too.

**Comment by ldstevens** [comment]
Glad they removed that limit. I ran into the same thing a few weeks ago, where I was hitting both the hard-coded max execution time, and hard-coded memory limit too (which you can set in config.php). Drove me mental trying to figure out why php.ini settings weren't being respected. I documented it in Slack (& not here, which was dumb) and it's now lost in the depths of Slack somewhere, but glad P&T have sorted it.

**Comment by engram-design** [comment]
Agreed! Thanks @takobell. Closing for now.
