### ISSUE TITLE
Can't access node attributes

### ISSUE THREAD

**Issue by LucaDelBuono** [engram-design/FeedMe#203]
I have an XML feed with attributes on the node elements but can't find a way to access them.

This feature used to work in 2.0.0 beta 1.

Can this be looked into please?

Thanks.

**Comment by engram-design** [comment]
Are you able to provide an example of your feed data? I need some sort of indication on the data that you're trying to map.

Can you also clarify if you are trying to map the node attributes via the control panel, or access them directly via the templates?

**Comment by LucaDelBuono** [comment]
Yeah sorry, I'm trying to access the node attributes from within a template.
In the following example, <trkpt> are the nodes and I need to access their attributes "lat" and "lon".

<?xml version="1.0" encoding="UTF-8" ?>
<gpx>
	<trk>
		<name>Active Log: 2016-06-18 07:08</name>
		<trkseg>
			<trkpt lat="51.657901" lon="-0.877611">
				<ele>200.57</ele>
				<time>2016-06-18T08:55:52Z</time>
			</trkpt>
			<trkpt lat="51.657882" lon="-0.877836">
				<ele>199.61</ele>
				<time>2016-06-18T08:55:53Z</time>
			</trkpt>
			<trkpt lat="51.657874" lon="-0.878071">
				<ele>198.17</ele>
				<time>2016-06-18T08:55:54Z</time>
			</trkpt>
			<trkpt lat="51.657866" lon="-0.878321">
				<ele>197.69</ele>
				<time>2016-06-18T08:55:55Z</time>
			</trkpt>
		</trkseg>
	</trk>
</gpx>

**Comment by engram-design** [comment]
Sure, so you can use something like:
```
{% set params = {
    url: 'http://your/url',
    type: 'xml',
    element: 'trkpt',
} %}

{% set feed = craft.feedme.feed(params) %}

{% for node in feed %}
    {{ node['@lat'] }}
{% endfor %}
```

As a handy hint, you can always use `{{ dump(node) }}` inside that loop to get an idea of what you have data-wise.

**Comment by LucaDelBuono** [comment]
Yay, that works great, but maybe it should be documented?

**Comment by engram-design** [comment]
Actually the documentation was outdated regarding this, so thanks for the prompt to update it! See https://sgroup.com.au/plugins/feedme/feature-tour/using-in-your-templates

**Comment by LucaDelBuono** [comment]
Very nice, thank you so much!
