### ISSUE TITLE
Direct Link not respecting url

### ISSUE THREAD

**Issue by danieltott** [engram-design/FeedMe#204]
I've been trying to run the feed task with different URLs, but it will only use the one saved in the settings. If I change the url in the settings, it works just fine, but not when i use `wget` and the `url=...` parameter as detailed [in the docs](https://sgroup.com.au/plugins/feedme/feature-tour/trigger-import-via-cron). Not sure if I have missed a step somewhere...

**Comment by engram-design** [comment]
I've tested this on my setup, and is working as expected. As we've closed #205, would you mind having another go?

**Comment by danieltott** [comment]
Yeah - the real problem here was a combination of #205 and that i was not `url_encode`ing my url parameter. Using an encoded value for `url=...` works great.
