### ISSUE TITLE
PHP error on Run Task

### ISSUE THREAD

**Issue by danieltott** [engram-design/FeedMe#207]
I'm getting the following error when trying to run my feed task:

```
Invalid argument supplied for foreach()

.../feedme/FeedMe/FieldTypes/BaseFeedMeFieldType.php(36)
```

This is with the latest code. The feed was working properly before the update. 

After digging around a bit, it appears it is failing while trying to process a Matrix field on a Product. The sub-field for the Matrix field is just plain text. It is passing the plain-text value (ie a string) to the `foreach` in `postFieldData`. 

![image](https://cloud.githubusercontent.com/assets/360261/25583372/7fe1b95a-2e5f-11e7-80ff-1c580cbd1950.png)

**Comment by engram-design** [comment]
@danieltott Sorry about that, this should be fixed in the [latest master](https://sgroup.com.au/plugins/feedme/download).

**Comment by danieltott** [comment]
Thanks, that took care of it!
