### ISSUE TITLE
Asset error when using filenames in query string

### ISSUE THREAD

**Issue by arnemart** [engram-design/FeedMe#208]
First of all, thanks for a fantastic plugin, which has saved me countless hours of coding.

The feed I'm downloading has images stored in this format (domain redacted):

`https://example.com/readimage.aspx?pubid=763cb958-b119-4e80-9b7c-200a592de162.jpg`

I.e. the actual filename is in the query string, and only the `pubid=...` changes from entry to entry.

The images are downloaded and stored in `runtime/temp` with the filename `readimage.aspx`. This file is indeed a valid image file, but craft does not recognize it as such and the image is not imported. Is there a remedy for this?

**Comment by arnemart** [comment]
When files are downloaded, the query string is stripped from the url to generate the file name ([AssetFeedMeFieldType.php line 178](https://github.com/engram-design/FeedMe/blob/2.0.3/feedme/FeedMe/FieldTypes/AssetsFeedMeFieldType.php#L178)). If this is skipped, the file is imported successfully.

**Comment by engram-design** [comment]
I've actually refactored this to deal with a whole collection of different URLs. Feed Me will now intelligently try to extract the filename from a URL. You can see how this might get complicated with the URL you're providing - technically it could be `readimage.aspx` or `763cb958-b119-4e80-9b7c-200a592de162.jpg`.

But, Feed Me will now extract the correct filename of `763cb958-b119-4e80-9b7c-200a592de162.jpg`.

Have a go at the [latest master](https://sgroup.com.au/plugins/feedme/download) and let me know how that goes.

**Comment by arnemart** [comment]
Beautiful! Now it works perfectly, thanks a lot!
