### ISSUE TITLE
Feedme into "Address (Smart Map)" field type?

### ISSUE THREAD

**Issue by Ramshackle-Jamathon** [engram-design/FeedMe#21]
https://craftpl.us/plugins/smart-map/
Wondering if you know anyone who has done this before?

If I wanted to add this feature what files should I be looking at?

Thanks!

**Comment by engram-design** [comment]
I know that @lindseydiloreto is looking at this very soon! I'll also be adding some documentation on how to so this for other plugins. I'm working on supporting a few third-party plugins, but would like to hear if you're interested in any in particular (other than Smart Map).

**Comment by bryantAXS** [comment]
So it sounds like this would more so be the responsibility of the fieldtype developer?

**Comment by lindseydiloreto** [comment]
@bryantAXS Generally speaking, yes, this would more likely fall to the 3rd party developer.

But since some of the hooks needed are brand new, both @engram-design and myself are working together to make this happen. Although to be fair, @engram-design is doing most of the work at this point. ;)

No need for [two threads](https://github.com/lindseydiloreto/craft-smartmap/issues/33) on the same topic... I'll funnel traffic over to **this** thread, and go ahead and close the other one. :thumbsup:

**Comment by engram-design** [comment]
Hey all, like @lindseydiloreto says, its up to the fieldtype developer to integrate with Feed Me. I did toss up supporting fieldtypes through Feed Me, but decided I'd rather focus on improving this plugin, than maintaining integration with others :smile: 

The necessary hooks are in place, and ready for the next release (in a few days time). I'll provide documentation and working examples so that you can either get in touch with other fieldtype developers, or modify the fieldtype yourself to provide support. It'll be very straightforward.

Hope that helps - in the meantime, sit tight, and I'll have something sorted very soon!

**Comment by bryantAXS** [comment]
Hey Guys any movement here? We're trying to figure out of we can plan on having these updates in place over the the next week for an upcoming client project. If not we'll reconfigure the way we're doing things, but getting some visibility on when these are going to be released would be fantastic.

Thanks so much!

**Comment by engram-design** [comment]
Hey @bryantAXS sorry for the delay - this will definitely be in place this week, likely in the next few days. I've just been making some further improvements to Feed Me which requires a fair bit of refactoring. Will keep you posted - watch this space.

**Comment by bryantAXS** [comment]
Thanks so much Josh, that's perfect, thanks!

On Mon, Nov 16, 2015 at 8:14 AM, Josh Crawford <notifications@github.com>
wrote:

> Hey @bryantAXS <https://github.com/bryantAXS> sorry for the delay - this
> will definitely be in place this week, likely in the next few days. I've
> just been making some further improvements to Feed Me which requires a fair
> bit of refactoring. Will keep you posted - watch this space.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/engram-design/FeedMe/issues/21#issuecomment-157041964>
> .
>



-- 
*Bryant Hughes*
Partner

*Authentic Form & Function*
Web
<http://authenticff.com/?utm_source=email&utm_medium=email&utm_campaign=email-signature>
|  Twitter <http://twitter.com/authenticff>

**Comment by lindseydiloreto** [comment]
@bryantAXS, the Smart Map portion of this is done, but hasn't been officially released yet. I probably won't release it until after Craft 2.5 comes out (on Dec. 1st).

In the meantime, feel free to email me at support@doublesecretagency.com ... I can send you the upcoming version (which is totally stable), so you'll be ready when Josh releases his Feed Me update.

Ditto for anyone else following this thread... Email me directly, and I'll send you the upcoming version of Smart Map.

**Comment by engram-design** [comment]
Hey @bryantAXS - well that certainly was a long week! Sorry for the delay in getting back to you about this. I've ended up bundling some major changes to Feed Me that I'd been wanting to do for some time, which is mostly cleanup, refactoring and bugfixes. Then along came Craft 2.5, so wanted to ensure all is compatible with that too :smiley: 

In any case, please grab yourself a copy of the [1.4.0](https://github.com/engram-design/FeedMe/releases/tag/1.4.0) release, and then bug @lindseydiloreto to ship Smart Map with his changes.

If you're interesting in modifying other fieldtypes, or your own, consult the [Wiki](https://github.com/engram-design/FeedMe/wiki/Hooks). You can also check out this [PR](https://github.com/elivz/VzAddress-Craft/pull/6) for VZ address, which may or may not get applied.

**Comment by bryantAXS** [comment]
Amazing, thanks so much Josh! I'll be back into the office on Monday and
we'll give things a look right away.

Thanks for the attention to this!

On Thu, Nov 26, 2015 at 3:36 PM, Josh Crawford <notifications@github.com>
wrote:

> Hey @bryantAXS <https://github.com/bryantAXS> - well that certainly was a
> long week! Sorry for the delay in getting back to you about this. I've
> ended up bundling some major changes to Feed Me that I'd been wanting to do
> for some time, which is mostly cleanup, refactoring and bugfixes. Then
> along came Craft 2.5, so wanted to ensure all is compatible with that too [image:
> :smiley:]
>
> In any case, please grab yourself a copy of the 1.4.0
> <https://github.com/engram-design/FeedMe/releases/tag/1.4.0> release, and
> then bug @lindseydiloreto <https://github.com/lindseydiloreto> to ship
> Smart Map with his changes.
>
> If you're interesting in modifying other fieldtypes, or your own, consult
> the Wiki <https://github.com/engram-design/FeedMe/wiki/Hooks>. You can
> also check out this PR <https://github.com/elivz/VzAddress-Craft/pull/6>
> for VZ address, which may or may not get applied.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/engram-design/FeedMe/issues/21#issuecomment-159928927>
> .
>



-- 
*Bryant Hughes*
Partner

*Authentic Form & Function*
Web
<http://authenticff.com/?utm_source=email&utm_medium=email&utm_campaign=email-signature>
|  Twitter <http://twitter.com/authenticff>

**Comment by lindseydiloreto** [comment]
Update... Smart Map 2.3 was [released today](https://craftpl.us/plugins/smart-map/change-log), with full Feed Me compatibility. :+1:
