### ISSUE TITLE
Performance issues after asset matching fix

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#210]
I've been running imports on existing entries to update their assets now that asset matching is fixed, but I'm running into performance issues that weren't there previously.

An example import would be a feed that contains 5k entries, and times out after ~1000 entries, give it take. (Sometimes it's less, like 230 entries.) The same feed will always stall at the same place, however it doesn't seem to be related to specific entries, as I can import the entries that one feed was stalling on at the start of a new feed.

For example, say an import stalls at entry 1010 in an 0-5000 import. It will always then stall at entry 1010. But I can start importing entries from entry #1000 to entry #5000, and #1010 will import happily. (The feed then might then stall after another 1000 entries say, e.g. entry #2000.)

The dev machine has 7gb of RAM allocated to PHP (!). The timeouts just leave the import hanging (still "running" in the DB, though "stalled" in Craft's UI) so no errors are logged unfortunately. PHP's max execution time is being set to 0/infinite so that's predictable I guess, but hard to know what to do.

Is this just a fact of life now that hashing behavior has been changed? Or is something else going on?

I don't know if this is treating the symptoms rather than the cause, but to throw in a FR for this (beyond improved performance), it'd be handy to be able to advanced import options to start the import from a particular step (to use the task manager phrase), especially on bad imports where you might want to work around a bad entry, or continue an import after it failed/stalled. 

Cheers!

**Comment by engram-design** [comment]
it does sound like a memory issue, if its being consistently 'killed' at a certain number. I'll investigate. I don't believe this is to do with the hashing behaviour, which doesn't kick in unless you're providing a non-filenamed URL (http://domain.com/myDynamicImage).

It might help for the moment, but I've added a new configuration option `checkExistingFieldData` which might help. Essentially, it'll look at your feed content you're about to import, and any existing field content, and if they match exactly, it won't update the content. Updating less fields for an import will certainly go a long way to better performance - especially for relational fields like Assets.

See https://sgroup.com.au/plugins/feedme/getting-started/configuration#configuration-options

For your FR, follow via https://github.com/engram-design/FeedMe/issues/216

**Comment by ldstevens** [comment]
I broke up the feeds into smaller parts and it's mostly been fine, and that config setting was very helpful on re-runs thanks!

**Comment by engram-design** [comment]
Closing for now to follow up with [#216](https://github.com/engram-design/FeedMe/issues/216), and for the moment, I believe the `checkExistingFieldData` should help greatly to address this.
