### ISSUE TITLE
Assets being added incorrectly to subsequent entries

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#211]
Looks like there's a new bug in asset handling.

I've got entries with
- Title
- Entry Image
- Entry Gallery (optional)

Only (say) 1 in 10 entries have a gallery. Let's say entry 1 has a gallery. Entries 2-10 shouldn't have a gallery, but currently entries 2-10 are getting entry 1's gallery as well. If entry 11 has a gallery, that's imported, but then entries 12-20 get entry 11's gallery, etc.

Looks like a variable isn't being reset in a loop? (I've checked the import feed too - it's fine.)

Screenshot shows `title / import filename / asset / gallery / match?`
![safariscreen shot 8 may 2017 3 46 15 pm](https://cloud.githubusercontent.com/assets/6646445/25791738/9d4229a2-3405-11e7-8e45-19c752614c29.png)

**Comment by cab00m** [comment]
I can confirm this bug. I have the same problem.

**Comment by engram-design** [comment]
Just to confirm does this still occur with the [latest master](https://github.com/engram-design/FeedMe/archive/master.zip)?

**Comment by ldstevens** [comment]
Yep, was still an issue today with the latest master.

**Comment by engram-design** [comment]
Can you give the [latest master](https://github.com/engram-design/FeedMe/archive/master.zip) a go now?

**Comment by cab00m** [comment]
Is working now in non-matrix fields. Still have the issue importing into matrix.

**Comment by engram-design** [comment]
@cab00m Are you able to give the [2.0.5 release](https://sgroup.com.au/plugins/feedme/download) a go, which should fix this?

**Comment by cab00m** [comment]
Yes, it is fixed! Thank you!
