### ISSUE TITLE
Feed Me only using end of some image filenames

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#212]
When uploading assets, I'm seeing this behaviour with FM, especially where there's extra fullstops in filenames:

**filename orig:** 128GB_microSDXC_633x_w_3.0Reader.JPG
**after import:** 0Reader.JPG

**filename orig:** 10mmT2.1.jpg
**after import:** 1.jpg

Version numbers are problematic, and results in generic filenames like 1.jpg that are likely to result in false duplicates (e.g. something_1.0.jpg and somethingelse_1.0.jpg both = 0.jpg). 

I noticed accents are a problem too:

**filename orig:** Anna-Vadász_Hungary_Shortlist_Youth_Environment_2014.JPG	
**after import:** sz_Hungary_Shortlist_Youth_Environment_2014.JPG 

I tried uploading a file `Kite.ly.jpg` as an asset directly in Craft and its filename remained intact, so I'm guessing (!) it's a FM issue with the way filenames are parsed. (FM imported it as `ly.jpg`.)

**Comment by engram-design** [comment]
Can you give the [latest master](https://github.com/engram-design/FeedMe/archive/master.zip) a go?

**Comment by ldstevens** [comment]
Did the trick, thanks :)
