### ISSUE TITLE
Importing null value for asset field doesn't remove asset/s

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#213]
I imagine this is a bug...

To clean up my entries from #211, I created a feed of titles, slugs, and empty asset fields (news gallery) for all entries which should have an empty asset field. 

I expected that running that import (i.e. null values for asset fields) would update matched entries and remove assets from the specified asset field field. However, the assets remain intact. I tried an empty string, and `null`, but neither worked.

**Comment by engram-design** [comment]
Can you give the [latest master](https://github.com/engram-design/FeedMe/archive/master.zip) a go?

**Comment by ldstevens** [comment]
Thanks for the fix! Solved the issue. Had my fingers crossed it would solve #211 as well if `null` fields were present, but no such luck.
