### ISSUE TITLE
Child categories

### ISSUE THREAD

**Issue by EmptyStreets** [engram-design/FeedMe#217]
Hello,

Is is the right syntax to import parent and child categories? (XML)

       <categories>
            <category>California</category>
            <category>Sacramento</category>
        </categories>

**Comment by engram-design** [comment]
No, there's no notion of hierarchy to that feed. Which nodes are the parent and child?

```
<categories>
  <category>California</category>

  <subcategories>
    <category>Sacramento</category>
  </subcategories>
</categories>
```
<img width="1076" alt="screen shot 2017-05-14 at 8 31 21 am" src="https://cloud.githubusercontent.com/assets/1221575/26029765/9cbc8d04-3880-11e7-93ed-863fd9fb34b3.png">

Note that currently only existing categories can be matched - Feed Me won't create your parent Categories for you yet.
