### ISSUE TITLE
PHP Errors Importing JSON

### ISSUE THREAD

**Issue by liamscott** [engram-design/FeedMe#22]
Encountering an error when I try importing a feed from JSON: 

![screen shot 2015-11-17 at 5 30 11 pm](https://cloud.githubusercontent.com/assets/5066494/11227057/c1d2673e-8d51-11e5-84b5-7d1ba2e2a17a.png)

Could this be a JSON validation issue? Is there a place I can see a more detailed log?

**Comment by engram-design** [comment]
@liamscott Sorry for not getting back to you sooner. This does seem to point to an issue with the JSON feed - with it potentially not being formatted properly.

If you could either: 1) Post the link to your feed here, 2) Use the Feed Me Help widget to send us directly the feed in question, or 3) Get in touch over Slack, and we'll give you a hand!

**Comment by liamscott** [comment]
@engram-design Thanks for the help! I ran the feed through some JSON validators and they all passed, but maybe there is a specific standard you are using? You can find the feed at http://cdn2.hubspot.net/hubfs/372554/blog-posts.json

**Comment by engram-design** [comment]
Hey @liamscott - this actually seems to be a bug, which I'm glad you stumbled upon! Please see the [1.4.3](https://github.com/engram-design/FeedMe/releases/tag/1.4.3) release which fixes this. Also make sure you're using `objects` as your primary element.

Let me know if you have any further issues!

**Comment by liamscott** [comment]
@engram-design Thank you so much for patching that issue so quickly! That issue has certainly been solved (no longer getting any PHP errors), however I'm still having an issue where my import is failing. Is there a more detailed log somewhere that would assist me in debugging?

I'm curious, if I'm importing a blog post and don't set an author, what happens? Is there a default behavior where the program assigns admin as the author if not specified? Right now, I'm not setting one and wondering if that might be causing my import to fail.

**Comment by engram-design** [comment]
Not really a more detailed log other than whats provided, but if you'd like to post to the Feed Me Help widget again, happy to look into it.

Right now, it'll import using the currently logged in user. Its on the roadmap to be able to set default values across all fieldtypes. In your case, it'd look for a mapped user, and default to the current user if not found. Sounds like something else might be happening...

**Comment by engram-design** [comment]
Closing for now, as from memory this was finished up through Slack. Please let me know if you're continuing to have issues!
