### ISSUE TITLE
Asset fields updated on import re-run

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#220]
I have feeds which import assets, and assign the entry's pub date to the asset's own field ("assetDate"). Whenever I re-run an import, I see a lot of:

> Updated Asset (ID 62874) inner-element with content: {"assetDate":"2016-08-03 14:00:00"}

At least going by the logs, it looks like this field always gets updated, even when the field's value hasn't changed from the previous import. Just mentioning it fwiw :)

**Comment by engram-design** [comment]
This has been improved in the [latest master](https://sgroup.com.au/plugins/feedme/download). Note that you'll still need to set the `checkExistingFieldData` config option to make this work.
