### ISSUE TITLE
Best approach to import table rows

### ISSUE THREAD

**Issue by EmptyStreets** [engram-design/FeedMe#222]
Hey,

I've created a table field (no matrix) with opening hours.

![screenshot-ntl dev 2017-05-17 18-37-15](https://cloud.githubusercontent.com/assets/1551388/26165413/2f004bc2-3b30-11e7-9ac4-266f181186d8.png)

However on the fields mapping page there is no option to map values for each row. Is there a workaround for this?

XML has the following code:
       ` <hoursMonday>9am - 8pm</hoursMonday>`
         `<hoursTuesday>9am - 7pm</hoursMonday>`

and so on.

**Comment by engram-design** [comment]
Can you provide a screenshot of the field mapping screen for Feed Me? You absolutely should be able to pick the individual column you want to import into. See attached.
![screen shot 2017-05-20 at 3 11 02 pm](https://cloud.githubusercontent.com/assets/1221575/26273231/8fa32eaa-3d6e-11e7-9e2d-d6ec2e7d2a17.png)

**Comment by EmptyStreets** [comment]
Hey,

Yes it is possible for columns. But I'm trying to import days and hours as rows. Thanks.

**Comment by engram-design** [comment]
Thats not really possible at the moment. You would need to have your feed formatted something like:

```
<row>
  <day>Monday</day>
  <hours>9am - 8pm</hours>
</row>
<row>
  <day>Tuesday </day>
  <hours>9am - 7pm</hours>
</row>
```
