### ISSUE TITLE
Existing elements aren't re-enabled with "disable missing elements" import strategy

### ISSUE THREAD

**Issue by OscarBarrett** [engram-design/FeedMe#223]
If "disable missing elements" is enabled as a strategy, and
- An item appears in the feed and gets created
- The item disappears from the feed and gets unpublished
- The item then reappears in the feed

then it doesn't get re-enabled.

**Comment by engram-design** [comment]
Do you have "Don't Import" set for the elements' status? If you do, then it won't touch whatever the existing status of an entry is, be it enabled or disabled.

**Comment by OscarBarrett** [comment]
Ah thanks, that was the issue. The feed doesn't have a field that should determine the status - all items that appear in it should be enabled. Setting the default to enabled worked (and left previously disabled elements disabled).
