### ISSUE TITLE
Date as Unique Identifier Errors

### ISSUE THREAD

**Issue by kragit** [engram-design/FeedMe#225]
I'm using an RSS feed from the [NOAA](http://w1.weather.gov/xml/current_obs/seek.php?state=mi&Find=Find).

When I attempt to import placing the <title> in the Title field, the <guid/@> in the Post Date field ~~(which doesn't seem to actually import the date - it sets the entry as the DateTime imported, not what's set in the RSS feed, but that may be a different issue)~~ and the <description> in a text field, with the unique identifier selected as Post Date, the task fails and the debug page throws this error:

`Fatal error: Call to a member function getTimestamp() on boolean in /home/***/***/craft/app/helpers/DbHelper.php on line 597`

When selecting the Expiry Date (which is empty), the task again fails and presents this error:
`Undefined offset: 0
/home/***/***/craft/app/helpers/DbHelper.php(564)`
(obviously less concerned about this, as I don't plan on using the Expiry Date).

Using Title & Entry ID as unique identifiers allows the feed to import as intended (so far).

**Comment by engram-design** [comment]
This has been added to the [latest master](https://sgroup.com.au/plugins/feedme/download).
