### ISSUE TITLE
FR: Allow user group(s) to be imported as field/data

### ISSUE THREAD

**Issue by theskyfloor** [engram-design/FeedMe#227]
For many of our large user conversions we need the ability to import users into more than one group at a time. Ideally this would be accomplished by creating an array of user group handles or id's in the data set to be imported and then assign that key to the user group import function.

Thanks!

**Comment by engram-design** [comment]
This has been added as of the [latest master](https://sgroup.com.au/plugins/feedme/download). You can set the default user groups, of provide an array in your feed using either the ID, Name or Handle of user groups.

```
<?xml version="1.0" encoding="UTF-8"?>
<rss>
<channel>
    <item>
        <firstname>user 1</firstname>
        <groups>
            <group>Imported</group>
            <group>Imported 2</group>
        </groups>
    </item>
    <item>
        <firstname>user 2</firstname>
        <groups>
            <group>Imported</group>
        </groups>
    </item>
</channel>
</rss>
```
