### ISSUE TITLE
Locales throwing errors

### ISSUE THREAD

**Issue by cole007** [engram-design/FeedMe#23]
Cannot import errors that are not assigned to the default locale

**Comment by engram-design** [comment]
Locale-specific importing isn't supported at the moment, but I'll add that to the roadmap. I'll look at adding this sooner rather than later however.

**Comment by cole007** [comment]
Great thanks - there is a solution where you can temporarily move the
required locale to be the default locale which resolves this but obviously
not ideal.

Thanks again!

On 14 December 2015 at 22:36, Josh Crawford <notifications@github.com>
wrote:

> Locale-specific importing isn't supported at the moment, but I'll add that
> to the roadmap. I'll look at adding this sooner rather than later however.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/engram-design/FeedMe/issues/23#issuecomment-164582098>
> .
>



-- 
Cole Henley
Technical Director
Mud // Clear Digital Thinking

3a Fountain Buildings  Bath  BA1 5DU
01225 471 465

**Comment by brettgullan** [comment]
Hi @engram-design Any further thoughts on Locale support? I have a project starting very shortly, that is going to need the ability to handle importing of data—ideally via RSS—in multiple languages.

Happy to help out, if that would move things along … ?

Cheers,

Brett

**Comment by engram-design** [comment]
No progress as of yet, but its a relatively straightforward (off the top of my head at least) to implement. 

I'll have a look this weekend and get back to you if anything comes up that might make things take longer!

**Comment by brettgullan** [comment]
Awesome. Thank you!!

**Comment by brettgullan** [comment]
Hi @engram-design, Sorry to pester! Wondering if you've had a chance to look at Locale support yet? Many thanks,
Brett

**Comment by engram-design** [comment]
This has been included in the [1.4.7 release](https://github.com/engram-design/FeedMe/releases/tag/1.4.7).
