### ISSUE TITLE
Integrity Constraint Violation issue

### ISSUE THREAD

**Issue by joshua-martin** [engram-design/FeedMe#230]
We seem to be getting a lot of these errors popping up in our FeedMe logs

    Message	[Forced] Events: CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'event/junior-youth-theatre-year-5-en_gb' for key 'craft_elements_i18n_uri_locale_unq_idx'

It does look like the task then successfully completes all of its steps, but then doesn't close itself off and sticks as a 'Failed Task' in Craft.

![screen shot 2017-06-23 at 09 23 07](https://user-images.githubusercontent.com/1694957/27473055-a0a258ce-57f5-11e7-8164-560b4dac9a17.png)

See attached log from the last couple of days for your reference: [feedme.txt](https://github.com/engram-design/FeedMe/files/1097189/feedme.txt)

Many thanks

**Comment by engram-design** [comment]
Are you able to send a Help request? Really need a bit more information if possible!

**Comment by joshua-martin** [comment]
Oh yes, sorry. I forgot you introduced that in v2! I've just pushed one through for you.
