### ISSUE TITLE
Entries fieldtype issue

### ISSUE THREAD

**Issue by EmptyStreets** [engram-design/FeedMe#232]
![screenshot2017-07-04 16-12-33](https://user-images.githubusercontent.com/1551388/27833740-4afa656e-60d4-11e7-9647-a440f3883f0c.png)
Hello,

I'm trying to map entries fieldtype to existing entry. Entry slug is xenith-bank. I define it as a slug as there are a lot of same titles but slugs are unique. I expect that during the import feedme will look up for an entry with the specified slug and make a relation, however the entries field isn't populated and empty.

Logs tab is good, no errors there. Plugin version is 2.0.7. Please help :(

**Comment by engram-design** [comment]
@EmptyStreets Are there any settings on your entries field? Say if you have limited entries for that field to be only from particular sources, Feed Me will respect that. It won't find entries outside of the sections you've allowed.

Failing that, have you updated your Search Indexes? Have you also run the debug action?

**Comment by EmptyStreets** [comment]
Hey,

- there are no limitations in the field settings
- search indexes were rebuilt  as well
- feedme.log does look good too. no errors. all other fields are imported and work correctly except relations (entries) fieldtype where I provide the "slug" value to find and relate and existing entry.

![2017-08-20 09-18-53](https://user-images.githubusercontent.com/1551388/29493379-baa23f88-8594-11e7-9fcb-8de7063e9537.png)


in /srv/users/serverpilot/apps/_craft/app/etc/plugins/BasePlugin.php (65)
in /srv/users/serverpilot/apps/_craft/plugins/feedme/services/FeedMe_ProcessService.php (185)
in /srv/users/serverpilot/apps/_craft/plugins/feedme/tasks/FeedMeTask.php (77)
2017/08/20 08:35:02 [info] [plugin] [Forced] Branches: Entry 28067 updated.

**Comment by EmptyStreets** [comment]
I have changed the "data provided for this field is slug" to "title" did a test import and changed it back to slug. It has helped. That was a strange glitch :(

**Comment by EmptyStreets** [comment]
I did some more tests and here are the results:

data provided for this field set to title = work as expected
data provided for this field set to slug = field remain empty. If I select related entry manually and do another run (update entries) it becomes empty again.

DB encoding set to utf8_unicode_ci. INNODB, mysql 5.7, php 7.1.

XML file format:

`<row>
		<bankName>1st Bank Yuma</bankName>
		<bankSlug>1st-bank-yuma</bankSlug>
</row>`

Please advice :(

**Comment by engram-design** [comment]
I will double-check that all works when using an entry slug, and I'll let you know.

**Comment by EmptyStreets** [comment]
Hey,

Sorry for bothering you. Is there any ETA when you plan to do the tests? Thanks.

**Comment by engram-design** [comment]
So, I imagine the entry `1st Bank Yuma` exists in the Institutions Section correct? I've tested this thoroughly locally, and its working well for me. I don't suppose any of the entries are disabled, or if you have a multi-locale site setup?

![screen shot 2017-08-30 at 3 20 06 pm](https://user-images.githubusercontent.com/1221575/29856514-be8d7bda-8d96-11e7-8786-ab0a6bfd5b44.png)
![screen shot 2017-08-30 at 3 21 42 pm](https://user-images.githubusercontent.com/1221575/29856552-f212a296-8d96-11e7-852b-052f8a07b56f.png)

**Comment by EmptyStreets** [comment]
Somehow it started to work as expected. I did a fresh install and tested it again and it works.

**Comment by engram-design** [comment]
@EmptyStreets Do let me know if it happens again, but does sound like a Search Indexing issue (I know you said you refreshed them), but can't think what else!
