### ISSUE TITLE
Honour Default Entry Status setting for Section

### ISSUE THREAD

**Issue by howells** [engram-design/FeedMe#234]
It seems that if the Default Entry Status is set to disabled, all new imported entries are set to enabled. Is there a way to have FeedMe honour this setting, so that any new entries are set to whatever it is?

I thought this could be worked around by setting the field mapping default for Status to Disabled (without mapping Status to a source), but when I ran the import again, all the entries were set to Disabled.

**Comment by engram-design** [comment]
This should be implemented as of the [latest master](https://sgroup.com.au/plugins/feedme/download). However, bare in mind this will only effect new entries created, and won't effect existing entry status
