### ISSUE TITLE
Error on import: Page Not Found 

### ISSUE THREAD

**Issue by cscomfort** [engram-design/FeedMe#240]
I just updated to the latest version of FeedMe (2.0.7) by uninstalling and reinstalling. Now, when creating a new feed and trying to import (using Save & Import button) I get the following error:

**Page Not Found**
The system is unable to find the requested action "saveAndImportFeed".

Currently using: Craft 2.6.2983 with PHP Version 5.6.28.

**Comment by engram-design** [comment]
That seems odd, have you tried clearing the caches for Craft? It does sound like there was an issue updating the Feed Me files, as there's no longer a `saveAndImportFeed` action. That endpoint should be there as of 2.0.7.

**Comment by cscomfort** [comment]
Looks like the cache-clearing resolved the issue. Thought I had done so previously, but apparently not. Thanks, and keep up the great work!
