### ISSUE TITLE
VZ Address integration broken?

### ISSUE THREAD

**Issue by spib** [engram-design/FeedMe#241]
Did the integration with VZAddress (https://github.com/elivz/VzAddress-Craft/pull/6) get broken somewhere along the line? I tried following the example of SmartMaps from https://github.com/engram-design/FeedMe-Helpers but I couldn't see how the helper knows which field type it's associated with?

**Comment by engram-design** [comment]
@spib I believe the VZ Address field types' integration is a bit out of date. Please refer to the [Feed Me Helpers](https://github.com/engram-design/FeedMe-Helpers) for an up to date integration.

**Comment by spib** [comment]
Excellent, thanks so much
