### ISSUE TITLE
Getting : {"title":["Title cannot be blank."]} even i dont import title.

### ISSUE THREAD

**Issue by idolab** [engram-design/FeedMe#247]
Trying to import commerce_product variants (only updating the variant QTY), this errors keep showing. 
Import Strategy = update exisiting
Slug & SKU are the unique identifier.

```
<?xml version="1.0" encoding="UTF-8"?>
<products>
	<product>
		<slug>pwrbkcrecd2500</slug>
		<variants>
			<variant>
				<sku>720072</sku>
				<qty>123</qty>
			</variant>
		</variants>
	</product>
</products>
```

**Comment by engram-design** [comment]
This should be fixed as of the [latest master](https://sgroup.com.au/plugins/feedme/download).
