### ISSUE TITLE
{"uri":["URI ist kein g\u00fcltiger URI"]}

### ISSUE THREAD

**Issue by jacfab** [engram-design/FeedMe#248]
I am trying to import certain fields for a section of around 100 entries from a .json file. 
so each entry has an ID which the "unique identifier for existing elements". the "keyword" should be added to a certain field.

That works alright first but for certain files / fields it interrupts after a few processed ones. The protokol says: 

> {"uri":["URI ist kein g\u00fcltiger URI"]}

I already reduces the JSON a lot to make sure theres no syntax error in the file:
```
[
{
    "id": 105,
    "keyword": "uberall geomarketing"
},
{
    "id": 108,
    "keyword": "efre"
}
]
```

**Comment by engram-design** [comment]
I have a feeling this might be an issue with the slug being generated not being valid - therefore the resulting URI is invalid as per your error message. Have you had a look at [limitAutoSlugsToAscii](https://craftcms.com/docs/config-settings#limitAutoSlugsToAscii) config setting?

This should turn the slug from `gültiger` to `gultiger`.

**Comment by jacfab** [comment]
I think thats a very good guess. unfortunately limitAutoSlugsToAscii doesnt make a change in that case.
I am wondering why the progress changes the url at all. No new slug has to be created as I am even not touching the "title" field...

**Comment by engram-design** [comment]
Hmmm, without looking at your whole feed (and current entries) its a little hard to guess. If you're just re-saving existing entries by adding content to custom fields, then it certainly is odd.

Does the URI error message change, or are there multiple ones? For instance, have you gone to manually edit the entry with slug `gültiger`, just to see if that saves normally like you would through Craft's CP? Feed Me pretty much uses the same process to save an entry...

It might be worth submitting a Help request through the plugin to allow us to get some more information on your setup?

**Comment by jacfab** [comment]
In german you can say something like I didn't see the forest because of too many trees...

Well the problem was that I imported the entries, changed the URL of the section to {title}-something (craft doesnt complain about eventual conflicts at this point until you save one of the entries again) and then I tried to update them with Feedme (including the title field). 

I noticed that when I tried to update the entries manually and craft wouldnt let me.

Josh, thanks your help finding that solution!

**Comment by engram-design** [comment]
Ah gotcha, glad you got to the bottom of it!

**Comment by EpocSquadron** [comment]
For any future searchers that happen upon this issue, in addition to the option of changing which field is used to generate the uri, you can also pass unsafe values to the `kebab` twig filter. This filter will get rid of spaces and normalize to kebab case like everything else in craft. Non-ascii characters are already handled as internally there is a urlencode performed (unless you explicitely dont want special characters, in which case you can pass the `url_encode` or `ascii` filters).
