### ISSUE TITLE
Add Support for Importing Data into Comments

### ISSUE THREAD

**Issue by ademers** [engram-design/FeedMe#253]
Have you considered adding support for importing data into your Comments plugin?

An example use case would be migrating ExpressionEngine comments into a Craft install that is using the Comments plugin for comments. 

I noticed that you added an issue over in the Comments repo: https://github.com/engram-design/Comments/issues/63

**Comment by engram-design** [comment]
This has now been implemented as part of the [Feed Me Helpers](https://github.com/engram-design/FeedMe-Helpers) repository. Download the `commentshelper` and install as a regular plugin.

Please also note you'll need the latest [master](https://github.com/engram-design/Comments/archive/master.zip) of the comments plugin.
