### ISSUE TITLE
BE formatted dates not imported correctly (or not at all)

### ISSUE THREAD

**Issue by timbertens** [engram-design/FeedMe#255]
I've read feedme uses date_parse to parse dates in an inbound feed.  This usually works out great, the issue I have now is a certain XML-feed is using the Belgian format (dd/mm/yyyy). I'm unable to change that unfortunately.

2 issues:

1. in case the dd is > 12, the import does not process the date

1. when dd <= 12, it does import them but for some reason it has an -2h offset. Probably some timezone issue, as the timezone is set to Europe/Brusssels, which is CET+2h

**Comment by engram-design** [comment]
Actually, for this reason (and a few others), we don't rely on `date_parse` anymore, instead using [Carbon::parse](https://github.com/briannesbitt/Carbon). And is Australia (where we're from), this is the norm for date formatting, so we've used this daily.

What version on Feed Me are you running? Is this a custom date field, or are you mapping to one of the element attributes (Post Date, etc)?

If you're interested, we've got a [helper](https://github.com/engram-design/FeedMe/blob/master/feedme/FeedMe/Helpers/FeedMeDateHelper.php) for this sort of thing.

**Comment by timbertens** [comment]
The issue with the offset is solved in the current version on the master branch (I was using the 2.0.7 release version).  

The dates with the problem occur in a custom date field, e.g original feed vs debug output 
- <D_BEGIN>16/03/2016</D_BEGIN> ---> [dBegin] => 
- <D_BEGIN>28/09/2015</D_BEGIN> ---> [dBegin] => 
- <D_BEGIN>8/03/2017</D_BEGIN> ---> [dBegin] => 2017-08-03 00:00:00 (CORRECT!)

Is there a way I can preparse the input data before the writes to the database actually occur? 

ps: let's keep the conversation here, i'll update stackexchange to keep in sync with the answers

**Comment by engram-design** [comment]
After a bit of research on this, I've discovered that PHP's date methods actually assume when a date is provided with slashes in the date, it expects it to be mm/dd/yyyy.

However, I've added additional functionality to cater for these edge-cases. As of the [latest master](https://sgroup.com.au/plugins/feedme/download) Date fields now have format options, enforcing specific formatting that the field is provided on. Feed Me will try and do its best to parse the date automatically, but there are cases where you need to force the format its being provided.

![screen shot 2017-08-31 at 3 19 49 pm](https://user-images.githubusercontent.com/1221575/29907647-e9c14696-8e5f-11e7-8f21-da9c39edcf35.png)

**Comment by timbertens** [comment]
well, that is just awesome! I've updated the plugin and it works great!
