### ISSUE TITLE
Entries parent entry

### ISSUE THREAD

**Issue by EmptyStreets** [engram-design/FeedMe#256]
Hey,

Imported element:

- entry with related (entries field) that points to a structure with multiple (2) levels. A child entry is selected but I'd like to have its parent to be selected as well. What is the proper syntax (XML)?

I hope it is supported as I also don't see an option to select the parent entry manually.

Thanks.

**Comment by engram-design** [comment]
Can't you provide both the parent and child entry slug/ids/titles?

```
<Entries>
        <Entry>level-1</Entry>
        <Entry>level-2</Entry>
</Entries>
```
![screen shot 2017-09-01 at 7 35 10 am](https://user-images.githubusercontent.com/1221575/29946310-24f9f162-8ee8-11e7-86e9-b64e3a27476f.png)

![screen shot 2017-09-01 at 7 35 23 am](https://user-images.githubusercontent.com/1221575/29946309-24f7c7e8-8ee8-11e7-837e-68f78701e622.png)

**Comment by EmptyStreets** [comment]
Hi,

No, it it not possible. Also your screenshots dont show the desired result.
It has to list child under parent entry instead of simply select 2 entries.

**Comment by engram-design** [comment]
Have you tried selecting a child and parent manually through an Entries field? I just did and it didn't preserve the structure of entries in the field. Can you confirm?

**Comment by EmptyStreets** [comment]
Yes you are right, it ignores the parent entry.
