### ISSUE TITLE
Importing delete "Don't Import" matrix field content

### ISSUE THREAD

**Issue by idolab** [engram-design/FeedMe#257]
On updating Commerce_Product (match by product slug & variant's SKU => update variant's QTY)
Other Matrix fields (on another tab) on the product get removed even set to "Don't Import"

Check the url below to see an example feed i used.
http://gmyle.s3.amazonaws.com/feed/craftcms/general-product.xml

====
Import Strategy: Update existing elements
A+ content (the matrix field) is set to "Don't Import"
![screen shot 2017-09-11 at 18 00 19](https://user-images.githubusercontent.com/7658690/30269351-20a1d810-971b-11e7-9a14-0b38476ceae7.png)

**Comment by stianmandarin** [comment]
Confirming that I have this problem too

**Comment by engram-design** [comment]
@stianmandarin @idolab Have you both tried the [latest master](https://sgroup.com.au/plugins/feedme/download) to confirm if it is still happening?

**Comment by stianmandarin** [comment]
@engram-design Hey, thanks for getting back. I'm already on 2.0.7 (that is the latest right?)

**Comment by engram-design** [comment]
@stianmandarin The master has got a few fixes I'm about to roll into a 2.0.8 release

**Comment by stianmandarin** [comment]
@engram-design Aha, I see. Tried the master now, but the problem persists

**Comment by idolab** [comment]
@engram-design Tried the master too, but the problem persists +1

**Comment by webvader** [comment]
Hi, any news on this? I've got the same problem too ...

**Comment by stianmandarin** [comment]
Sorry to be a pain, but are there any news on this? We're about to launch a site, so it's a bit critical

**Comment by engram-design** [comment]
Hi all, this seems to be an issue with the newly added 'Enabled' block option. Selectize.js apparently doesn't let you select blank values (for Don't Import) so they only way around this at the moment is to select the Enabled dropdown field and hit backspace - this will save with an empty value.

Pushing a fix for this regardless shortly.

**Comment by engram-design** [comment]
This is fixed in the latest master, but as I mentioned, for all current feeds, you'll need to actively remove the value from the Enabled default field by pressing backspace. This is because its already saved as importing as enabled.

The way field mapping works at the moment, is that if any value is mapped to a field (even defaults) it'll enact the parsing. This will change in the Craft 3 version of Feed Me.
