### ISSUE TITLE
Error reading namespaced RSS tags

### ISSUE THREAD

**Issue by andyra** [engram-design/FeedMe#27]
I'm having trouble parsing an RSS feed for a podcast that includes namespaced tags (`<itunes:summary>`, `<itunes:image>`, etc.) because Twig thinks the colon is the start of a code block.

**Example:**
```
<p>Description</strong>: {{ node.itunes:summary }}</p>.
=> Unexpected token "punctuation" of value ":" ("end of statement block" expected).
```

What's the best way around that? This is a wonderful plugin, by the way. Great work!

**Comment by engram-design** [comment]
You'll have to use the array notation for that - have a look at the [example code](https://github.com/engram-design/FeedMe/blob/master/README.md#template-example) 

So you'd use 'node['itunes:summary']'
