### ISSUE TITLE
Using ftp:// URLs fails

### ISSUE THREAD

**Issue by nervetattoo** [engram-design/FeedMe#29]
Everything is in place for using ftp (and other protocols, like file://) except for the validation caused by `AttributeType::Url`.
I guess the simplest way around it is using ::Uri and writing custom validations in the record/model.

I've hacked my way around it by just changing the attributetypes locally at least ...

**Comment by engram-design** [comment]
Hadn't thought about using ftp and other protocols, but I suppose that makes sense. This'll be changed in the next release, thanks!

**Comment by engram-design** [comment]
This has been included in the [1.4.7 release](https://github.com/engram-design/FeedMe/releases/tag/1.4.7).
