### ISSUE TITLE
Imports not working for Atom feeds

### ISSUE THREAD

**Issue by jonathanmelville** [engram-design/FeedMe#3]
I have a standard, well-formed Atom XML file that I'm trying to import into Craft with FeedMe. When setting up the initial import, the data in the XML seems to be read properly by FeedMe as I can see it on the plugin page.

However when the import actually runs. The custom fields are blank. See attached screenshots for one example of this.

![screen shot 2015-04-22 at 4 05 25 pm](https://cloud.githubusercontent.com/assets/7415693/7284205/f8253948-e909-11e4-8e9a-ab086d98f314.png)

![screen shot 2015-04-22 at 4 10 14 pm](https://cloud.githubusercontent.com/assets/7415693/7284243/446e6dc4-e90a-11e4-9ada-82d411f2882a.png)

**Comment by engram-design** [comment]
There were some issues regarding nested attributes which have been fixed. Please give the latest commit a go!

**Comment by jonathanmelville** [comment]
Fixed! Thanks so much!

**Comment by engram-design** [comment]
Awesome - glad we got there! :)
