### ISSUE TITLE
Import feeds to categories (and users?)

### ISSUE THREAD

**Issue by kmelve** [engram-design/FeedMe#30]
It would be nice if we could import to categories. And, I am not sure if it's a good idea, perhaps users also?

**Comment by engram-design** [comment]
Certainly, I would like to expand it out to all elements - Commerce Products included. I'm keeping things purely Entry-based for the moment, and there's lots more core functionality I'm looking to include in the plugin. If there's enough demand, I'll certainly consider it - but it'll likely be a post-2.0 focus.

Until then, there's always [Import](https://github.com/boboldehampsink/import)!

**Comment by mazedesign** [comment]
sorry to be that guy, but is there any timeline for the 2.0 beta, or just this feature?

**Comment by engram-design** [comment]
@mazedesign No timeline yet, but work is well underway on it.

**Comment by engram-design** [comment]
This has finally been added to Feed Me 2 along with Users, Commerce Products and any third-party element.
