### ISSUE TITLE
Processing fails with title":["Title is invalid."]

### ISSUE THREAD

**Issue by neekster** [engram-design/FeedMe#33]
My first feed, which is a much more complex and large import works perfectly. Then when I came to do the very very simple one I get the error below every time:

`{"title":["Title is invalid."]}`

To ensure it's not an issue with our file, I've reproduced this error with a sample from w3schools:

```
<?xml version="1.0" encoding="UTF-8"?>
<bookstore>
  <book category="cooking">
    <title lang="en">Everyday Italian</title>
    <author>Giada De Laurentiis</author>
    <year>2005</year>
    <price>30.00</price>
  </book>
  <book category="children">
    <title lang="en">Harry Potter</title>
    <author>J K. Rowling</author>
    <year>2005</year>
    <price>29.99</price>
  </book>
  <book category="web">
    <title lang="en">Learning XML</title>
    <author>Erik T. Ray</author>
    <year>2003</year>
    <price>39.95</price>
  </book>
</bookstore>
```

I get the error regardless if it's set to Add, Update or Delete duplicate entries. 

I'm using Craft 2.4.2688 and have also reproduced it on 2.5 and 2.6, all running 1.4.9 of FeedMe.

In the above example I used the Title as the Title field.

If I remove the second and third elements leaving just a single element, it works fine. I suspect after completing the mapping screen, when I save the changes the mappings are lost, causing the error above as it no longer has a mapped field for the title. 

I'll log a support request too so you have logs etc.

**Comment by engram-design** [comment]
Yep, if you could file a support request, that'd help greatly so I can double-check your settings. Thanks!

**Comment by neekster** [comment]
All fixed, Josh pointed out my glaring error, selecting the wrong primary XML  element. Once I change this everything worked perfectly. In my example above. In my code example above, I had selected bookstore when the correct one was book.
