### ISSUE TITLE
Feature request - Select parent entry within structure to import under

### ISSUE THREAD

**Issue by lexbi** [engram-design/FeedMe#34]
Hey, thanks for your fantastic plugin!

I'm sure this sort of thing is probably on your to-do list, but, I would love to import a load of entries under an existing entry within a structure.

**Comment by engram-design** [comment]
Its actually not something I'd planned to do - so thanks for the request!

**Comment by engram-design** [comment]
Added in [Feed Me 2.0 beta 1](https://github.com/engram-design/FeedMe/tree/2.0.0).

**Comment by lexbi** [comment]
Many thanks!
