### ISSUE TITLE
Failed import with auto-generated titles

### ISSUE THREAD

**Issue by zizther** [engram-design/FeedMe#36]
My imports fail when a section has the title set to auto-generate based on other fields.
The error shows as Import: {"title":[" cannot be blank."]}

Removing this does solve the problem, but all entry titles then need to be adjusted.

Is there a way to support importing with auto-generated titles?

**Comment by engram-design** [comment]
Feed Me supports this out of the box (just double checked too), but bare in mind you have to map the other fields that dynamically make up your title field.

If you're struggling, can you send a Help request, along with your title format for your entry type?

**Comment by ImDineshSaini** [comment]
Same issue arises with me: https://www.us-cert.gov/ncas/all.xml Could you please suggest what fields should I have to create. Please find the attached screenshot for reference. 
![fireshot capture 33 - news - enetics networks_ - http___localhost_enetics_trunk_pub](https://cloud.githubusercontent.com/assets/16646294/14133883/8a1cf40c-f670-11e5-9d35-8a65db2fb04d.png)
![fireshot capture 32 - fields - enetics networks_ - http___localhost_enetics_trunk_pub](https://cloud.githubusercontent.com/assets/16646294/14133884/8a1d224c-f670-11e5-9d69-eb19cc5aaaab.png)
![fireshot capture 31 - news feed - enet_ - http___localhost_enetics_trunk_public_admin_feedme_feeds_1](https://cloud.githubusercontent.com/assets/16646294/14133885/8a1e1ad0-f670-11e5-9ae6-15e6dd3ecc8f.png)

**Comment by engram-design** [comment]
@ImDineshSaini Is your title format correct? Its listed as `{ite.first.title}` - what is `ite`?

**Comment by ImDineshSaini** [comment]
Yes it is {title} and i have set item as well please see screenshot
![fireshot capture 35 - feed me - enetics n_ - http___localhost_enetics_trunk_public_admin_feedme_logs](https://cloud.githubusercontent.com/assets/16646294/14137728/cf1354b4-f686-11e5-9af9-6db738234bf9.png)
![fireshot capture 34 - news - enetics networks_ - http___localhost_enetics_trunk_pub](https://cloud.githubusercontent.com/assets/16646294/14137729/cf1c1c8e-f686-11e5-83dc-0a06ffd4ac2b.png)

**Comment by engram-design** [comment]
@ImDineshSaini You don't seem to have a title field in your entry - only a Link field? Have you actually tried to create an Entry for this section manually - did it work? See below example - I don't believe this is a Feed Me issue.

![screen shot 2016-03-30 at 10 06 03 pm](https://cloud.githubusercontent.com/assets/1221575/14140256/abdaab36-f6c3-11e5-84b3-b36fbb6c0c13.png)

**Comment by ImDineshSaini** [comment]
There is no field created by Feed me so I have to create one

**Comment by ImDineshSaini** [comment]
![fireshot capture 36 - news - enetics networks_ - http___localhost_enetics_trunk_pub](https://cloud.githubusercontent.com/assets/16646294/14140490/d38877d0-f696-11e5-9919-06f3ffa8a163.png)

**Comment by engram-design** [comment]
Feed Me won't create any fields for you, so yes, you'll need to create any fields you need.

The Title Format option allows you to use any inbuilt fields for an entry (author, slug, section, dateCreated, etc) along with any custom fields you may have to make the title. Because you have `Show the Title field` unticked, you can't use the Title field for your dynamic title.

I have just tested with the below trying to create a manual entry, and it fails because the Title Format is incorrect (there is no field called Title, because you're dynamically generating one).

![screen shot 2016-03-30 at 10 18 23 pm](https://cloud.githubusercontent.com/assets/1221575/14140544/58772d0a-f6c5-11e5-9659-d7647066f145.png)

![screen shot 2016-03-30 at 10 18 44 pm](https://cloud.githubusercontent.com/assets/1221575/14140553/65c2b92a-f6c5-11e5-92d5-e008d3e7b753.png)

![screen shot 2016-03-30 at 10 19 10 pm](https://cloud.githubusercontent.com/assets/1221575/14140559/7360d878-f6c5-11e5-93d4-53da04b143e2.png)

**Comment by ImDineshSaini** [comment]
I have updated and add only link from xml. 
![fireshot capture 37 - feed me - enetics n_ - http___localhost_enetics_trunk_public_admin_feedme_logs](https://cloud.githubusercontent.com/assets/16646294/14140711/4ddeea36-f698-11e5-857a-906661713f09.png)

**Comment by ImDineshSaini** [comment]
Should I have to make news as structure or channel

**Comment by ImDineshSaini** [comment]
Could you please help me to map the RSS entries, how to map the attribute?

**Comment by engram-design** [comment]
@ImDineshSaini Can you please send a help request through the Feed Me page? I know you sent one initially, but would like to see your updated options. Also - it might be worth creating a new issue to not take over this one.

Are you on the Craft Slack channel? It might be more effective providing assistance through there.

**Comment by ImDineshSaini** [comment]
Okay Let me add myself to slack.

**Comment by ImDineshSaini** [comment]
I m there on ImDineshSaini, how could I share my problem there.

**Comment by zizther** [comment]
Thanks for your reply.

I gathered it would support it out the box.

I am not doing anything special, just mapping a plain text field to the
title. It works when I add an entry in Craft, but not when I import.

N
