### ISSUE TITLE
Support for a passkey in anonymous cURL requests

### ISSUE THREAD

**Issue by jonathanmelville** [engram-design/FeedMe#4]
When triggering an import with cron, it would be nice to allow for a passkey in the query since the action can be run anonymously. 

Example: http://mysweetsite.com/index.php/actions/feedMe/feeds/runTask?direct=1&feedId=5&passkey=2758867339

This makes the anonymous action more secure.

**Comment by engram-design** [comment]
@jonathanmelville Thanks as always for the suggestion! Added in the latest release - https://github.com/engram-design/FeedMe#using-with-a-cron-job
