### ISSUE TITLE
Feature requets: Delete should handle dle 404s/invalid json gracefully.

### ISSUE THREAD

**Issue by bstein-clever** [engram-design/FeedMe#41]
On our website, we pull down a feed from a service that's sometimes flaky (invalid or unresponsive).

I love that FeedMe can import into Craft entries - it means Craft can trivially act as a caching mechanism for the data we want to show, and can update only when we want to, without relying on the service. 

However, if the "Duplicate Entry Action" is set to "Delete" (we want to update only with the current data in the feed), and the service is down, the end result is that _all_ of the feed's entries are deleted.

Instead, it seems like FeedMe should leave any entries alone if there's a failure (either connecting and/or parsing the data), and instead only do the full-delete if everything has been successfully read.

What do you think?

**Comment by schimmy** [comment]
+1

**Comment by engram-design** [comment]
Totally agreed, and has been added in Feed Me 2. See also [#98](https://github.com/engram-design/FeedMe/issues/98).

**Comment by schimmy** [comment]
nice, thanks @engram-design !

**Comment by bstein-clever** [comment]
Awesome, thanks!
