### ISSUE TITLE
Never brought to the Field Mapping page

### ISSUE THREAD

**Issue by wfendler** [engram-design/FeedMe#43]
> Click on the `Save and continue` to be taken to the field mapping screen

After clicking this the page refreshes and gives me a "Feed saved" notice at the top of the screen with no other errors or messages.

Working on a fresh install of:
- `Craft CMS 2.6.2780` Personal License
- `Feed Me 1.4.9`

**Comment by engram-design** [comment]
Hi - are you able to submit your feed info through the Help page for Feed Me?

**Comment by wfendler** [comment]
Sent! Thanks.
