### ISSUE TITLE
Craft\FeedMe_FeedModel' not found

### ISSUE THREAD

**Issue by speck1990** [engram-design/FeedMe#45]
I'm using the plugin to move my podcast xml items to entries in a podcast section. I tried running a task to update some entries and it broke my site. Now I am unable to access the admin portion of my site. I receive the following error.

`Fatal error: Class 'Craft\FeedMe_FeedModel' not found in /www/sites/mywebsite/craft/app/helpers/ModelHelper.php on line 587`

I've tried replacing the app folder with a fresh copy, but nothing. Any suggestions?

**Comment by engram-design** [comment]
Have you removed the `feedme` plugin folder, re-downloaded the [last release](https://github.com/engram-design/FeedMe/releases/tag/1.4.10), and installed the plugin again? Seems like it wasn't installed/downloaded properly.

**Comment by speck1990** [comment]
Yes I tried that...It worked perfectly several times. When it broke I was doing the following: I have a podcast section that has everything that a podcast feed would have including publication date field. I wanted the post date to be the same as the publication date so I ran the task once having the pub date in the xml insert the date into the post date. Then I ran it again so that it would update the publication date field. I checked for duplicates on the pub date since that should be unique. I ran the task and it was taking forever, in fact in never finished. I closed out the browser and tried to get back in and it was broke.

**Comment by engram-design** [comment]
Would you be able to clear out the `tasks` table in your database [see here](https://craftcms.com/support/stuck-tasks).

**Comment by speck1990** [comment]
Ok, I tried that...still have the error

**Comment by engram-design** [comment]
Can you go to your `craft_plugins` table and find the row with Feed Me and set `enabled` to 0?

**Comment by speck1990** [comment]
Hmmmm, that's odd...it isn't in the the table

**Comment by engram-design** [comment]
If its not in the table then it means the plugin has been uninstalled, and you're getting that error because something is trying to use Feed Me's classes, but because its uninstalled, it can't. Have you restarted your web server just to clear anything out? I would assume there were stuck tasks or something present if its trying to do something. You can't access your control panel at all?

**Comment by speck1990** [comment]
Yes, I've restarted the web server. Could I remove those tasks instead of just setting them to error? Would that do anything?

**Comment by engram-design** [comment]
Ah - yes you'll want to remove them. Setting them to error can potentially restart the processing. See if that helps?

**Comment by speck1990** [comment]
I just tried restarting my server after making those changes you suggested...that seemed to work. I'm at least able to get to my dashboard. I'm still going to clear out those task anyways. Thanks for your help.

**Comment by engram-design** [comment]
Great - let me know if you come across issues again - not quite sure what caused it to drop off like that.

**Comment by speck1990** [comment]
Yeah, me neither
