### ISSUE TITLE
Only imports one item

### ISSUE THREAD

**Issue by wihodges** [engram-design/FeedMe#47]
The field mapping and import seems to work fine, only problem is: I only see one post populating. I've rerun command and deleted post only to have just one populated. Don't seem to be getting any errors. I've checked the feed url and see multiple entries. Anybody else experience this? Is there limitation on local dev environment?

**Comment by engram-design** [comment]
Are you able to send through a help request? It may very well be something is incorrect with the primary element or duplication handling.

**Comment by wihodges** [comment]
Ah I think that is it, the field I selected to map to 'Title' was actually not unique. But I also found that by switching the Duplicate Entry Action to 'Delete Entries' allowed all the posts to import. For some reason Update and Add entries selection did not pull every post.  

Thanks. Awesome plugin!
