### ISSUE TITLE
Smart quotes not getting encoded properly

### ISSUE THREAD

**Issue by stegrainer** [engram-design/FeedMe#48]
This seems to be happening since I updated to 1.4.10. I haven't made any changes to my feed or the blog engine that drives it. FeedMe seems to be creating duplicate copies of my entries with the smart quotes encoded improperly. (â instead of ’)

My feed is set to "Update Entries" on Duplicate Entry Action, and I have "Check for duplicate" checked on both `title` and `link`. So for now, entries with smart quotes are created as duplicates rather than updating the original.

Here's my feed if you need it for testing: http://uxcellence.com/rss/

And here's a screenshot showing the entries as they appear on my list.

![And here's a screenshot of the different entries.](https://cloud.githubusercontent.com/assets/2728027/14766733/d4583ea2-09e2-11e6-9762-f14250b6cafc.png)

**Comment by engram-design** [comment]
If you could, would you be able to give the latest master a go? Just to be on the safe side.

**Comment by stegrainer** [comment]
I've just installed the latest master. I deleted the duplicates with the incorrect encoding and reran the task for that feed, and it seems to be working properly now.

**Comment by slelorrain** [comment]
Hello, I was facing the same problem since the last update. It also looks good to me with the latest master. Thank you.

**Comment by engram-design** [comment]
@slelorrain Great, thanks for letting me know, and apologies for the issues to you both.
