### ISSUE TITLE
Not mapping url from media:content

### ISSUE THREAD

**Issue by stegrainer** [engram-design/FeedMe#49]
When I attempt to map a feed's media:content to a field in Craft, I'm not seeing any data. The format for media:content places the URL for the image within a URL attribute rather than as content in between opening and closing tags (like most of the other text content in the feed). I'm wondering if that's where the disconnect occurs.

When I attempt to map the field, I can see that the example data (from the most recent entry) doesn't find anything:

![No content for media:content](https://cloud.githubusercontent.com/assets/2728027/14766773/07c69ddc-09e4-11e6-931b-13662d04a75f.png)

But in my feed, the content is there like this:

`<media:content url="http://uxcellence.com/content/images/2016/04/sketch-hacks-1.png" medium="image"/>`

I'm attempting to map the url to a plain text field which I would then use to link to the image on the original feed's server. (I don't expect FeedMe to handle parsing a URL and saving the image to my local Craft site.)

**Comment by engram-design** [comment]
Currently Feed Me only supports content defined between tags, and not attributes.

For example, you could achieve this if your feed layout was:

```
<media:content>
    <url>http://uxcellence.com/content/images/2016/04/sketch-hacks-1.png</url>
    <medium>image</medium>
</media:content>
```

**Comment by engram-design** [comment]
This has finally been added to Feed Me 2.
