### ISSUE TITLE
Built-in Craft fields (title, author, etc.) not available to map to other than the first one.

### ISSUE THREAD

**Issue by dustinwalker** [engram-design/FeedMe#5]
After upgrading to 1.2.1 the ability to map certain fields seemed to be removed: https://dl.dropboxusercontent.com/u/491945/videos/options.mp4 

This happens in both latest Chrome and Safari, on Craft Pro 2.3.2644. Uninstalling and reinstalling FeeMe didn't seem to help. Let me know if you need any additional info.

**Comment by engram-design** [comment]
@dustinwalker Thanks for the video description, fixed in latest commit.
