### ISSUE TITLE
Create multiple entries from one feed?

### ISSUE THREAD

**Issue by shantamg** [engram-design/FeedMe#52]
I want to pull from the [weather underground API's 10 day forecast](https://www.wunderground.com/weather/api/d/docs?d=data/forecast10day) but the data is structured in a way that I need to loop through the returned JSON and create an entry in craft for each of the 10 days. I don't see a way to do that in this plugin, except for just doing it right in the template like:

    {% set params = {
        url: 'http://api.wunderground.com/api/{MY_API_KEY}/forecast10day/q/CA/San_Fransisco.json',
        type: 'json',
        element: 'forecast',
        cache: 3000
    } %}

    {% set feed = craft.feedme.feed(params) %}
    {% for node in feed %}
        {% for day in node.simpleforecast.forecastday %}
          . . .
          {{day.high.fahrenheit}}
          . . .
        {% endfor %}
    {% endfor %}

But then it won't be saved as entries, which I'd like to do.
Any suggestions?

**Comment by engram-design** [comment]
So using `forecast` as your primary element - could you not map `forecastday` to a Matrix or Super Table field? That way, you could map, say `high.fahrenheit` to a text field in one of those field, and you'll have them contained in a single entry.

**Comment by shantamg** [comment]
I'll have to look into Matrix and Super Table. Never done either of those before. So are you saying that one Matrix entry would contain all 10 days?

**Comment by engram-design** [comment]
Yeah - I'm saying one Matrix field could contain all 10 days. Thats going off the below json example:
```
{
	"forecast": {
		"txt_forecast": {
			"date": "8:00 AM PDT",
			"forecastday": [{
				"fcttext": "Overcast in the morning, then clear. High of 75F. Winds from the SSW at 5 to 20 mph."
			}]
		}
	}
}
```

**Comment by shantamg** [comment]
Sounds good but when I go to map the fields in the plugin, it's drilling down too far and I can't just select 'forecastday'.
![screen shot 2016-05-11 at 8 34 00 am](https://cloud.githubusercontent.com/assets/262882/15186811/60df5c34-1753-11e6-88f4-9df6f146acc1.png)

**Comment by engram-design** [comment]
Thats correct behaviour - you can't just automatically 'map everything' in the `forecastday` node - you need to create a field in your Matrix field for each item you want to import.

For instance, you'd potentially have a field for Temperature, High/Low Celsius, Conditions, Icon, etc.

**Comment by shantamg** [comment]
Right, that's what I had thought, and I tried that:
![screen shot 2016-05-11 at 8 55 26 am](https://cloud.githubusercontent.com/assets/262882/15187512/3ca832f2-1756-11e6-8b08-9286fa9ce413.png)

But then when I run the task I get a php error:

    PHP warning
    mb_convert_case() expects parameter 1 to be string, array given

**Comment by shantamg** [comment]
Sorry, I know that's not that helpful. Looking in the stack trace, here's where I think it happens:

    /Users/jasongaluten/Sites/temple_craft/craft/app/services/ElementsService.php(764):     Craft\DbHelper::parseParam("content.title", array(array("epoch" => "1463018400", "pretty" => "7:00 PM PDT on May 11, 2016", "day" => 11, "month" => 5, ...), array("epoch" => "1463104800", "pretty" => "7:00 PM PDT on May 12, 2016", "day" => 12, "month" => 5, ...), array("epoch" => "1463191200", "pretty" => "7:00 PM PDT on May 13, 2016", "day" => 13, "month" => 5, ...), array("epoch" => "1463277600", "pretty" => "7:00 PM PDT on May 14, 2016", "day" => 14, "month" => 5, ...), ...), array(":locale" => "en_us"))

**Comment by shantamg** [comment]
Actually, a little earlier in the stack, here's what happens:

    /Users/jasongaluten/Sites/temple_craft/craft/plugins/feedme/services/FeedMeService.php(57): Craft\FeedMeService->importSingleNode(array("forecastday" => array(array("date" => array("epoch" => "1463018400", "pretty" => "7:00 PM PDT on May 11, 2016", "day" => 11, "month" => 5, ...), "period" => 1, "high" => array("fahrenheit" => "67", "celsius" => "19"), "low" => array("fahrenheit" => "52", "celsius" => "11"), ...), array("date" => array("epoch" => "1463104800", "pretty" => "7:00 PM PDT on May 12, 2016", "day" => 12, "month" => 5, ...), "period" => 2, "high" => array("fahrenheit" => "66", "celsius" => "19"), "low" => array("fahrenheit" => "52", "celsius" => "11"), ...), array("date" => array("epoch" => "1463191200", "pretty" => "7:00 PM PDT on May 13, 2016", "day" => 13, "month" => 5, ...), "period" => 3, "high" => array("fahrenheit" => "64", "celsius" => "18"), "low" => array("fahrenheit" => "49", "celsius" => "9"), ...), array("date" => array("epoch" => "1463277600", "pretty" => "7:00 PM PDT on May 14, 2016", "day" => 14, "month" => 5, ...), "period" => 4, "high" => array("fahrenheit" => "68", "celsius" => "20"), "low" => array("fahrenheit" => "53", "celsius" => "12"), ...), ...)), Craft\FeedMe_FeedModel, array("fields" => array("forecastday/.../date/pretty" => "title", "forecastday/.../date/day" => "forecast[day][day]", "forecastday/.../date/month" => "forecast[day][month]", "forecastday/.../date/year" => "forecast[day][year]", ...)))

So it looks like the data is still nested too deep?

**Comment by engram-design** [comment]
That stack trace isn't all that helpful I'm afraid. What happens when you run the feed directly (click on the small arrow icon next to the delete button). Can you send through a Help Request through Feed Me? That'll give me more information.

**Comment by shantamg** [comment]
Ok, I sent a help request through the control panel. I attached an html file with the php error. Thanks so much for looking at this!

**Comment by engram-design** [comment]
Hmmm, haven't received it yet - just to make sure, you used the Help widget in the Feed Me section and not the Dashboard? Maybe your local server can't send emails out?

**Comment by shantamg** [comment]
Ah, yeah. It's just my local computer so the email probably didn't go out.

**Comment by shantamg** [comment]
Ok, turns out that Feed Me does work great for this if you map the fields to a Matrix. The problem I was having was with weather undergrounds feed having different depths of data.

Mapping  `<simpleforecast/forecastday/.../conditions>` to a Plain Text field in my Matrix field works fine, but if I try to import a field like `<simpleforecast/forecastday/.../high/fahrenheit>` then what I get in the field is `{"fahrenheit":"63","celsius":"17"}` because it is more than 1 deep after the `/.../` and it is returning both values under “high”.

So, since the feed is "crappy", I am pointing Feed Me to a custom php file that gets the weather underground feed and parses it how I want it and exports the data using `json_encode()`
