### ISSUE TITLE
Empty date

### ISSUE THREAD

**Issue by arthurdewolf** [engram-design/FeedMe#53]
I'm importing a JSON feed into a section with a Date field and some of the dates are empty. Whether I set the value to `null` or `''` today's date gets filled in. Is there a way to keep the field empty?

**Comment by engram-design** [comment]
Not at the moment I'm afraid - FeedMe 2.0 will allow you to set field defaults. However, I do feel this goes against how its expected to work, so will mark this to be fixed.

**Comment by lenchantin** [comment]
Seconded. I have an events calendar where some items have a registration cutoff date, but only if registration is required. Therefore, most of my dates get returned as null. 

I'm working around this by testing another field - if the registration link field is not empty - then posting the date. I won't always have the luxury of this kind of workaround, but I use this plugin on many of my client websites. It's uber helpful. :)

**Comment by engram-design** [comment]
Field defaults have finally been added to Feed Me 2.
