### ISSUE TITLE
XML node with sub node: attributes not found

### ISSUE THREAD

**Issue by grafixgeek** [engram-design/FeedMe#54]
I'm not sure if I have this entirely right but it seems to me (using the template method) that when an XML node has a subnode its attributes are not pulled in using `craft.feedme.feed(params)`. The moment I remove the subnodes I can find the attributes.

**Comment by engram-design** [comment]
Sorry for the delay - but I do believe you're correct. I'll add a fix for this.

**Comment by engram-design** [comment]
This should be fixed as of Feed Me 2, due to a re-written XML-parsing method.
