### ISSUE TITLE
Entries filed not exact matching

### ISSUE THREAD

**Issue by thoughtfulweb** [engram-design/FeedMe#56]
I’ve noticed that when importing data into an Entries field it matches multiple values. 

For example, I have a Venues channel, with multiple entries including:
- LONDON Barbican
- LONDON Barbican / Freestage
- LONDON Barbican Fountain Room
- LONDON Barbican Cinema 1

When I import data into an Events channel, with a related Venue field, if the value of the data being imported is just LONDON Barbican, it imports all of the above. Is there anyway to make the search an exact match so it only imports LONDON Barbican?

Great plugin by the way!

Simon

**Comment by thoughtfulweb** [comment]
Having experimented with this, I finally found a solution. It’s not ideal because it requires updating a file (which could get replaced if/when the plugin is updated), however, in case it is useful here’s the changes I made:

In the file feedme > services > FeedMe_FieldsService.php I modified line 234 from:

`$criteria->search = 'title:'.$entry.' OR slug:'.$entry;`

to:

`$criteria->search = 'title::"'.$entry.'" OR slug::"'.$entry.'"';`

Wrapping the $entry with double quotes and using two colons ensures the search is an exact match. See https://craftcms.com/docs/searching for details.

Be aware that searching can be effected by the defaultSearchTermOptions settings if added to Craft’s config.php. See https://craftcms.com/docs/config-settings#defaultSearchTermOptions

In addition and on a slightly different note, I discovered that some entires were not being found/added to an Entries field. The missing entries were ones with a Pending status, so to ensure they were added I inserted the following after line 234 (above):

`$criteria->status = null;`

This fix is for Feedme version 1.4.11

**Comment by engram-design** [comment]
Sorry for my later reply - thanks for your detailed information, I'm going to test this out, as you make a pretty good case. I'll work on a fix for now, but in FeedMe 2.0 you'll have greater control over determining how to match your data with existing data.

**Comment by engram-design** [comment]
This has been fixed as of Feed Me 2. Using the `->search` function is now no longer present - thankfully for performance as well. Titles should match exactly now.
