### ISSUE TITLE
Clear pending feed requests

### ISSUE THREAD

**Issue by theswebsite** [engram-design/FeedMe#57]
Hi,

Is it possible to clear the pending import requests? It looks like I have a feed import that is stuck and about 10 that have now backed up due to cron jobs running.

Many thanks

**Comment by engram-design** [comment]
Not at this stage I'm afraid, but I'll add that to 2.0. For now, its handy to install [TaskManager](https://github.com/boboldehampsink/taskmanager).

**Comment by theswebsite** [comment]
Thank you for the reply and I'll install Task Manager. Feed Me is a great plugin so many thanks for developing it :)

**Comment by marcdebiak** [comment]
Having this same issue. Restart Apache/Nginx crashes the plugin page with Class 'Craft\FeedMe_FeedModel' not found.

craft_tasks table is empty, and the task manager throws an error if I try to stop the task using it.

**Comment by engram-design** [comment]
I've added a "Clear Tasks" button to the Settings in Feed Me 2.
