### ISSUE TITLE
csv file support

### ISSUE THREAD

**Issue by mdxprograms** [engram-design/FeedMe#62]
Is it possible to include csv support?

**Comment by engram-design** [comment]
No plans for CSV support I'm afraid. The problem lies with the lack of nested field support for a CSV format. How would you represent Table, Matrix or Super Table data in a CSV file? It's something I'll address eventually, but very low on the priority list. For now, there's the [Import Plugin](https://github.com/boboldehampsink/import).

**Comment by mdxprograms** [comment]
Thanks, unfortunately import plugin doesn't work well with importing users... FeedMe has worked pretty well for me in the past with my json and xml data.

**Comment by engram-design** [comment]
I am tossing up building in at least partial support - I'd just rather a fully-functioning solution that something half-baked. My solution for the near future would be to write a script converting your CSV to XML/JSON.

**Comment by mdxprograms** [comment]
That would be fantastic. Maybe I could help assist in that process?

**Comment by simplethemes** [comment]
@mdxprograms You can use [DracoBlue/Craur](https://github.com/DracoBlue/Craur) to convert your CSV to JSON.

**Comment by mdxprograms** [comment]
Thanks @simplethemes I'll take a look.

**Comment by timbertens** [comment]
Is CSV support still something that won't be added (in the near future)? I have a use case too. It is a pretty straightforward import, each csv field represents a field in craft. It is true that complex data schemes would be a burden but that always is with CSV to my opinion

**Comment by engram-design** [comment]
@timbertens My arm could be twisted. In Feed Me 2, there will be means to supply your own service to deal with custom data. This means you could add your own implementation of CSV, or even JSON/XML if you wanted. 

Supporting CSV natively isn't something I'm overly fond of - I'm not sure how to fully support all fields (Matrix, Super Table), and as I mentioned, would rather not produce something half-baked.

**Comment by w3studio** [comment]
I have a site using a popular data import add-on for another CMS and imports from uploaded CSV to entries and categories, and image names mapped to files uploaded to assets, wondering if the CSV were exported to from Excel to XML? whether this would mean I could use FeedMe with Craft CMS for the client to run the imports on a monthly basis (wine stock list), thanks.

**Comment by engram-design** [comment]
You can now write your own [Data Type](http://sgroup.com.au/plugins/feedme/developers/data-types) functionality (docs coming shortly) with Feed Me 2, where you can write your own CSV data handling class.

**Comment by siffring** [comment]
You're welcome to use our free CSV helper.
[https://github.com/surprisehighway/craft-feedmehelper](https://github.com/surprisehighway/craft-feedmehelper)

**Comment by engram-design** [comment]
This has been implemented in [3.0.0-beta.1 for Craft 3](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.1).

**Comment by ianyoung** [comment]
@engram-design CSV import is now possible in Feed Me for Craft 3?

**Comment by engram-design** [comment]
@ianyoung That's correct
