### ISSUE TITLE
Update existing and delete all not included in feed

### ISSUE THREAD

**Issue by JonnyTurnerUK** [engram-design/FeedMe#63]
When 'update' is selected under 'Duplicate Entry Action' all works perfect and updates as expected, however, we also need to delete entries that are not included in the feed. Is this possible?

Previously we've used DataGrab for EE which had this functionality so trying to replicate for Craft.

**Comment by engram-design** [comment]
Sure - you'll want to select `Delete`. Check out the tooltip on that field which says:
```
Delete Entries: Delete all existing entries in this section, adding only entries from this feed. Be careful. For example - "I want only the entries from this feed in this section."
```

**Comment by JonnyTurnerUK** [comment]
Ah, I when I read that, I was under the impression it deleted all entries so nothing existed then added them again. Once we add our stock, we have another feed that looks-up info for the products which costs per lookup so want to keep that information and just update but delete old stock.

I'll give it a go now. Thanks for the super quick reply!

**Comment by engram-design** [comment]
Ah gotcha - thats actually exactly what it does. It will delete all entries, then add only the ones in that particular feed. I suppose maybe that a better option going forward...

**Comment by JonnyTurnerUK** [comment]
Yeah just tried it and yep, all deleted - doh! We're in dev credentials at the mo so doesn't cost us anything just but will soon. Is it a big job to add that functionality or is it worth us delving into the code and attempting to adapt it ourselves?

**Comment by engram-design** [comment]
I've got a few bug fixes to do in the next few days, so might schedule it in then. I'm thinking of changing the current delete function to act this way, as I don't believe you'd need both options (delete all then add vs. update and delete entries not in feed). Are you pressed for time?

**Comment by JonnyTurnerUK** [comment]
That would be excellent. We'll be going live over the next two weeks so no big rush. Really appreciate it.

**Comment by JonnyTurnerUK** [comment]
Hey Josh, did you manage to have a look into adding this as a feature?

**Comment by engram-design** [comment]
I've just reworked the current delete strategy to make this work as expected. I think functionally its the same, so I'm replacing the current strategy for now. I'm not sure if there's a case where you'd need to ditch existing data, but maybe I'll add in later.

Would you be able to give the latest master a spin?

**Comment by JonnyTurnerUK** [comment]
Awesome, thanks! Definitely, will give it a go.

**Comment by engram-design** [comment]
Closing for now - please re-open if not working for you.
