### ISSUE TITLE
Matrix block order out of sync from JSON import

### ISSUE THREAD

**Issue by thoughtfulweb** [engram-design/FeedMe#64]
I’m really struggling to get a Matrix block imported in the correct order so I have my fingers-and-toes crossed that you can help.

I am creating a JSON file using P&T’s ElementAPI plugin.

To output the Matrix field data, you need to create and empty array and add data to this array as it loops through the blocks. If the data isn’t nested then the second value overwrites the first in the array. With this in mind, I get the following nested output:

`{
    "data": [
        {
            "Body": {
                "text": [
                    {
                        "Body": "<p>This entry contains content for all blocks to test the import</p>"
                    },
                    {
                        "Body": "<p>Another text block</p>"
                    }
                ],
                "video": [
                    {
                        "YouTube URL": "https://www.youtube.com/watch?v=LtMunDW_cBc"
                    },
                    {
                        "YouTube URL": "https://youtu.be/X7FxX1l2u0I"
                    }
                ]
            }
        }
    ]
}`

Feedme does a great job importing all this data, with the first values for each block imported in the correct order, however, the second value gets appended to the end in an unordered sequence. 

Maintaining the order on import is essential for the project I am working on, so I wondered if there is a way to do this. 

It would be easy to add each block’s sort order as an additional value, but I guess this would need to be processed by Feedme in some way.

Do you have any ideas?

**Comment by thoughtfulweb** [comment]
I have noticed that there is some commented out code within FeedMe_FieldsService.php towards the bottom (line 472-491) that seems to refer to my idea of passing the block sort order attribute within the block data. 

I have (temporarily) uncommented this code, however, it seems to have no effect. 

I am sure it is commented out for a reason, but from what I understand this method would certainly help with my issue.

Here’s a reduced example of the code generated with the additional order attribute:

`{  
   "data":[  
      {  
         "Body":{  
            "text":[  
               {  
                  "Body":"<p>This entry contains content for all blocks to test the import<\/p>",
                  "order":"1"
               },
               {  
                  "Body":"<p>Another text block<\/p>",
                  "order":"9"
               }
            ],
            "video":[  
               {  
                  "YouTube URL":"https:\/\/www.youtube.com\/watch?v=LtMunDW_cBc",
                  "order":"3"
               },
               {  
                  "YouTube URL":"https:\/\/youtu.be\/X7FxX1l2u0I",
                  "order":"8"
               }
            ]
         }
      }
   ]
}`

Any help/guidance would very much appreciated. 

I would even be willing to pay for your time to look into this as it is key to my project.

Thanks,

Simon

**Comment by thoughtfulweb** [comment]
I was wondering if you’ve had a chance to consider this?

With customisation, would it be possible to retrieve the sortOrder value from the craft_matrixblocks table and use it for the order value in FeedMe’s prepMatrix function?

As far as I can work out, this value is derived iterating through the array on line 284 of FeedMe_FieldsService.php

Any assistance would be really appreciated as this has stopped me in my tracks.

Thanks,

Simon

**Comment by engram-design** [comment]
Hey @thoughtfulweb sorry for my lack of response here! Looking into it now

**Comment by engram-design** [comment]
@thoughtfulweb Would you mind posting what would be your expected output from your example? For instance, I need to know your field setup, as my testing seems to order things as I'd expect.

See below screenshots of two different Matrix field with two ways fields are setup. The first one each a different block for Body and Video, while the second in a single block with Body and Video fields.

![screen shot 2016-06-23 at 11 08 43 pm](https://cloud.githubusercontent.com/assets/1221575/16304167/9845a6ae-3997-11e6-9309-16b13387dcca.png)

**Comment by thoughtfulweb** [comment]
Thanks for taking the time to look into this. I really do appreciate it.

Here’s the screenshot from Site A:

![original](https://cloud.githubusercontent.com/assets/1379783/16305273/f538aa1a-3950-11e6-80f5-9ba314ffd2e7.png)

In this reduced example, I have only used two block types, but the Content Matrix field contains multiple blocks. As you can see, I have ordered these block as TEXT VIDEO TEXT VIDEO 

After import, the blocks are ordered TEXT TEXT VIDEO VIDEO like this in Site B:

![imported](https://cloud.githubusercontent.com/assets/1379783/16305264/ee783fb0-3950-11e6-8a04-964ba40c2886.png)

I need to retain the same order in both Site A and Site B.

As mentioned, I am using P&T ElementAPI plugin to generate the JSON file from Site A. The matrix data it generates is nested, which creates markup like:

```
{  
   "data":[  
      {  
         "Body":{  
            "text":[  
               {  
                  "Body":"<p>This entry contains content for all blocks to test the import<\/p>",
                  "order":"1"
               },
               {  
                  "Body":"<p>Another text block<\/p>",
                  "order":"3"
               }
            ],
            "video":[  
               {  
                  "YouTube URL":"https:\/\/www.youtube.com\/watch?v=LtMunDW_cBc",
                  "order":"2"
               },
               {  
                  "YouTube URL":"https:\/\/youtu.be\/X7FxX1l2u0I",
                  "order":"4"
               }
            ]
         }
   ]
}
```

Essentially this:

```
Body
   text
      body
      body
   video
      YouTube URL
      YouTube URL
```
If it is not nested this way then the second instance of **body** or **YouTube URL** overwrites the first.

I can’t see anyway to generate the markup like this:

```
Body
   text
      body
   video
      YouTube URL
   text
      body
   video
      YouTube URL
```
which I imagine FeedMe prefers.

Having nosed around the code in FeedMe_FieldsService.php I noticed that you’ve commented out code that looks for and order attribute, which I can easily add to the JSON file (as shown in my sample code above).

I was wondering if there is any way to use the value of this attribute to set the order which would overcome the issue of nested data like this?

Thanks,

Simon

**Comment by engram-design** [comment]
Happy to add that code back in - my testing has shown that to produce the output you expect (give your second example with an order attribute).

For instance, using:
```
{  
    "data":[  
        {  
            "title": "Title",
            "Body":{  
                "text":[  
                   {  
                      "Body":"<p>This entry contains content for all blocks to test the import<\/p>",
                      "order":"1"
                   },
                   {  
                      "Body":"<p>Another text block<\/p>",
                      "order":"3"
                   }
                ],
                "video":[  
                   {  
                      "YouTube URL":"https:\/\/www.youtube.com\/watch?v=LtMunDW_cBc",
                      "order":"2"
                   },
                   {  
                      "YouTube URL":"https:\/\/youtu.be\/X7FxX1l2u0I",
                      "order":"4"
                   }
                ]
            }
        }
    ]
}
```

And uncommenting the Matrix processing code in `FeedMe_FieldsService.php`, I get:

![screen shot 2016-06-24 at 6 32 43 pm](https://cloud.githubusercontent.com/assets/1221575/16332600/107be0d2-3a3a-11e6-99b8-914c10ae255f.png)

Is this desired behaviour?

**Comment by thoughtfulweb** [comment]
Thanks, but just uncommenting that code results in the issue I mentioned when opening this ticket.

If I extend the basic example I’ve given with another (different) block at the end of this order as so:

```
 "Body":{  
    "text":[  
       {  
          "Body":"<p>This entry contains content for all blocks to test the import<\/p>",
          "order":"1"
       },
       {  
          "Body":"<p>Another text block<\/p>",
          "order":"3"
       },
       {  
          "Body":"<p>Another text block 3<\/p>",
          "order":"5"
       }
    ],
    "video":[  
       {  
          "YouTube URL":"https:\/\/www.youtube.com\/watch?v=LtMunDW_cBc",
          "order":"2"
       },
       {  
          "YouTube URL":"https:\/\/youtu.be\/X7FxX1l2u0I",
          "order":"4"
       }
    ],
    "gallery":[  
       {  
          "Title":"Gallery",
          "Images":"http:\/\/new.serious.dev\/images\/images\/1_NW_Album_Shot_920x550.jpg|, http:\/\/new.serious.dev\/images\/images\/131120_Somi_s4_003_by_Glynis_Carpenter.jpg|, http:\/\/new.serious.dev\/images\/images\/15_Nov_Pieranunzi_Zirilli_Guascoyne_Vortex_carousel.jpg|",
          "order":"6"
       }
    ]
 },

```

This results in:

```
Body
   text
      body
   video
      YouTube URL
   gallery
      Gallery
   text
      body
   video
      YouTube URL
   text
      body
```

It appears to be adding any new top-level blocks before it renders the rest of the nested content so, in effect, out of order.

I have also noticed that dropdown fields do not import properly.

I would be happy to give you access to both websites on our development server if that would help, but would need to email you login credentials.

Simon

**Comment by thoughtfulweb** [comment]
In fear of becoming an irritation, I really do need some help with this. 

As there are no other plugins that come close to this fantastic plugin I am eager to use FeedMe, but this issue has really stopped me in my tracks. I would happily pay for your time to look into this.

I have tried to debug this so I can send more accurate information or fix the issue myself but it is sadly it is proving to be beyond my skills.

Everything I try doesn’t seem to allow the matrix order to be retained and now the dropdown fields have stopped importing data too. See https://github.com/engram-design/FeedMe/issues/66

**Comment by engram-design** [comment]
@thoughtfulweb I apologise for not getting back to you sooner - I'm extremely under the pump with other commitments at the moment, and haven't had a chance to take a deep-dive into this issue. Having said that, I've been looking into this issue since you've requested it, but may very well be a deeper issue. I'm also diving time up between other plugins and Feed Me 2.

I'm working towards a solution, and will let you know in 24 hours.

**Comment by thoughtfulweb** [comment]
Thanks and I apologise for applying unwanted pressure. I really do appreciate your help an understand that you’ll have other things going on in your life.

I look forward to hearing from you once you’ve had the chance to review these issues. Cheers.

**Comment by engram-design** [comment]
@thoughtfulweb Thanks for your patience. So first off - `postForFieldType()` isn't for using an `order` item in your feed, it was actually put there to re-order Matrix blocks post-import. This was fixed a few releases back, but kept just in case there was some weirdness going on. Its not really relevant here, and simply wont work, because you're not mapping the `order` item in your feed to anything.

What you're trying to achieve is straying from the norm of how Feed Me should import your data. If you provide Feed Me with the following:

```
"Body":{  
    "text":[  
       {"Body":"<p>This entry contains content for all blocks to test the import<\/p>"},
       {"Body":"<p>Another text block<\/p>"},
       {"Body":"<p>Another text block 3<\/p>"}
    ],
    "video":[  
       {"YouTube URL":"https:\/\/www.youtube.com\/watch?v=LtMunDW_cBc"},
       {"YouTube URL":"https:\/\/youtu.be\/X7FxX1l2u0I"}
    ]
 }
```
It will import in that order:
```
Body
Body
Body
YouTube
YouTube
```
However - Feed Me lets you perform post-processing on data through a hook. I would recommend creating a plugin that does your custom sorting of data. Normally I would suggest a middle-man script between your feed and Feed Me, but as its coming from another Craft install, this might be easier.

Additionally, to actually get the sorting to work to your needs, you'll need to create a Plain Text field in each Matrix block - otherwise Feed Me doesn't know anything about the order attribute.

I've created a [Gist](https://gist.github.com/engram-design/ae0e93ed198f01c78b9e5ab24b1a3497) for you to get going with this additional plugin.

Let me know what you think and how that works for you. You may need to pull the latest master which comments back that code in `postForFeedMeFieldType`, which might mess the ordering up.

**Comment by thoughtfulweb** [comment]
This worked perfectly! 

Thank you so much for helping find a solution for this issue.

For anyone else who may stumble across this post, the additional **feedmecustomsort** plugin works perfectly if you are trying to import a JSON feed created using P&T’s ElementAPI plugin, as the data in a Matrix field needs to be nested.

Just make sure you add an additional **Sort order** field to each Matrix block you’re importing with the field handle **sort**. 

Of course, you also need to make sure this data appearis in your JSON file. I used `'sortOrder' => $block->sortOrder`
