### ISSUE TITLE
Any way to import assets?

### ISSUE THREAD

**Issue by subratom** [engram-design/FeedMe#65]
I have about 50K+ items that I need to import into CMS. I tried importing by seleting them by it will take forever and more importantly it makes no sense for me to keep a tab on which was last uploaded if I have to upload so many of them.

Any way to upload assets in one specific folder?

**Comment by engram-design** [comment]
Feed Me 1.x.x only supports entries. Feed Me 2.0 will support importing Assets. You could achieve something for your particular case by writing a simple plugin that imports a folder of assets.

**Comment by subratom** [comment]
Do you have a timeline for the next release? If it's in near future, I can always create a band-aid solution and use your solution when it's out. 

I ask because I am still learning this CMS and not really sure how to proceed with this. Of course this is in no way meant to push you to finish this as this is your product and I appreciate all of your efforts you have put in so people like me can use it.

**Comment by engram-design** [comment]
Couldn't tell you I'm afraid - its pretty much a rewrite, so there's no ETA on it being ready. But we're realistically talking in the next few months. 

Why not ask on the Craft Slack channel? I'm sure someone would have written a small plugin to achieve this! I've done it on a small-scale for one of our projects.

**Comment by subratom** [comment]
Thank you, I will see if anyone has a solution. If not, can you guide me on where to begin?

**Comment by engram-design** [comment]
If you've not had a great deal of plugin development (but still experienced in PHP), I'd have to suggest starting with [Mijingo Craft Plugin Development](https://mijingo.com/products/screencasts/craft-plugin-development/) - its very good. I also have a _very_ specific plugin created for a previous project [BatchImageUpload](https://github.com/engram-design/BatchImageUpload). This basically took a JSON feed of image urls and bulk-uploads them.

**Comment by subratom** [comment]
I have purchased that course and I am going to sit down and go through it to understand the plugin development. Thanks, also appreciate your help, replies and this plugin itself

**Comment by engram-design** [comment]
We've added uploading of Assets in Feed Me 2.
