### ISSUE TITLE
Key "19" for array with keys "13, 15, 16, 17, 18, 22, 23" does not exist

### ISSUE THREAD

**Issue by lexbi** [engram-design/FeedMe#68]
Not sure how I've managed this, had the plugin disabled for a while, tried to re-enable it, now I get this error, any ideas? I've updated the plugin to your most recent version, though still getting the same thing:

    Key "19" for array with keys "13, 15, 16, 17, 18, 22, 23" does not exist

    build/craft/plugins/feedme/templates/feeds/index.html(46)

    34                 {% for feed in feeds %}
    35                     {% set section = craft.sections.getSectionById(feed.section) %}
    36 
    37                     <tr data-id="{{ feed.id }}" data-name="{{ feed.name | t }}">
    38                         <td>{{ feed.id }}</td>
    39                         <td><a href="{{ url('feedme/feeds/' ~ feed.id) }}">{{ feed.name | t }}</a></td>
    40                         <td>{{ feed.feedType | upper }}</td>
    41                         <td>{{ feed.feedUrl }}</td>
    42                         <td>{{ (section | length > 0) ? section.name : '' }}</td>
    43                         <td>
    44                             {% if section | length > 0 %}
    45                                 {% set entryTypes = section.getEntryTypes('id') %}
    46                                 {{ entryTypes[feed.entrytype].name }}
    47                             {% endif %}
    48                         </td>
    49                         <td>{{ feed.duplicateHandle | capitalize }}</td>
    50                         
    51                         <td><a href="{{ url('feedme/runTask/' ~ feed.id) }}">{{ 'Run Task' | t }}</a></td>
    52 
    53                         <td class="thin action">
    54                             {% set directUrl = actionUrl('/feedMe/feeds/runTask', { direct: true, feedId: feed.id, passkey: feed.passkey }) | replace(craft.config.cpTrigger ~ '/', '') %}
    55                             <a href="{{ directUrl }}" target="_blank" class="direct fa-icon" title="{{ 'Direct feed link' | t }}" role="button"><i class="fa fa-external-link"></i></a>
    56                         </td>
    57                         
    58                         <td class="thin action"><a class="delete icon" title="{{ 'Delete' | t }}" role="button"></a></td>

**Comment by engram-design** [comment]
Couldn't say without looking at your feed and what version you updated from. Are you able to send through a Help request through Feed Me?

**Comment by lexbi** [comment]
This is just from trying to view the page after clicking the "feedme" link in the craft sidebar

**Comment by lexbi** [comment]
done

**Comment by engram-design** [comment]
Oh, yeah you're right! You've probably removed an entry type or section along the way, and it can't find it. I'll work in better error-handling for that, its been on my todo list for a long while...

**Comment by lexbi** [comment]
Ah, yes, I have removed an entry type since installing and working with it.

That would be very much appreciated, thanks!

**Comment by lexbi** [comment]
As it may help others, until you get around to sorting this, you can still view the import pages at:
`/admin/feedme/feeds/1` (1 being the ID of the feed)
`/admin/feedme/feeds/new`

**Comment by engram-design** [comment]
Fixed in the latest master.

**Comment by lexbi** [comment]
Thanks so much!
