### ISSUE TITLE
FR: import to Craft Commerce products

### ISSUE THREAD

**Issue by stevieg83** [engram-design/FeedMe#69]
Would love to see this added

**Comment by engram-design** [comment]
Coming in [Feed Me 2.0](https://github.com/engram-design/FeedMe/tree/2.0.0).

**Comment by stevieg83** [comment]
Nice - what's the status of it right now?

**Comment by engram-design** [comment]
No ETA, but probably 50% of the way to beta.

**Comment by engram-design** [comment]
Added in [Feed Me 2](http://sgroup.com.au/plugins/feedme).
