### ISSUE TITLE
FeedMeError - Columns and data did not match, could be due to malformed feed

### ISSUE THREAD

**Issue by ginkelb** [engram-design/FeedMe#7]
I'm trying to run an import but i keep getting this error. Even when i tell the system to only import the title and the slug and ignore all other fields. Have also tried eliminating all the other fields in the XML, with no result.

Could you point me in the right direction?

Log	Date
"Started importing node: 0"	14 mei 2015 18:43:32
{"feed":[],"items":1,"logsId":"15"}	14 mei 2015 18:43:32
"FeedMeError - Columns and data did not match, could be due to malformed feed."	14 mei 2015 18:43:32

XML feed = http://www.calco.nl/development/export

Bas

**Comment by engram-design** [comment]
@ginkelb happy to have a look, sorry for the delayed response. Would you mind posting a screenshot of your current mapping and field settings? Happy to chat directly through Slack if that suits you as well.

From what I can tell, it may just be an issue of the primary element being incorrect, as it's working fine in my tests. Have a look at the attached screenshots.

![craft-dev-office-feedme-feeds-22-1431870591496](https://cloud.githubusercontent.com/assets/1221575/7670641/acef9afa-fcef-11e4-9e05-a78671d97b8b.png)
![craft-dev-office-feedme-feeds-22-1431870568140](https://cloud.githubusercontent.com/assets/1221575/7670642/acf50ca6-fcef-11e4-858a-b393fa3345fd.png)

**Comment by engram-design** [comment]
@ginkelb Have you had any luck with the settings I've provided? Happy to help :smiley:

**Comment by ginkelb** [comment]
Hi John,

i solved the issue via another route. So i haven’t been able to test this.

Met vriendelijke groet,
Bas van Ginkel


Bas van Ginkel
Online Strateeg
030 8200 271 | 06 29 51 69 00
http://www.ditiserg.nl | bas@ditiserg.nl
Grebbeberglaan 15, 3527VX Utrecht (routebeschrijving)
         


Op 19 juni 2015 bij 16:59:01, Josh Crawford (notifications@github.com) schreef:

@ginkelb Have you had any luck with the settings I've provided? Happy to help
