### ISSUE TITLE
Incorrect times when importing to a date/time field type

### ISSUE THREAD

**Issue by omglolwtf** [engram-design/FeedMe#72]
I'm importing a raw ISO date timestamp from a JSON feed and saving it as a date/time field type in Craft. It's working fine, but the imported dates are off - by 1 hour earlier.

For example, **2016-07-09T11:00:00** from the feed becomes 10am when it should be 11am.

I assume this might be daylight savings related, but I'm not sure if this is something FeedMe is doing when it imports to the date field or it's something to do with Craft itself? My timezone in Craft's general settings is correctly set to my local time.

Thanks!

**Comment by omglolwtf** [comment]
Seems to be fixed in a [recent Craft CMS update](https://craftcms.com/changelog#build2795):
> Updated jQuery Timepicker to 1.11.1, fixing some issues for users Eastern Australia.

**Comment by engram-design** [comment]
Closing for now, and seemingly fixed.
