### ISSUE TITLE
Set Default Values for Entries Pulled In From Feed

### ISSUE THREAD

**Issue by crookedneighbor** [engram-design/FeedMe#74]
The plugin works great for data that exists in the feed you're pulling from, but if there is data that you know will always be the same, but can't be pulled from the feed, it requires you to go in and manually update each item.

For instance, if I'm pulling from a Soundcloud feed, I might want to set some meta data about it for every entry. Maybe something as simple as "Source: Soundcloud" or add a category automatically. Many, but not all tracks, will be included on the site, so I may want to mark them as not enabled so a staff member can approve them for inclusion.

**Comment by engram-design** [comment]
Definitely being added into Feed Me 2! https://github.com/engram-design/FeedMe/tree/2.0.0

**Comment by crookedneighbor** [comment]
That's awesome! Any idea for when it will be released?

**Comment by engram-design** [comment]
Added in [Feed Me 2](http://sgroup.com.au/plugins/feedme).
