### ISSUE TITLE
Allow empty Expiry Date

### ISSUE THREAD

**Issue by thoughtfulweb** [engram-design/FeedMe#75]
I have a need to import a blank expiry date, however, Craft will automatically add the current timestamp if a null value is passed to the expiryDate field.

To overcome this I made a modification to version 1.4.12, which I thought worth sharing as it non destructive.

I have change line 86-93 in services > FeedMe_EntryService.php from:

```
// Set expiry date
$expiryDate = FeedMe_Element::ExpiryDate;
if (isset($fields[$expiryDate])) {
    $d = date_parse($fields[$expiryDate]);
    $date_string = date('Y-m-d H:i:s', mktime($d['hour'], $d['minute'], $d['second'], $d['month'], $d['day'], $d['year']));

    $element->$expiryDate = DateTime::createFromString($date_string, craft()->timezone);
}
```

to:

```
// Set expiry date
$expiryDate = FeedMe_Element::ExpiryDate;
if (isset($fields[$expiryDate])) {
    $d = date_parse($fields[$expiryDate]);
    $date_string = date('Y-m-d H:i:s', mktime($d['hour'], $d['minute'], $d['second'], $d['month'], $d['day'], $d['year']));
    if ($d['year']) {
      $element->$expiryDate = DateTime::createFromString($date_string, craft()->timezone);
    } else {
      $element->$expiryDate = '';
    }
}
```

The simple conditional checks if a the date has a value for the Year. If not then it passes an empty string.

If this can not been introduced into the plugin then I hope it helps someone else who needs to achieve the same thing.

**Comment by engram-design** [comment]
Thanks for supplying this fix. This will be much more improved in v2, where you'll be able to provide a default value for dates (and every other field).

**Comment by shantamg** [comment]
Any idea how to modify this to work for a custom date time field? I have a field that I'm mapping to that I'd like to set to blank but it defaults to the current date and time.

**Comment by engram-design** [comment]
You could achieve this by using the provided fieldtype hooks to add a case for your datetime field - https://github.com/engram-design/FeedMe/wiki/Hooks#prepforfeedmefieldtype.

This will be addressed in [Feed Me 2](https://github.com/engram-design/FeedMe/tree/2.0.0) however.

**Comment by shantamg** [comment]
I don't want to modify the FeedMe plugin, but a very easy solution would be to change the prepDate function (in ) from this:

    return DateTimeHelper::formatTimeForDb(DateTimeHelper::fromString($data, craft()->timezone));

to this:

    return $data ? DateTimeHelper::formatTimeForDb(DateTimeHelper::fromString($data, craft()->timezone)) : '';

But, like I said, I don't want to modify FeedMe, and I can't quite see how to do it using the prepforfeedmefieldtype hook. How would I check for an empty date in the incoming JSON and set the date to empty in the entry?

**Comment by shantamg** [comment]
In other words, is there a way to access the original data that was brought in from the JSON file? In the prepforfeedmefieldtype hook, the fields have already been prepped so I can't know which ones were blank.

**Comment by shantamg** [comment]
Well, here's what I did. Not ideal, but it's working for me... haha.

      public function prepForFeedMeFieldType($field, &$data, $handle)
      {
        if ($field->type == 'Date') {
          // if the date is less than 10 seconds ago then
          // we assume it was set from a blank field to the current time
          if (strtotime($data[$handle]) - time() < 10) {                                                                              
            $data[$handle] = '';
          }
        }
      }

**Comment by engram-design** [comment]
Using `prepForFeedMeFieldType` is what this sort of thing is for - but totally agree that altering this in core field handling is the way to go. I'll look at adding this in the short term.

**Comment by shantamg** [comment]
I know this won't be an issue in 2.0 with defaults, but in the mean time here's a question... 

Do you think it should be expected behavior for an empty string to become the current time? I suppose if we are talking about the post date that might make sense but if post date were mapped then there should be a date being passed in, right? In other words, do you think people are relying on being able to send an empty string in the JSON and get the current date time?

At any rate, I would like to know if there's a way to get the original string that came from the JSON within `prepForFeedMeFieldType`.

**Comment by engram-design** [comment]
Its a good point, and probably something a simple checkbox can fix (use today's date by default vs leave empty).

And sadly not - the `prepForFeedMeFieldType` is called after core fieldtype behaviour, so its already changing the `$data` variable. Arguably, I'm likely to change this atomic variable. Let me test out your original code, as I believe providing no data should leave the field blank.

**Comment by engram-design** [comment]
Should be fixed in [Feed Me 2](http://sgroup.com.au/plugins/feedme).
