### ISSUE TITLE
Radio button importing using label

### ISSUE THREAD

**Issue by thoughtfulweb** [engram-design/FeedMe#76]
I’ve noticed that radio buttons are being imported using their label, rather than value.

Would it make sense to update line 330 in services > FeedMe_FieldsService.php from:

```
if ($data == $option['label']) {
```

to:

```
if ($data == $option['value']) { 
```

**Comment by engram-design** [comment]
Thats correct! I made this change to the Dropdown field - totally forgot to check elsewhere. Thanks, and fixed in the latest master.
