### ISSUE TITLE
Import Strategy Request - Update Only?

### ISSUE THREAD

**Issue by miralize** [engram-design/FeedMe#77]
Basically I have some info thats pulled from an API but the entries themselves were manually created & curated. I want to update some info on the entries and I dont want to create new ones but I do want the ones that are created to accept the new data. 

Is that currently possible with FeedMe?

**Comment by engram-design** [comment]
Not currently, but you raise a good point. I'm thinking of re-working the import strategies in v2 to not be mutually exclusive, and more a checkbox. So you'd be able to tick any of:

- Add entries that don't already exist in your section
- Update entries that already exist in your section
- Delete any entry in this section not found in this feed

But I'm happy to make this change straight away, should be in the next release. Thanks!

**Comment by miralize** [comment]
That would be awesome!

**Comment by engram-design** [comment]
Just added this in [2.0 beta 2](https://github.com/engram-design/FeedMe/tree/2.0.0).

![screen shot 2017-01-29 at 4 24 55 pm](https://cloud.githubusercontent.com/assets/1221575/22402112/7d76169c-e63f-11e6-8ce4-2755e66adf21.png)
