### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by aelvan** [engram-design/FeedMe#8]
Hi,

After creating an import and running it, I get the following error on the FeedMe control panel frontpage:

https://www.dropbox.com/s/7g7lq3wmeoputdw/Screenshot%202015-05-15%2009.52.53.png?dl=0

This is probably due to the fact that I have a multilanguage site set up, with this in my config:

   'siteUrl' => array(
        'no' => 'http://' . $_SERVER['SERVER_NAME'] . '/no/',
        'en' => 'http://' . $_SERVER['SERVER_NAME'] . '/en/',
    ),

In front-end templates, doing {{ craft.config.siteUrl }} works just fine. Not sure if this is a Craft or FeedMe bug?

**Comment by engram-design** [comment]
@aelvan Sorry for the delay! Fixed in the latest release. Totally hadn't thought of that scenario, so appreciate the input :)
