### ISSUE TITLE
Add ability to send user agent string with feed requests

### ISSUE THREAD

**Issue by oblongd** [engram-design/FeedMe#80]
Please provide a setting to define a custom user agent string and include it via CURLOPT_USERAGENT when retrieving feeds.

This feature request is a response to weather.gov (and similar sites) requiring inclusion of a user agent string in the header to uniquely identify the requestor of any XML feed. If no user agent string is present, their servers reject the request and return a 403 error.

**Comment by engram-design** [comment]
Added configuration file in [Feed Me 2](http://sgroup.com.au/plugins/feedme).
