### ISSUE TITLE
Duplicate data check doesnt work. Always returns first entry.

### ISSUE THREAD

**Issue by subratom** [engram-design/FeedMe#84]
So I mentioned this in my earlier issue but I thought it would make sense to create a new issue because the duplication check has failed and I had worked around this issue thinking it is only me who had this issue. Someone on Slack asked a same question. 

So here is the issue, when I check title & content (RTF) to avoid insertions, I noticed it was always returning the first entry it successfully inserted. After that each entry is skipped, I checked the id and it was always the same for other items that it was trying to insert. 

Is there I can do to help and look into this issue?

**Comment by engram-design** [comment]
A help request through Feed Me would be a great start, just so I can replicate things on my end to help with troubleshooting.

**Comment by engram-design** [comment]
This should be fixed in [Feed Me 2](http://sgroup.com.au/plugins/feedme), but let me know if not.
