### ISSUE TITLE
Did image mapping stop working?

### ISSUE THREAD

**Issue by subratom** [engram-design/FeedMe#85]
I think I remember it working but I am not sure right now, I am uploading data using json feed and I have images in HTML field. I thought that I didnt have to give it a path and plugin was looking up images and mapping it correctly.
But right now it definitely doesnt seem to work, can you tell me if I am just dreaming about this or this feature existed in previous version?

**Comment by engram-design** [comment]
Image-mapping works just fine for Asset fields, but its a little more difficult for images inside HTML content, and mapping to Rich Text fields.

Feed Me has never altered content like that, so you might have been dreaming of this! I have to say, I don't think I'll ever implement this, as I'd rather a hands-off approach to content. What if (for some reason), I wanted to have external images in my content? I don't believe Feed Me should make this call.

A solution for this - one I've used myself - is to create a script in that parses your JSON feed, modifies the HTML as needed, and outputs is again as JSON. If you like, happy to share some code to get you started.

**Comment by subratom** [comment]
You are right, I was dreaming when I wrote that as an issue.
