### ISSUE TITLE
Option for matrix fields to overwrite data or not

### ISSUE THREAD

**Issue by michaelhwinter** [engram-design/FeedMe#88]
Add an option for matrix fields that lets you choose whether or not to overwrite the existing data? We had this in datagrab and it would be fantastic to see it here

**Comment by engram-design** [comment]
Smart-mapping for Matrix fields has been added in [Feed Me 2](http://sgroup.com.au/plugins/feedme). This essentially looks at the existing Matrix data with the data its about to overwrite, and skips if its the same.
