### ISSUE TITLE
Unmapped fields in updated entry are destroyed

### ISSUE THREAD

**Issue by shantamg** [engram-design/FeedMe#89]
Take this scenario:

1. A feed's import strategy is set to "Add and Update Existing"
2. The task is run and and entry is created.
3. A user adds content to fields in that entry that are not mapped in the feed
4. The task is run again

I would expect that mapped fields would update when the feed is re-run and that other data in that entry which is not mapped in the feed would remain intact.

What in fact happens is that the fields which are not mapped become empty.  :(

**Comment by engram-design** [comment]
This certainly shouldn't happen. Any field that you select `Don't Import` in your mapping screen will not be touched. I know this for a fact, as many sites we have Feed Me implemented on require this.

If this is happening for you, can you confirm what your mapping setup is? Either through screenshots, or by sending a Help request.

**Comment by shantamg** [comment]
You can only select Don't Import on a field in the incoming JSON. I'm saying that existing fields on the entry are being overwritten because there is no corresponding field in the JSON.

**Comment by shantamg** [comment]
I see what's happening. The feed maps to a particular block in a matrix field and then if other blocks are added to that matrix field they will be deleted when the feed runs again. Does that make sense? Shall I send a help request?

**Comment by engram-design** [comment]
Ah - now if we're talking about Matrix fields (or Super Table fields), then yes - Feed Me will overwrite all blocks in your Matrix fields, with just the ones in the feed. All other fields are not touched as I mentioned earlier. There's obviously a little bit of logic involved to try to match existing Matrix blocks (and whether they should be added or updated). I think people have used hooks to write their own comparison logic, as its a pretty intensive check.

So are we talking about Matrix fields, or regular fields?

**Comment by shantamg** [comment]
Yeah, now we're at the issue. It's a matrix field. Any chance there's something around to get me started if I were to write a hook to do the comparison?

**Comment by engram-design** [comment]
If memory serves, I believe @lindseydiloreto may have written something to handle this...

**Comment by lindseydiloreto** [comment]
As @engram-design said, this is a little tricky for Matrix, Super Table, and Neo fields. When you run the Feed Me import, it's really only looking at the "outer" fields, not the "inner" fields.

In a nutshell, you'll basically want to loop through and re-save all existing blocks. This gives you the opportunity to update any existing data (based on your own custom logic), and add or remove blocks as necessary.

Here's a pared down version of one I did recently...

In this example, the `$anchor` is the specific data point which will help determine if each block is new or old. Ideally, this would be some sort of ID value, but it can realistically be anything.

```php
// Unpack JSON during import
public function postForFeedMeFieldType(&$fieldData, $entry)
{

    // Initialize existing blocks array
    $existingBlocks = array();

    // Get existing data
    $originalData = $entry->mySuperTableField->find();

    // Loop through existing blocks
    foreach ($originalData as $block) {
        $existingBlocks[$block->anchor] = array(
            'blockId'     => $block->id,
            'subfieldOne' => $block->subfieldOne,
            'subfieldTwo' => $block->subfieldTwo,
        );
    }

    // Get imported data
    $importedData = json_decode($fieldData['myJsonData'], true);

    // Counter for new ST blocks
    $i = 1;

    // Initialize ST data
    $superTableData = array();

    // Loop through imported blocks
    foreach ($importedData as $anchor => $newData) {

        // Check if block already exists
        if (array_key_exists($anchor, $existingBlocks)) {

            // UPDATE EXISTING BLOCK

            // Get existing block info
            $oldData = $existingBlocks[$anchor];

            // Existing block ID
            $blockId = $oldData['blockId'];

            // Update subfield data
            $subfieldData = array(
                'anchor'      => $anchor,
                'subfieldOne' => $oldData['subfieldOne'],
                'subfieldTwo' => $oldData['subfieldTwo'],
            );

        } else {

            // ADD NEW BLOCK

            // New block ID
            $blockId = 'new'.$i++;

            // New subfield data
            $subfieldData = array(
                'anchor'      => $anchor,
                'subfieldOne' => $newData['subfieldOne'],
                'subfieldTwo' => $newData['subfieldTwo'],
            );

        }

        // Add ST block
        $superTableData[$blockId] = array(
            'type'    => 1,
            'enabled' => true,
            'fields'  => $subfieldData
        );

    }

    // Add ST blocks data
    $fieldData['mySuperTableField'] = $superTableData;

}
```

---

**Disclaimer:** The code example above may contain mistakes. This was a quick attempt to make my snippet more generic. Additionally, I cannot provide any support for this code... It is for educational purposes only.

**Comment by shantamg** [comment]
Thank you @lindseydiloreto. This should get us moving in the right direction, thanks!

**Comment by engram-design** [comment]
@lindseydiloreto Thanks for your input! A great resource for others to have too.

**Comment by shantamg** [comment]
Could you explain to me the best place to put this code where it won't get overwritten by updates?

**Comment by shantamg** [comment]
Oh, I see. I guess I can make my own plugin.

**Comment by lindseydiloreto** [comment]
Yup, that's exactly right! You'd put that code in the main PHP file of your plugin.

If you need a good starting point, you can use either this [plugin template](https://github.com/lindseydiloreto/craft-businesslogic), or this [plugin generator](https://pluginfactory.io/).

**Comment by shantamg** [comment]
I have spent some time playing with this and I am realizing that this is a beast of a thing to try and do, especially if the matrix has many block types with many different types of fields in them.

First of all, [the hook](https://github.com/engram-design/FeedMe/wiki/Hooks#postforfeedmefieldtype) only takes one argument, so all we get is the fieldData. This means that to get the corresponding existing entry we have to do something like this:

    public function postForFeedMeFieldType(&$fieldData) {
      $criteria = craft()->elements->getCriteria(ElementType::Entry);
      $criteria->section = 'calendar';
      $criteria->regId = $fieldData['regId']; // uniquely identifying field
      $entry = $criteria->first();
 
`$fieldData` is an array, but `$entry` is an [EntryModel object](https://craftcms.com/docs/templating/entrymodel).

From there, we can to loop through the blocks in the matrix field (ours is called `pageBuilder`):

      foreach ($entry->pageBuilder as $i => $block) {

Getting all of the fields turns out to be a bit crazy (lots of googling, testing, logging, and more googling):

        foreach ($block->getFieldLayout()->getFields() as $fieldLayoutField) {
          $field = $fieldLayoutField->getField();

Then, we can get the field handle with `$field->handle`, but the values are yet another story. The value can be retrieved with `$block->getFieldValue($field->handle)` but that value might be an integer or a string (great!), or another Craft object (like RichTextData or SingleOptionFieldData, etc.).

I was originally thinking that we could loop through the blocks of the existing entry and build an array of key values that could be added to `$fieldData`, but with as many block types as we have and as many different fields as there are in each block type it would be a monster endeavor. We'd have to check at each depth for all of the object types and treat them case by case, and still I'm not sure exactly how that would all need to be formatted for `$fieldData`. Quite prone to errors down the line if anything changes in Craft.

Sheesh.

**Comment by engram-design** [comment]
@shantamg Sorry for the delay in responding.

`postForFeedMeFieldType` now accepts the element you're working on as a second parameter - `postForFeedMeFieldType($fieldData, $element)`. That might help things in your case.

I'm working on building in a few permanent solutions to this for Feed Me 2.
