### ISSUE TITLE
Task Run but no data import?

### ISSUE THREAD

**Issue by keithmancuso** [engram-design/FeedMe#9]
I tried a simple xml import task and it runs but no data is created?

Its a simple xml file that just has two <item></item> in it.  It shows the correct fields in the field mapping setup, the task runs and completes but then no data is created.

I was getting PHP errors at first but then i raised the memory limits and those went away, but still no actual data created.  Nothing in either of the feed me log tables either?

Any ideas?

**Comment by keithmancuso** [comment]
here is the xml data by the way.  For now i was only importing the Title from  <title></title> and still nothing was getting import

<item>
  <title>Opening weekend brings Family Festival, Polo, art exhibits and more to Governors Island </title>
  <link>http://govislandblog.com/2008/06/02/opening-weekend-brings-family-festival-polo-art-exhibits-and-more-to-governors-island/</link>
  <pubDate>Mon, 02 Jun 2008 14:45:05 +0000</pubDate>
  <dc:creator>erapuano</dc:creator>
  <guid isPermaLink="false">http://govislandblog.wordpress.com/?p=61</guid>
  <description/>
  <content:encoded><![CDATA[<a href="http://govislandblog.files.wordpress.com/2008/06/2008_05_31-551.jpg"></a><a href="http://govislandblog.files.wordpress.com/2008/06/2008_05_31-75.jpg"><img class="alignnone size-medium wp-image-64" src="http://govislandblog.files.wordpress.com/2008/06/2008_05_31-75.jpg?w=300" alt="" width="300" height="225" /></a>Opening weekend on Governors Island was a great success, bringing more than 3,000 people to enjoy the family festival, Figment's Emergence exhibit, the Sculptors Guild's "In Site," the first polo match on the Island in more than seven decades, and a book signing by acclaimed author Linda Fairstein. All in all, it was a great start to the Island's biggest season yet.]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>61</wp:post_id>
  <wp:post_date>2008-06-02 14:45:05</wp:post_date>
  <wp:post_date_gmt>2008-06-02 14:45:05</wp:post_date_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>open</wp:ping_status>
  <wp:post_name>opening-weekend-brings-family-festival-polo-art-exhibits-and-more-to-governors-island</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>post</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <category domain="category" nicename="upcoming-events"><![CDATA[Upcoming Events]]></category>
  <wp:postmeta>
    <wp:meta_key>_edit_last</wp:meta_key>
    <wp:meta_value><![CDATA[3969231]]></wp:meta_value>
  </wp:postmeta>
</item>
<item>
  <title>Car-free biking on Governors Island </title>
  <link>http://govislandblog.com/2008/06/02/car-free-biking-on-governors-island/</link>
  <pubDate>Mon, 02 Jun 2008 14:54:13 +0000</pubDate>
  <dc:creator>erapuano</dc:creator>
  <guid isPermaLink="false">http://govislandblog.wordpress.com/?p=65</guid>
  <description/>
  <content:encoded><![CDATA[<a href="http://govislandblog.files.wordpress.com/2008/06/2008_05_31-11.jpg"></a>
<p style="text-align:center;"><img class="size-medium wp-image-71" src="http://govislandblog.files.wordpress.com/2008/06/bicycles.jpg?w=300" alt="" width="300" height="224" /></p>
<p style="text-align:left;">This weekend marked the first time that visitors could rent a bike on <a title="About Governors Island" href="http://govislandblog.com/about-governors-island/" target="_blank">Governors Island</a>. <a title="Bike and Roll Bike Rentals and Tours" href="http://http://www.bikeandroll.com/locations/nyc.aspx" target="_blank">Bike and Roll</a> will rent adult bikes, children's bikes and bike surreys from now until October 5th. Visitors can also bring their own bikes to enjoy more than one mile of car free cycling in the middle of New York Harbor.</p>]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>65</wp:post_id>
  <wp:post_date>2008-06-02 14:54:13</wp:post_date>
  <wp:post_date_gmt>2008-06-02 14:54:13</wp:post_date_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>open</wp:ping_status>
  <wp:post_name>car-free-biking-on-governors-island</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>post</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <category domain="post_tag" nicename="bike-and-roll"><![CDATA[Bike and Roll]]></category>
  <category domain="post_tag" nicename="bikes"><![CDATA[Bikes]]></category>
  <category domain="post_tag" nicename="biking"><![CDATA[biking]]></category>
  <category domain="post_tag" nicename="car-free"><![CDATA[car free]]></category>
  <category domain="post_tag" nicename="governors-island"><![CDATA[governors island]]></category>
  <category domain="post_tag" nicename="new-york"><![CDATA[New York]]></category>
  <category domain="post_tag" nicename="new-york-city"><![CDATA[New York City]]></category>
  <category domain="post_tag" nicename="new-york-harbor"><![CDATA[New York Harbor]]></category>
  <category domain="category" nicename="weekend-report"><![CDATA[Weekend Report]]></category>
  <wp:postmeta>
    <wp:meta_key>_edit_last</wp:meta_key>
    <wp:meta_value><![CDATA[3969231]]></wp:meta_value>
  </wp:postmeta>

**Comment by engram-design** [comment]
Closing - solved through Slack! The issue being no Duplicate Field was ticked. Fixed in the latest release.
