### ISSUE TITLE
Feature request: Mass assign fields and import entries as disabled

### ISSUE THREAD

**Issue by oadslug** [engram-design/FeedMe#90]
It would be great if we could mass assign fields during the import process. (i.e. assign a category or author to all imported entries, or arbitrarily set a field).

Here are a couple use cases:
- Currently 'labels' from blogger are not importing to 'categories' in craft (for some reason it is not part of the ATOM feed or not formatted properly). To get around this I am importing 'posts' by label separately (via feed URL parameters) and then writing a custom script to mass assign categories to newly imported entries. A rather time consuming process.
- Another scenario is that a required field in craft is not part of the imported data, and the import fails. To work around this issue I temporarily need to set the field as 'not required' in craft; perform the import; then mass assign the field using a custom script (or manually); then reset the field to required.

As far as UI goes, to implement this, I might suggest reversing the matching columns — meaning list all fields in the field layout, and then offer a select dropdown to match the imported field data, or an entry field to mass assign data. Just an idea.

Likewise, it would also be extremely useful to be able to import entries as 'not enabled', if for example the entries need to cleaned, or additional data needs to be entered before being made public.

And have to add — love this plugin. I can't thank you enough!

**Comment by engram-design** [comment]
Totally agree - all these things are coming in [Feed Me 2](https://github.com/engram-design/FeedMe/tree/2.0.0). If you're at all interested, mapping will look something like the below.

![screen shot 2016-09-21 at 1 59 08 pm](https://cloud.githubusercontent.com/assets/1221575/18697341/a07e94b8-8003-11e6-87fd-843df6791961.png)

**Comment by oadslug** [comment]
Very Cool. Exactly what I was thinking. Huge thank you for all the great work! — Douglas

**Comment by engram-design** [comment]
Field defaults have been added in [Feed Me 2](http://sgroup.com.au/plugins/feedme).
