### ISSUE TITLE
devMode false causes 500 error

### ISSUE THREAD

**Issue by niekjansenNL** [engram-design/FeedMe#92]
Hi,

When we disable the devMode on our live-environment, the view for mapping the feed throws an 500 error exception. When I enable the devMode, the mapping-page is rendered correct and I can map the values to the right columns.

We're using version: 1.4.12

Does anyone has a suggestion or a solution?

**Comment by engram-design** [comment]
Anything in your `phperrors.log` file? Or `feeme.log`?

**Comment by niekjansenNL** [comment]
Hi,

Srry, didn't let you know that the problem was solved.
Somehow it magically worked again, so I still don't know what the problem was...

Thanks for your response anyway! 😄
