### ISSUE TITLE
Assets inside matrix field aren't being assigned while importing data

### ISSUE THREAD

**Issue by subratom** [engram-design/FeedMe#94]
So I have tried everything to get data into CMS but asset field remains un-assigned. All the assets are inside of their individual directories. Can you take a look and see why it may be failing? Or even just tell me what to look for and I will debug.

**Comment by subratom** [comment]
So after digging through the code, using a lot of dd & log entries I figured out that Craft wasn't able to return ids when the filename was passed in for the asset. I had to put in some createcommand code to look up file name and then create an array and work from there.

**Comment by engram-design** [comment]
Your assets are in subfolders correct? Craft's native element search doesn't seem to like that (from memory). There are ways around It I believe, but may need to investigate further, or wait for Feed Me 2.

**Comment by subratom** [comment]
No, I was mistaken when I mentioned it to you on Slack, I have 6 or so different kinds of folders and each of them is an entry in CraftCMS (so each folder on the drive points to one folder in Craft). One asset folder does have subfolders but none of the other ones worked either.

**Comment by engram-design** [comment]
You've lost me - each folder is an entry? Can you provide a sample of your feed? Have you tried searching the asset value you've got in your feed in the Assets Index? Anything returned? ie - you're trying to map `My_File.jpg` to an existing asset called that. If you can search for it in the Assets Index, then there might have an issue...

**Comment by subratom** [comment]
`[
	{
		"ContentID": 59813,
		"Id": 4119,
		"CurrentId": 76,
		"Title": "some-title",
		"Slug": "some-title",
		"Parent": "",
		"Ancestors": "",
		"Author": "admin",
		"Post Date": "2012-03-04 00:00:00",
		"Expiry Date": null,
		"Enabled": "Yes",
		"Status": "live",
		"Summary": "Designed to meet the stringent requirements of fiber-optic telecom applications, the M675S02 series of low-jitter SiGe voltage-controlled SAW-based oscillators . . .",
		"Sub Title": "",
		"Contents": "<div>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</div>",
		"Meta Tags": "",
		"ArticleType": "Features",
		"Primary Article Classification": "Another category",
		"Companies": "Company name",
		"Primary End Markets": "industrial",
		"Image Thumbnail": "cscn25 apr2012",
		"HotTopic": "0",
		"DownloadList": [
		  {
			"DownloadType": "datasheets",
			"DownloadValue": "idt_m675s02-ds_dst_20120222_120226201231.pdf"
		  }
		]
	  }
	]`


Here is a sample json file. Yes I have one folder called documents and under which I have 6 subfolders. So under assets I have entry for each of those folders pointing it to the exact subfolder location So datasheets point to /var/www/craftcms/public/documents/datasheets, literature points to /var/www/craftcms/public/documents/literature and so on.

In assetindexdata table, the whole path is mentioned /var/www/craftcms/public/documents/datasheets/some.pdf So if I search for the whole path I can see it, may be that's the issue that I need to provide the whole path?

**Comment by engram-design** [comment]
This should be fixed in [Feed Me 2](http://sgroup.com.au/plugins/feedme).
