### ISSUE TITLE
Search index bloat

### ISSUE THREAD

**Issue by cole007** [engram-design/FeedMe#96]
Not sure if this is a Craft thing or a Feedme thing but we have a large, multi-lingual site (5,000+ entries) and we are using Feedme to input news on the site. Because of an issue with the source feed (not using a constant unique identifier) we are deleting existing entries on each import.

We had been noticing performance issues on the site and noticed that the search index had 25m+ rows! Rebuilding the search index shaved this down to a mere 350,000+ rows. Again, not sure if this is a Craft thing or a Feedme thing but my gut feeling is that with new entries added daily and this being replicated across 5 locales, the search index is not being cleared out or refreshed.

Is this something to take up with Craft folk or is something that can be done in Feedme (eg, triggering a hook to reindex). Thoughts?

**Comment by engram-design** [comment]
This should be much improved in [Feed Me 2](http://sgroup.com.au/plugins/feedme), but would love to get some tests done.

**Comment by engram-design** [comment]
Feed Me 2 no longer uses searching, and shouldn't really effect search index bloat.
