### ISSUE TITLE
Background task created, not running

### ISSUE THREAD

**Issue by ginkelb** [engram-design/FeedMe#97]
Hi Josh,

Feed Me has always worked fine for me but after updating my systems this morning i've been hitting a wall.

Feed Me does create the background task in the database but it never starts running. So no error messages to share either. 

Do you have any idea where I could start looking?

Greetz,
Bas van Ginkel

Craft CMS 2.6.2949
Feed Me 1.4.12
and other background tasks, UpdateElementSlugsAndUris, does run normally.

**Comment by madebyshape** [comment]
I had a similar issue, and to fix it I updated Craft & FeedMe, made sure my fields weren't marked as 'Required'.

I also found that feeds that were previously created didn't import, they stuck at '1'. So I just recreated the import in FeedMe and they work fine.

**Comment by lexbi** [comment]
I am getting this also. 

The cron seems to run, and creates the task, but, they only run when you login to the backend.

Is this intended?

Looks like there is an action to run pending tasks as discussed here:
https://craftcms.stackexchange.com/questions/1359/triggering-the-start-of-a-task-from-a-cron-job

`http://example.com/actions/tasks/runPendingTasks`

**Comment by engram-design** [comment]
First, if you haven't done so, give the 2.0 beta a run.

Regarding how they run @lexbi thats pretty much what Feed Me does - however, its a little more complicated than that. 

Tasks are run in a particular way (via Ajax) so as not to lock up the control panel. I've found through considerable testing that calling `craft()->tasks->runPendingTasks();` essentially takes over requests to Craft (front and back), causing it to freeze or lock up. Fortunately, this is only for the current browser session you're on, so wouldn't affect users on a production site. Still - its a pain if each time you want to run a Feed, particularly a large one, the CP locks up.

How are you triggering the cron by the way? Depending on your setup, you might need to try something like: `curl -H "X-Requested-With: XMLHttpRequest" http://domain.com/index.php/actions/feedMe/feeds/runTask?direct=1&feedId=1&passkey=kcKYqS61bF`

**Comment by lexbi** [comment]
Hey Josh,

Thanks for getting back to me.

I'm on the 2.0beta.

I understand that it can lock the CP up, but when running a cron I would expect the task to be started, not, queued up waiting for someone to login?

I logged in the next day after setting cron every 15m for example and had looooads queued up ready to go (glad you added the clear tasks button for that).

Is there another less demanding way to trigger the tasks to start?

Crons have been triggered as you've suggested in your docs:

    curl --silent --compressed "http://your.domain/actions/feedMe/feeds/runTask?direct=1&feedId=1&passkey=FwafY5kg3c"

For the moment I set a cron for the minute after the above example, which then calls the run tasks action. This does work, though is there a better way to deal with that?

**Comment by engram-design** [comment]
@lexbi Thats exactly what should happen - there should be no need to trigger the CP. Are you testing this locally, or on a staging/production server? I'd be really interested to see your setup if possible (ping me on Slack if you want to discuss)

**Comment by engram-design** [comment]
@lexbi Just to follow up on this, and after investigation, you're totally correct that its not triggering correctly when run via cron. This has now been fixed in the [latest master](https://sgroup.com.au/plugins/feedme/download).

**Comment by lexbi** [comment]
Wahey, thanks dude, I'll try this out asap.

**Comment by engram-design** [comment]
Not a problem - the thought hadn't occurred to me that the JS that triggers the task running will never get fired running from the command line - because it doesn't have a browser! Seems totally obvious in hindsight...
