### ISSUE TITLE
If JSON is empty, FeedMe deletes the latest entry

### ISSUE THREAD

**Issue by joshua-martin** [engram-design/FeedMe#98]
We're using ElementAPI to return updates made in the last 24 hours (for example) in the 'News' channel. We then run a nightly cron with FeedMe to sync the news on another site.

However, we have noticed that if the JSON file is empty then FeedMe is deleting the latest entry from the channel. We tested this running FeedMe manually with an empty JSON endpoint and each time it was removing the latest entry.

Is there a way to exit the FeedMe import if the JSON it is using has no elements?

**Comment by engram-design** [comment]
This is now fixed as of Feed Me 2, so I'll close this for now. Feed Me will check if the feed is empty, and quit processing immediately. Appreciate the issue submission.
