### ISSUE TITLE
"Delete old and Update existing" is not exactly true

### ISSUE THREAD

**Issue by shantamg** [engram-design/FeedMe#99]
The "Delete old and Update existing" import strategy actually deletes all entries and then freshly imports the feed. In most cases that is ok, but it is not exactly what is expected.

I have a case where I want the entries that are not in the feed to be deleted, but I want to update the existing entries from the feed (based on "Check for duplicate"). The reason is that I want fields that are not mapped to be preserved.

**Comment by engram-design** [comment]
This was changed a little while ago for this reason (see https://github.com/engram-design/FeedMe/issues/63). It used to be the case where all entries were deleted first, then the feed was run.

Now, when the feed is run, it first updates all existing entries, then deletes entries not found in the feed. A crucial difference if you've got other fields you're not mapping in Feed Me, which would be lost when the entry is blindly deleted first.

Are you able to confirm this?

**Comment by shantamg** [comment]
Ok, but when you choose "Delete old and Update existing", the "check for duplicate" option is not there on the mapping screen.

By the way, you might consider rewording "check for duplicate" to say something more like "Unique identifier" or something like that. Check for duplicate is a little strange, since what you're trying to do is avoid duplicates. Just an opinion.

Thanks for maintaining this excellent plugin. It's totally essential!

**Comment by engram-design** [comment]
Ah yes - I see what you mean now. I'm just about to release the beta for Feed Me 2, so if you can hold on 'till then, I'll ensure this is cleared up there.

**Comment by shantamg** [comment]
Thanks

**Comment by engram-design** [comment]
FYI - it should be much clearer being in a separate section (where I can actually describe what its for). Happy to get feedback to ensure its clear.

![screen shot 2016-10-26 at 10 03 55 am](https://cloud.githubusercontent.com/assets/1221575/19707500/a2d0a172-9b63-11e6-829b-ea566a383e02.png)

**Comment by shantamg** [comment]
Ooh, that looks awesome.

**Comment by engram-design** [comment]
Closing for now due to slightly better implementation in 2.0. I've also taken on board your renaming suggestion for "Unique identifier".
